project:
  type: website
  preview:
    port: 4200

website:
  title: "Item Response Warehouse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Getting Started with the IRW Data
      - text: "IRW Data"
        menu:
        - href: data.qmd
          text: Browse the IRW Data
        - href: standard.qmd
          text: The IRW Data Standard
        - href: contribute.qmd
          text: Contributing Data to the IRW
        - href: docs.qmd
          text: Data Documentation
      - text: "More"
        menu:
        - href: research.qmd
          text: Examples of IRW-related research
        - href: about.qmd
          text: About the IRW
        - href: training.qmd
          text: Training Resources
        - href: contact.qmd
          text: Contact Us!
    right:
      - icon: github
        menu:
          - text: "Data processing"
            href: https://github.com/ben-domingue/irw/tree/main/data
          - text: "irwpkg: R package for managing IRW data"
            href: https://hansorlee.github.io/irwpkg/

format:
  html:
    theme:
      - cosmo
      - scss/global.scss
    toc: false
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 0px
    callout-icon: false
    df-print: kable
    code-fold: true


execute: 
  echo: false
  message: false
  warning: false
  error: false
