project:
  type: website
  preview:
    port: 4200

website:
  title: "Item Response Warehouse"
  google-analytics: G-NM0Y0TP4RY
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Data"
        menu:
        - href: overview.qmd
          text: Overview of IRW Data Standards
        - href: data.qmd
          text: Browse the IRW Data
        - href: metadata.qmd
          text: Metadata for IRW tables
        - href: docs.qmd
          text: Data Documentation
        - text: "---"
        - href: itemtext.qmd
          text: Item Text Standard
        - href: itemtext_desc.qmd
          text: Item Text Descriptives
        - href: itemtext_issues.qmd
          text: Known Issues
        - href: itemtext_merge.qmd
          text: Merging with IRW data
        - text: "---"
        - href: standard.qmd
          text: The Core IRW Data Standard
        - href: comps_standard.qmd
          text: The Competition Data Standard
        - href: nominal_standard.qmd
          text: The Nominal Data Standard
        - href: simsyn.qmd
          text: Simulated and Synthetic Data
        - text: "---"
        - href: contribute.qmd
          text: Contributing Data to the IRW
      - text: "Get Started"
        menu:
        - href: getstarted.qmd
          text: Getting Started
        - href: training.qmd
          text: Training Resources
        - href: problems.qmd
          text: Problem Set Examples
      - text: "Vignettes"
        href: ./vignettes/index.qmd
        menu:
        - href: ./vignettes/index.qmd
          text: All Vignettes
        - href: ./vignettes/imv.qmd
          text: Calculating IMV Values
        - href: ./vignettes/diffsim.qmd
          text: Difficulty Simulation
        - href: ./vignettes/2pl_across_datasets.qmd
          text: Dispersion in Discrimination parameters
      - text: "About"
        menu:
        - href: about.qmd
          text: About the IRW
        - href: research.qmd
          text: Research!
        - href: othersites.qmd
          text: Related data resources
        - href: contact.qmd
          text: Contact Us
    right:
      - icon: github
        menu:
          - text: "Data processing"
            href: https://github.com/itemresponsewarehouse/misc/tree/main/data
          - text: "irw: R package for managing IRW data"
            href: https://itemresponsewarehouse.github.io/Rpkg/

format:
  html:
    theme:
      - cosmo
      - scss/global.scss
      - resources/scss/main.scss
    toc: false
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 0px
    callout-icon: false
    df-print: kable
    code-fold: true


execute: 
  echo: false
  message: false
  warning: false
  error: false

