project:
  type: website
  preview:
    port: 4200

website:
  title: "Item Response Warehouse"
  google-analytics: G-NM0Y0TP4RY
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getstarted.qmd
        text: Getting Started
      - text: "IRW Data"
        menu:
        - href: data.qmd
          text: Browse the IRW Data
        - href: standard.qmd
          text: The IRW Data Standard
        - href: metadata.qmd
          text: Metadata for IRW tables
        - href: contribute.qmd
          text: Contributing Data to the IRW
        - href: docs.qmd
          text: Data Documentation
        - href: itemtext.qmd
          text: Item Text
      - text: "Tutorials"
        menu:
        - href: diffsim.qmd
          text: Difficulty Simulation
        - href: training.qmd
          text: Training Resources
      - text: "Competitions"
        menu:
        - href: comps_standard.qmd
          text: The Competition Data Standard
      - text: "More"
        menu:
        - href: about.qmd
          text: About the IRW
        - href: research.qmd
          text: Examples of IRW-related research
        - href: othersites.qmd
          text: Related data resources and publications
        - href: contact.qmd
          text: Contact Us!
    right:
      - icon: github
        menu:
          - text: "Data processing"
            href: https://github.com/itemresponsewarehouse/misc/tree/main/data
          - text: "irw: R package for managing IRW data"
            href: https://itemresponsewarehouse.github.io/Rpkg/

format:
  html:
    theme:
      - cosmo
      - scss/global.scss
    toc: false
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 0px
    callout-icon: false
    df-print: kable
    code-fold: true


execute: 
  echo: false
  message: false
  warning: false
  error: false

