---
title: "About"
---

* Information about the nature of the datasets (including links and citations) are available in the [Documentation page](docs.qmd). Code used to generate the harmonized versions of the dataset can be found on [GitHub](https://github.com/ben-domingue/irw).

* Funding for the IRW was provided by the Stanford Office of the Vice Provost and Dean of Research (VPDoR) and the Jacobs Foundation. Thank you to these funders!

* **A [manuscript](https://link.springer.com/article/10.3758/s13428-025-02796-y) describing the IRW is available.**

* [This website](https://github.com/langcog/irw_site) is made using:
  + [Quarto](https://quarto.org/),
  + with interactive visualizations in [Observable](https://observablehq.com/),
  + and hosted on [GitHub pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages).
  + The data are stored on [Redivis](https://redivis.com/).

* If you want to access the data directly on Redivis, see the [guide to getting started](https://docs.redivis.com/guides/getting-started).


If you use data, we encourage you to note that you used the IRW and to cite the preprint. Thank you!

# Contributors

* The IRW was created by [Ben Domingue](https://profiles.stanford.edu/benjamin-domingue) (Graduate School of Education, Stanford University). 


* This website was made in collaboration with [Mike Frank](http://web.stanford.edu/~mcfrank/) and [Mika Braginsky](https://mikabr.io/) (Psychology Department, Stanford University).


* Additional contributors include 

  + Arthur Pan
  + Rochelle Lundy
  + [Susu Zhang](https://psychology.illinois.edu/directory/profile/szhan105)
  + [Klint Kanopka](https://klintkanopka.com)
  + Lucy Caffrey-Maffei
  + [Lijin Zhang](https://lijinzhang.com/)
  + Yiqing Liu
  + Hang Yu
  + [Josh Gilbert](https://scholar.google.com/citations?user=OCdG4IgAAAAJ&hl=en)
  + [Savira Dwia Nadela](https://www.linkedin.com/in/saviranadela/)
  + [Radhika Kapoor](https://scholar.google.com/citations?user=rpM1LoEAAAAJ&hl=en&oi=ao)
  + João Moreira
  + [Hansol Lee](https://scholar.google.com/citations?user=vmcet8AAAAAJ&hl=en)
  + [Mike Hardy](https://www.linkedin.com/in/michael-hardy-education/)
  + [Huanxiao Wang](https://whxiao210.github.io/)
  + Samuel Enrique
  + Xingyi Zhang
  + [Mathias Becerra Sanchez](https://www.linkedin.com/in/mathbecsan/)
  + Rubina Shrestha
  + Luis Anunciação
  + Ayaan Gupta
  + Nishka Jain
