---
title: "The Competition Data Standard"
---

Note: This is an experimental feature.

The IRW competition data standard is meant to describe data derived from pairwise comparisons or competitions. Such data are widely analyzed using ELO or Bradley-Luce-Terry approaches; more information about these approaches is available [here](https://www.annualreviews.org/content/journals/10.1146/annurev-statistics-040722-061813). The key distinction between these data and the conventional IRW data is that there are not `id` and `item` identifiers here but rather identifers of the two `agents` that are involved in a given competition.

- `agent_a` name/id of first competitor
- `agent_b` name/id of second competitor
- `date` Time of the data point in UNIX format.
- `homefield` Indicator of agent that had advantage based on game features (e.g., where game was played, who played first, etc).
- `score_a` Score of `agent_a`.
- `score_b` Score of `agent_b`.
- `winner` Winner of the competition (typically based on a comparison of scores). Values will be `agent_a`, `agent_b` or `draw`.

Documentation related to the tables can be found [here](https://docs.google.com/spreadsheets/d/1WZZYyVC2cmw8CUJM69qP0F_ZlQjQfdkCZbdsG-8mUrs/edit?usp=sharing).
