---
title: "Contributing data to the IRW"
---

We welcome contribution of new datasets to the IRW! Compatability with the IRW data standard is an essential requirement of data included in the IRW and so we first describe methods of ensuring comparability before a discussion of how a properly formatted dataset can be contributed to the IRW.


## Constructing an IRW-compliant dataset

Below are critical instructions for formatting data for the IRW. 

1. Numeric values of a response should be meaningful. For example, missing values cannot be coded as numbers (e.g., -9).

2. Please check that the `id` and `item` identifers have an appropriate number of unique values.

3. Additional data elements (e.g., `rt`, `date`, `wave`, `rater`, `qmatrix`) should all be formatted as specified above. 

4. If there are multiple scales available, the responses need to be split into mutiple files (one per scale). If multiple groups are assessed via the same scale, these data can be put into a single file (if desired, a column indicating group membership can be added).

While we have tried to offer generic guidance on formatting data to the IRW standard, there are innumerable idiosyncracies that may merit additional conversation. To discuss specific  issues associated with your formatting your data to the IRW standard, please feel free to each out to us at `itemresponsewarehouse@stanford.edu`. We would be happy to talk more! You can also use the [IRW Dataset Builder](https://irw-dataset-builder.streamlit.app/) that will help port data to the IRW data standard if you like. 

## Adding data to the IRW

To add properly formatted data to the IRW repository there are three todo items: 

1. Create a Github issue for this repository that describes any decisions you had to make and also includes a file with data (in CSV format).

2. Once the IRW team has confirmed that the data is appropriate, submit a pull request so that the code used to format the data gets added [here](https://github.com/ben-domingue/irw/tree/main/data). The pull request should go to the original repository (not your forked version of it) and to the main branch. 

3. Finally, work with the IRW team to ensure that the 'data index' page  [here](https://docs.google.com/spreadsheets/d/1nhPyvuAm3JO8c9oa1swPvQZghAvmnf4xlYgbvsFH99s/edit#gid=0) gets updated with the relevant information. 

Completion of these three steps will place the data in the IRW repository. This will be reflected on the Redivis site and the website at our next scheduled update time.
