---
title: "The Nominal Data Standard"
---

Note: This is an experimental feature.

## The data standard

The IRW nominal data standard is meant to describe data wherein responses are nominal and not ordinal. There are two distinct types of such data. The first type involves responses in a necessarily finite (but nominal) set of mutually exclusive categories; a typical example here might be the specific option from a multiple choice item that is selected. The second type involves responses that are potentially infinite; examples here would be constructed responses like essays. 

- `text`: This is the nominal version of `resp`.

## Accessing the nominal data

Documentation related to the tables can be found [here](https://docs.google.com/spreadsheets/d/12tM4vADKcUm5LGOGRwQ5_HKkdYa3mZUaKbFUqgs2U_w/edit?gid=0#gid=0).

## An example

Let's look at an example of how we can fit the nominal response model to a table (`preference_inventory`) from the nominal branch of the IRW and generated category response functions for all items..

::: panel-tabset
## R

```{r}
#| echo: true
df<-irw::irw_fetch("preference_inventory",source='nom')
resp<-irw::irw_long2resp(df,resp_col='text')
resp$id<-NULL
library(mirt)
m<-mirt(resp,1,'nominal')
f<-function(mod,n) {
    extr <- extract.item(mod,n)
    Theta <- matrix(seq(-6,6, length.out=2000))
    pr <- probtrace(extr, Theta)
    list(Theta,pr)
}
out<-list()
for (n in 1:ncol(resp)) out[[n]]<-f(m,n)
##
par(mfrow=c(4,3),mgp=c(2,1,0),mar=c(3,3,1,1))
cols<-c("black","red","blue","green")
for (i in 1:length(out)) {
    plot(NULL,xlim=c(-5,5),ylim=0:1,xlab='theta',ylab='Pr')
    z<-out[[i]]
    for (j in 1:4) lines(z[[1]],z[[2]][,j],col=cols[j])
}
```
:::
