<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tag Quality – Item Response Warehouse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a4aace43a0bb780eb35e26eaacb6ac4f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-NM0Y0TP4RY"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-NM0Y0TP4RY', { 'anonymize_ip': true});
</script>


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Item Response Warehouse</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data">    
        <li>
    <a class="dropdown-item" href="./overview.html">
 <span class="dropdown-text">Overview of IRW Data Standards</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data.html">
 <span class="dropdown-text">Browse the IRW Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./collections.html">
 <span class="dropdown-text">Browse IRW Collections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./metadata.html">
 <span class="dropdown-text">Metadata for IRW tables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tags_quality.html">
 <span class="dropdown-text">Tag Quality</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./docs.html">
 <span class="dropdown-text">Data Documentation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="./itemtext.html">
 <span class="dropdown-text">Item Text Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./itemtext_desc.html">
 <span class="dropdown-text">Item Text Descriptives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./itemtext_issues.html">
 <span class="dropdown-text">Known Issues</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./itemtext_merge.html">
 <span class="dropdown-text">Merging with IRW data</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="./standard.html">
 <span class="dropdown-text">The Core IRW Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./comps_standard.html">
 <span class="dropdown-text">The Competition Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nominal_standard.html">
 <span class="dropdown-text">The Nominal Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./simsyn.html">
 <span class="dropdown-text">Simulated and Synthetic Data</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="./contribute.html">
 <span class="dropdown-text">Contributing Data to the IRW</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-get-started" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Get Started</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-get-started">    
        <li>
    <a class="dropdown-item" href="./getstarted.html">
 <span class="dropdown-text">Getting Started</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./training.html">
 <span class="dropdown-text">Training Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./problems.html">
 <span class="dropdown-text">Problem Set Examples</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./vignettes/index.html"> 
<span class="menu-text">Vignettes</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="./about.html">
 <span class="dropdown-text">About the IRW</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./research.html">
 <span class="dropdown-text">Research!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./othersites.html">
 <span class="dropdown-text">Related data resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./contact.html">
 <span class="dropdown-text">Contact Us</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/itemresponsewarehouse/misc/tree/main/data">
 <span class="dropdown-text">Data processing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://itemresponsewarehouse.github.io/Rpkg/">
 <span class="dropdown-text">irw: R package for managing IRW data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tag Quality</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The IRW annotates every table with eight qualitative tags — who was measured, what was measured, and how. This page says what those tags are worth: how much of each column is filled, how accurate it has been measured to be, who or what wrote it, how it compares against the human annotations, and what the evidence behind those numbers does not cover.</p>
<p>If you are about to filter on a tag, the section you need is <a href="#coverage-per-column">Coverage, per column</a> and then <a href="#what-the-accuracy-numbers-do-not-cover">What the accuracy numbers do not cover</a>.</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The row figure is not a coverage number
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>4,125 of the 4,134 tables (99.8%) carry a tag row.</strong> A row is not an answer. Some columns in it are usually filled and some are usually empty, so the row figure tells you almost nothing about the column you intend to filter on. Read that column’s own number below.</p>
</div>
</div>
<section id="coverage-per-column" class="level2">
<h2 class="anchored" data-anchor-id="coverage-per-column">Coverage, per column</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Produced by</th>
<th style="text-align: right;">Filled</th>
<th style="text-align: right;">Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>age range</code></td>
<td style="text-align: left;">Derived</td>
<td style="text-align: right;">3,029</td>
<td style="text-align: right;">73.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>child age</code></td>
<td style="text-align: left;">Derived</td>
<td style="text-align: right;">708</td>
<td style="text-align: right;">78.4% *</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>sample</code></td>
<td style="text-align: left;">Definitional</td>
<td style="text-align: right;">3,716</td>
<td style="text-align: right;">89.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>construct type</code></td>
<td style="text-align: left;">Definitional</td>
<td style="text-align: right;">2,254</td>
<td style="text-align: right;">54.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>measurement tool</code></td>
<td style="text-align: left;">Tagger</td>
<td style="text-align: right;">4,089</td>
<td style="text-align: right;">98.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>item format</code></td>
<td style="text-align: left;">Tagger</td>
<td style="text-align: right;">3,980</td>
<td style="text-align: right;">96.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>primary language(s)</code></td>
<td style="text-align: left;">Tagger</td>
<td style="text-align: right;">3,890</td>
<td style="text-align: right;">94.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>construct name</code></td>
<td style="text-align: left;">Description</td>
<td style="text-align: right;">2,265</td>
<td style="text-align: right;">54.8%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Computed at page build from <strong>tags v21.0</strong>, the released version you can download today, against the 4,134 tables in the IRW. Values a rater typed to mean “I could not find this” — <code>need help</code>, <code>missing description</code> — are counted as empty rather than as tags.</p>
<p><code>*</code> <strong><code>child age</code> is shown against a different denominator</strong>, and has to be: it is only ever filled when the sample includes children. Its 708 values are counted against the 903 tables whose <code>age range</code> is <code>Child (&lt;18y)</code> or <code>Mixed</code>. Against all 4,134 tables it reads 17.1%, which would make it look like the worst-covered column in the project. Blank is the correct value everywhere else.</p>
<p>Two columns sit far below the rest, and they are not backlog — see <a href="#what-is-published-and-what-is-withheld">what is published and what is withheld</a>. <code>construct name</code> is also not a coverage target in the way the others are: it is free text naming an instrument, with most values used exactly once, so there is no right answer being missed.</p>
</section>
<section id="four-kinds-of-column" class="level2">
<h2 class="anchored" data-anchor-id="four-kinds-of-column">Four kinds of column</h2>
<p>A coverage figure only means something once you know what produced the value. Each column belongs to exactly one of these classes, and each is held to its own standard.</p>
<p><strong>Derived</strong> — <code>age range</code>, <code>child age</code>. Computed from the table’s own <code>cov_age</code> column rather than judged by anyone. <code>cov_age</code> is usable only when it parses as numeric, has at least 30 non-missing values, lies within [0, 120] and is not a banded code; a 2% floor stops three 17-year-olds in a 46,000-person adult survey from making a table <code>Mixed</code>. This is the one place where a computed value <strong>outranks a human tag</strong>.</p>
<p><strong>Tagger</strong> — <code>primary language(s)</code>, <code>item format</code>, <code>measurement tool</code>. Answered from the study’s source document against a fixed vocabulary, by a human working the annotation sheet or by an automated tagger reading the same rules.</p>
<p><strong>Definitional</strong> — <code>sample</code>, <code>construct type</code>. The vocabulary is enforced, but the boundaries between its values had to be written down before anyone, human or machine, could apply them consistently. Writing <code>sample</code>’s rules and then amending them moved its frame facet from 26.9% to 45.5% to 54.5% exact match <strong>with no change to the tagger at all</strong>.</p>
<p><strong>Description</strong> — <code>construct name</code>. Free text: “Ages and Stages Questionnaire (ASQ-3)”, “International Math Olympiad problems”. No enumeration, so no precision to measure.</p>
</section>
<section id="who-wrote-these-tags" class="level2">
<h2 class="anchored" data-anchor-id="who-wrote-these-tags">Who wrote these tags</h2>
<p>Every tag was written either by a human annotator working a spreadsheet or by an automated tagger that reads the study’s source document. <strong>The published table does not distinguish them</strong>, so if provenance matters for your use, that distinction lives in <code>tags/tags_auto.csv</code> in the <a href="https://github.com/ben-domingue/irw">processing repository</a>, where every machine-written row is stamped <code>Rater = claude-auto</code>. As of 2026-09-04 that file holds 1,847 tagged tables, carrying:</p>
<table class="caption-top table">
<caption>A snapshot of the staging file, not of any published version. Staged values reach a release only once that release is published, and a human row overrides one wherever the two disagree.</caption>
<thead>
<tr class="header">
<th>Column</th>
<th style="text-align: right;">Values written by the tagger</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>measurement tool</code></td>
<td style="text-align: right;">1,837</td>
</tr>
<tr class="even">
<td><code>item format</code></td>
<td style="text-align: right;">1,725</td>
</tr>
<tr class="odd">
<td><code>primary language(s)</code></td>
<td style="text-align: right;">1,711</td>
</tr>
<tr class="even">
<td><code>sample</code> (setting facet only)</td>
<td style="text-align: right;">1,494</td>
</tr>
</tbody>
</table>
<p>Three rules govern the mix:</p>
<ul>
<li><strong>A human row wins.</strong> The annotation sheet is authoritative for anything a person touched, and machine output is unioned underneath it.</li>
<li><strong>A derived <code>age range</code> beats both.</strong> It is computed from the responses themselves, which is better evidence than either rater had.</li>
<li><strong>Nothing is permanent.</strong> No published version of the tags is authoritative over a later, better one. A tag that can be <em>shown</em> wrong — against the source, not merely against a different rater’s judgment — gets fixed. Every Redivis version is immutable and citable, so a correction produces a new version rather than editing the one you cited. Pin a version for stability; take the latest for correctness.</li>
</ul>
</section>
<section id="what-is-published-and-what-is-withheld" class="level2">
<h2 class="anchored" data-anchor-id="what-is-published-and-what-is-withheld">What is published and what is withheld</h2>
<p>The automated tagger fills every field it can support. A staging step then decides what is allowed out, and blanks the rest before anything is written. <strong>Publishing is a decision made at assembly, not by the tagger</strong>, and the bar is 90% per-atom precision against the human-annotated set.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Machine-written column</th>
<th></th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>primary language(s)</code></td>
<td>published</td>
<td>100% per-atom precision against gold (n=33)</td>
</tr>
<tr class="even">
<td><code>item format</code></td>
<td>published</td>
<td>90.9% accurate when it commits</td>
</tr>
<tr class="odd">
<td><code>measurement tool</code></td>
<td>published</td>
<td>86.8–93.3% accurate across runs</td>
</tr>
<tr class="even">
<td><code>sample</code> — setting facet</td>
<td>published</td>
<td>93.3% per-atom precision</td>
</tr>
<tr class="odd">
<td><code>sample</code> — frame facet</td>
<td><strong>withheld</strong></td>
<td>59.1% precision; below the bar</td>
</tr>
<tr class="even">
<td><code>construct type</code></td>
<td><strong>withheld</strong></td>
<td>50.0–66.7% per-atom precision</td>
</tr>
<tr class="odd">
<td><code>age range</code>, <code>child age</code></td>
<td><strong>withheld</strong></td>
<td>the <code>cov_age</code> derivation owns these</td>
</tr>
<tr class="even">
<td><code>construct name</code></td>
<td><strong>withheld</strong></td>
<td>free text; never scored</td>
</tr>
</tbody>
</table>
<p>This is why <code>construct type</code> sits near 55% while <code>measurement tool</code> sits near 99%. The tagger has an answer for <code>construct type</code> on most tables. It is not good enough to publish, so it is held back rather than shipped with a caveat.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>One column carries two facets, and only one of them publishes
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>sample</code> answers two questions at once: <em>where</em> the study happened — the <strong>setting</strong>: <code>Educational</code>, <code>Clinical</code>, <code>Workplace</code>, <code>Internet-based</code>, <code>Program-based</code>, <code>Non-human</code> — and <em>how broad</em> the sampling was — the <strong>frame</strong>: <code>Representative</code>, <code>Targeted/specific</code>, <code>General/non-specific</code>.</p>
<p>Only the setting facet publishes from the tagger. A machine-written <code>Workplace, Targeted/specific</code> is staged as <code>Workplace</code> alone. So <strong>a missing frame value on a machine-tagged table means withheld, not unknown</strong>. Human-tagged rows carry both facets.</p>
</div>
</div>
</section>
<section id="measured-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="measured-accuracy">Measured accuracy</h2>
<p>Scored blind against the human-annotated set: predictions were made without access to the annotation sheet, by a tagger running the same vocabulary the rules describe. Blanks count as abstentions rather than errors, because the vocabulary asks the tagger to leave a field empty rather than guess — so <em>exact</em> means right when it commits.</p>
<table class="caption-top table">
<caption>Measured 2026-09-01, on one 60-table sample.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th style="text-align: right;">Exact</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">n</th>
<th>How it fails</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>primary language(s)</code></td>
<td style="text-align: right;">90.9%</td>
<td style="text-align: right;">100.0%</td>
<td style="text-align: right;">91.7%</td>
<td style="text-align: right;">33</td>
<td>never names a language that is not there; misses secondary ones</td>
</tr>
<tr class="even">
<td><code>item format</code></td>
<td style="text-align: right;">90.9%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">38</td>
<td>abstains on 42% of tables rather than guess</td>
</tr>
<tr class="odd">
<td><code>measurement tool</code></td>
<td style="text-align: right;">86.8%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">38</td>
<td>commits on every table</td>
</tr>
<tr class="even">
<td><code>sample</code> — setting</td>
<td style="text-align: right;">87.5%</td>
<td style="text-align: right;">93.3%</td>
<td style="text-align: right;">87.5%</td>
<td style="text-align: right;">16</td>
<td>improved at every revision of the rules</td>
</tr>
<tr class="odd">
<td><code>sample</code> — frame</td>
<td style="text-align: right;">54.5%</td>
<td style="text-align: right;">59.1%</td>
<td style="text-align: right;">56.5%</td>
<td style="text-align: right;">22</td>
<td>the weakest column; over-commits to <code>Representative</code></td>
</tr>
<tr class="even">
<td><code>construct type</code></td>
<td style="text-align: right;">64.9%</td>
<td style="text-align: right;">80.0%</td>
<td style="text-align: right;">69.6%</td>
<td style="text-align: right;">37</td>
<td>under-tags: right when it names a facet, misses 30% of the facets gold holds</td>
</tr>
<tr class="odd">
<td><code>age range</code></td>
<td style="text-align: right;">91.7%</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">12</td>
<td>scored against the <code>cov_age</code> derivation, not against the sheet</td>
</tr>
<tr class="even">
<td><code>child age</code></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">6</td>
<td>too few labelled rows to score</td>
</tr>
</tbody>
</table>
<p>Precision and recall are per atom, because these columns are multi-select: naming two facets of three should not score the same as naming something unrelated. They are reported alongside exact match, never instead of it — a bar set on partial credit alone would pass a tagger that reliably names one facet of three.</p>
<div class="callout callout-style-simple callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Do not use whole-cell match on <code>sample</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Compared cell-for-cell, <code>sample</code> scores 14.7%, and that figure measures the annotation sheet’s blanks rather than the tagger. The tagger answers the frame facet on 34 of 34 tables while the sheet answers it on 22 of 34, so whole-cell matching penalises the tagger for filling a facet the key leaves empty — 15 of its 33 misses are supersets rather than wrong answers. Score this column one facet at a time, on the tables where the sheet answered that facet.</p>
</div>
</div>
</section>
<section id="when-the-two-disagree-which-one-is-wrong" class="level2">
<h2 class="anchored" data-anchor-id="when-the-two-disagree-which-one-is-wrong">When the two disagree, which one is wrong?</h2>
<p>Everything above scores the tagger against the human-annotated set as though that set were correct. It is worth being explicit that <strong>it is not a gold standard</strong>, because the direct comparisons run so far have found errors on both sides — and the human ones are the more systematic.</p>
<section id="age-range-the-data-usually-sided-with-the-machine" class="level3">
<h3 class="anchored" data-anchor-id="age-range-the-data-usually-sided-with-the-machine"><code>age range</code>: the data usually sided with the machine</h3>
<p>A seeded sample of 70 human-tagged tables carrying a <code>cov_age</code> column was checked against the ages recorded in each table’s own data. Of the 64 that could be checked, <strong>33 disagreed with the table’s own respondents.</strong></p>
<p>The disagreement is concentrated almost entirely in one label. Of 29 sampled <code>Mixed</code> tags, <strong>25 are contradicted by the data, and every one of those 25 has zero respondents under 18</strong>. <code>Adult (18+)</code> held up far better: 6 of 30.</p>
<p>This is why the column moved to derivation, and why a derived <code>age range</code> is the one value allowed to outrank a human tag. It also revises a number that looked like a tagger failure: the tagger first scored 73.0% on this column, and 86.5% against the corrected labels — the same predictions, re-marked. <strong>The tagger had been right more often than the key said.</strong></p>
</section>
<section id="construct-type-humans-tag-the-study-the-tagger-tags-the-table" class="level3">
<h3 class="anchored" data-anchor-id="construct-type-humans-tag-the-study-the-tagger-tags-the-table"><code>construct type</code>: humans tag the study, the tagger tags the table</h3>
<p>36 of the 96 study families with six or more tagged tables give every one of their tables an identical <code>construct type</code> — 738 tables in total. For some families that is correct: an exam programme really is <code>Cognitive/educational</code> all the way down.</p>
<p>For others it is a blanket. All 72 <code>c19prc_*</code> tables carry <code>Affective/mental health, Opinion/attitude</code>, including <code>c19prc_uk_mcbride_2021_wordsum</code> — a vocabulary test, which is <code>Cognitive/educational</code> by any reading and is tagged as neither. The pair describes the <em>study</em>, a COVID-era psychology survey, and was applied to all 72 of its tables regardless of what each one measures.</p>
<p>The rule now states that a tag describes <strong>what this table measures</strong>, never what the study was about. Those rows have not been rewritten, so a filter on <code>construct type</code> will still return them as they are.</p>
</section>
<section id="what-this-does-not-mean" class="level3">
<h3 class="anchored" data-anchor-id="what-this-does-not-mean">What this does not mean</h3>
<p>It does not mean the machine tags are better. Where both answered on the published columns they mostly agree, and the tagger’s characteristic failure — naming too few facets rather than inventing one — is visible in the accuracy table above. A human row still wins on conflict everywhere except derived <code>age range</code>, because a human can weigh things a source does not state outright.</p>
<p>And the comparison has a floor nobody has measured: <strong>no two human annotators have ever been scored against each other here.</strong> Some share of that 33-in-64 is legitimate judgment rather than error, and there is no measurement saying how much.</p>
</section>
</section>
<section id="what-happens-when-the-same-pipeline-runs-twice" class="level2">
<h2 class="anchored" data-anchor-id="what-happens-when-the-same-pipeline-runs-twice">What happens when the same pipeline runs twice</h2>
<p>Accuracy is not the only question worth asking. On 2026-09-04, 60 already-tagged tables were re-tagged blind, end to end, with cleared caches — the same pipeline, a second time. Separately, 369 tables that carried a language and nothing else were re-tagged by agents who were not shown the existing value, making that column an independent second opinion at six times the size.</p>
<table class="caption-top table">
<caption>Run-to-run agreement, 2026-09-04.</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th style="text-align: right;">Both runs answered</th>
<th style="text-align: right;">Identical</th>
<th>Second opinion at scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>item format</code></td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">100.0%</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>measurement tool</code></td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">100.0%</td>
<td>—</td>
</tr>
<tr class="odd">
<td><code>primary language(s)</code></td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">93.9%</td>
<td>91.1% identical on 359 further tables</td>
</tr>
<tr class="even">
<td><code>sample</code></td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">82.9%</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Stability is not correctness.</strong> None of those re-tagged tables has a human label to be right or wrong against. Two runs agreeing means the pipeline is reproducible, not that it is right.</p>
<p><strong>A disagreement is sometimes a defect, and finding it is the point.</strong> Of the 32 language disagreements in the 369-table comparison, ten were the same language spelled two ways under ISO 639-2 — <code>fra</code> against <code>fre</code>, <code>cze</code> against <code>ces</code> — since collapsed on export. The other 22 are substantive and have not been adjudicated. One earlier disagreement was a plain error: a Brazilian validation study recorded as Persian, found only because the same table was tagged twice.</p>
<p><strong>The two runs commit at different rates and nobody knows why.</strong> Where one run answered and the other left a blank, the second run was the one committing 11 times on <code>sample</code>, 8 on <code>item format</code> and 7 on <code>measurement tool</code>, against 0, 1 and 1 in the other direction. The asymmetry is real in this sample of 60; its cause is not established.</p>
</section>
<section id="one-column-may-be-inferred-another-may-never-be" class="level2">
<h2 class="anchored" data-anchor-id="one-column-may-be-inferred-another-may-never-be">One column may be inferred, another may never be</h2>
<p>The tagging rules are not just lists of permitted values, and two of them point in deliberately opposite directions.</p>
<p><strong><code>age range</code> may not be inferred.</strong> With no usable <code>cov_age</code>, it is tagged only from explicit age information in the source: a stated numeric inclusion criterion, a reported minimum or maximum, a school grade that cannot include 18-year-olds. Never from a country, a survey programme’s name, the word “undergraduates” (which routinely includes 17-year-olds), or the construct. A wrong value here silently mis-filters a sample, and a blank is cheaper to fix than a wrong tag.</p>
<p><strong><code>primary language(s)</code> may be inferred, and should be.</strong> Where a source does not state the language of administration, it is inferred from the country, the population, a forward-backward translation, or the language of the instrument’s cited version. The corpus is majority non-English, and every missing value makes it read as more English than it is — so erring toward naming a non-English language is the intended failure direction.</p>
<p>Two inferences stay off-limits even there, because neither is about the respondents: a repository record’s own language field describes the <em>record</em> (Zenodo stamps “English” on deposits from Finnish universities), and the language a paper is written in is not the language its questionnaire went out in. What is recorded is what the respondents read.</p>
</section>
<section id="what-the-accuracy-numbers-do-not-cover" class="level2">
<h2 class="anchored" data-anchor-id="what-the-accuracy-numbers-do-not-cover">What the accuracy numbers do not cover</h2>
<p>This section is the point of the page, not a disclaimer at the end of it.</p>
<ol type="1">
<li><p><strong>The evidence is one 60-table sample, scored three times.</strong> Per-column n runs from 6 to 38. These are directional, not tight estimates. One model only; a stronger one would likely differ, and the gap is unmeasured.</p></li>
<li><p><strong>The labelled set the tagger is scored against carries its own errors</strong>, measured for <code>age range</code> and unmeasured elsewhere — see <a href="#when-the-two-disagree-which-one-is-wrong">when the two disagree</a>. Accuracy against a standard is only as good as the standard.</p></li>
<li><p><strong>No ceiling is known.</strong> The human-annotated set is itself human work of unmeasured consistency. Nobody has measured how often two annotators disagree, so every figure above is scored against a standard whose own quality is unknown.</p></li>
<li><p><strong>Whole-cell <code>sample</code> match is a dead statistic</strong> — see the warning above.</p></li>
<li><p><strong>Coverage is not reach.</strong> Between 8% and 37% of sampled tables produced nothing at all across runs: failed fetches, paywalls, deposit records with no usable description. Difficulty tracks the <em>shape of the source</em> rather than the warehouse a table sits in — a national assessment programme published through a data portal is harder than a single-instrument psychometrics paper.</p></li>
<li><p><strong>Some subjectivity is irreducible.</strong> The re-run found roughly five tables in twelve where a second rater could reasonably land somewhere else. Those are not errors, and rewriting them would be churn rather than repair.</p></li>
</ol>
</section>
<section id="where-these-numbers-come-from" class="level2">
<h2 class="anchored" data-anchor-id="where-these-numbers-come-from">Where these numbers come from</h2>
<p>Coverage on this page is computed at build time from the published tag table, so it describes the version you can download today. The accuracy and reliability figures are dated snapshots of specific scoring runs and are reproducible from the scripts in <a href="https://github.com/ben-domingue/irw/tree/main/tags/scoring"><code>tags/scoring/</code></a> in the processing repository, alongside the predictions they scored. The rules themselves live in that repository’s tagging vocabulary, and the reasoning behind each one — the case as it was put, and what was decided — in <code>tags/decisions/</code>.</p>
<p>Corrections are welcome; open an issue on <a href="https://github.com/ben-domingue/irw/issues">ben-domingue/irw</a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/itemresponsewarehouse\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>