---
title: "Training Resources"
---

## IMPS 2025

### How to install R

Resources on installing R and Rstudio are available:

* <https://rstudio-education.github.io/hopr/starting.html>
* <https://www.r-project.org/>

### The data

This year’s competition centers on predicting cognitive performance using data from the Hearts and Flowers (H&F) task, a widely used measure of executive functioning. These data were collected from a large urban district in the US. In particular, these data were collected in school environments. Students completed the Hearts and Flowers measures on digital devices during the school day.

The data are available here [to be posted June 9 2025].

#### Variables
In the competition, you need to predict whether the response is accurate. 
* `resp`: Response accuracy (1 = correct, 0 = incorrect).

The following information is available for prediction.
* `id`: Unique identifier for each respondent.
* `cov_grade`: Respondent’s current school grade level.
* `cov_female`: Respondent’s gender (0 = male, 1 = female).
* `cov_age`: Respondent’s age in years (numeric, continuous).
* `trial_num`: The trial number within the respondent’s task session (starts at 1).
* `resp_side`: Side on which the response was made (either "left" or "right"); can be ignored for scoring (see acc).
* `rt`: Response time in milliseconds.
* `block`: Block label indicating task phase (e.g., "practice", or test condition).
* `time_limit`: Maximum response time allowed in that trial (may be NA in some blocks, such as practice).
* `stim_side`: Side on which the stimulus was shown ("left" or "right").
* `time`: Season during which data were collected (e.g., "Fall").
* `stim_shape`: Shape of the stimulus shown on screen (e.g., "heart", "plus").
* `cohort`: Condition or experimental grouping label (e.g., "plus").

### Problem: Predicting Performance in Executive Function Assessment

Your task is to develop predictive models leveraging response accuracy, response time, and demographic information to predict accuracy on a holdout sample that will not be included in the initially shared dataset. The H&F task is a cognitive task that measures inhibitory control and cognitive flexibility, two components of executive functions. Participants respond to visual stimuli following simple (congruent) or conflicting (incongruent) rules. Key features of the dataset include:

* Response accuracy and response time across different task conditions (congruent, incongruent, mixed).

* Demographic variables, such as age and data collection country, which provide opportunities for studying cross-group differences in cognitive performance.

* Structured in an Item Response Warehouse (IRW)-consistent format, ensuring accessibility for analysis.

### Suggested Readings

* Camerota, M., Willoughby, M. T., Magnus, B. E., & Blair, C. B. (2020). Leveraging item accuracy and reaction time to improve measurement of child executive function ability. Psychological Assessment, 32(12), 1118–1132. <https://doi.org/10.1037/pas0000953>

* Domingue, B.W., Braginsky, M., Caffrey-Maffei, L., Gilbert, J.B., Kanopka, K., Kapoor, R., Liu, Y., Nadela, S., Pan, G., Zhang, L., Zhang, S., & Frank, M. (2025). Solving the problem of data in psychometrics: An introduction to the Item Response Warehouse (IRW). PsyArXiv. <https://doi.org/10.31234/osf.io/7bd54>

* Obradović, J., Sulik, M. J., Finch, J. E., & Tirado-Strayer, N. (2018). Assessing students' executive functions in the classroom: Validating a scalable group-based procedure. Journal of Applied Developmental Psychology, 55, 4-13. <https://psycnet.apa.org/record/2018-17703-003>

* Stanford Project on Adaptation and Resilience in Kids. (n.d.). Assessment of Motivation, Effort, and Self-Regulation (AMES). Stanford University. Retrievable from <https://sparklab.stanford.edu/ames>

* Wu, T., Weiland, C., McCormick, M., Hsueh, J., Snow, C., & Sachs, J. (2024). One Score to Rule Them All? Comparing the Predictive and Concurrent Validity of 30 Hearts and Flowers Scoring Approaches. Assessment, 31(8), 1702-1720. <https://journals.sagepub.com/doi/10.1177/10731911241229566>


## V International Meeting of Psychometrics and Neuropsychological Evaluation

Slides for [this meeting](https://psychometricsmeetig.netlify.app/) can be found [here](https://docs.google.com/presentation/d/15UYpmrzKyi0g5v6IDyn7tYe45AzrVu0bnMLmIpLnI6U/edit?slide=id.g34a2d561067_0_0#slide=id.g34a2d561067_0_0).

## IOMW 2025

Information here pertains to the April 2025 demonstration of the IRW at the [IOMW conference](https://www.iomw.net/) held in Boulder, CO. Slides for this training can be found [here](https://docs.google.com/presentation/d/1ZOcMpaRwBfBF9xBdgdO6KBHm7xiGlq6n9WczI2oCrX8/edit?slide=id.g3334d2a9abd_0_4#slide=id.g3334d2a9abd_0_4). Prior to attending the conference, please go through the following checklist:

* **Install R and the necessary packages.** We will be working with R. Make sure you have [R installed](https://www.r-project.org/). We will also use some specific packages that you will need to install. Please follow the instructions [here](https://github.com/ben-domingue/irw/blob/main/training/iomw2025/00_packages.R).

* **Download the necessary data.** Please download the zip file [here](https://www.dropbox.com/scl/fi/mplmps10t7z7p8ljyo6km/tables.zip?rlkey=mde08yuex0jjvr80wchercb6b&e=1&dl=0) and store is so that you can access it readily during the training. This file will make it possible to follow along without depending on Redivis authentication. 

* **Prepare to interact with IRW data.** I will discuss several methods of interacting with IRW data. These methods require a few minutes of preparation. You only need to choose one of them and *I recommend you try the second*.

  + You can use a Redivis notebook. To get started, go [here](https://redivis.com/workflows/sdv7-7r839my4g/notebooks/vma9-89a2etg40). If you have not previously used Redivis you will need to create an account. After doing so, you can attempt to run the code (and should be good to go if you can run the lines showing the first few rows of the dataset). To run the code, you will first need to `fork` the notebook (choose `clone this workflow`) and then you should be able to 'start notebook' and execute the code blocks.

  + You can use `irw` (the preferred option). To do so, you will need to follow the instructions shown [here](https://github.com/itemresponsewarehouse/Rpkg). If you plan to work with the data this way, you can test that you are set up to do so by trying to successfully execute the following in your local R environment:
    ```
    df<-irw::irw_fetch("DART_Brysbaert_2020_1")
    head(df)
    ```

We recommend working with `irw` given that you can work in your local environment and utilize the filtering techniques we are developing. Please let me know (email ben.domingue at gmail.com) if you have any problems/questions!
