# dimensionality_merge_compute.R
#
# Companion to dimensionality_compute.R. That script asks how often a single
# IRW table looks unidimensional; this one asks what happens at the other end
# of the scale -- when several distinct instruments given to the same
# respondents are stacked into one wide matrix.
#
# IRW tables are typically one instrument each, which caps how multidimensional
# any single table can be. Tables sharing a DOI are usually several instruments
# from one study administered to one cohort, so merging them recovers the full
# battery a respondent actually saw. That is where genuinely high-dimensional
# structure lives in the warehouse.
#
# The number of member tables (k) is an INDEX of how many instruments were
# stacked, not a ground-truth factor count: some groups split one inventory
# into per-subscale tables, others repeat a construct pre/post. The question
# here is how multidimensional merged batteries get and whether the two
# diagnostics track that, not whether either recovers a known k.
#
# Groups are frozen in MERGE_GROUPS below rather than discovered at run time.
# See dimensionality_merge_scout.R for how they were found, and why the frozen
# list is preferred over calling irw_merge() directly.
#
# Output: dimensionality_data/dimensionality_merge_results.rds
#
# Usage:
#   Rscript vignettes/dimensionality_merge_compute.R   # from project root

library(irw)
library(psych)
library(dplyr)
library(purrr)
library(furrr)
library(tibble)

set.seed(20260817)

out_dir  <- "vignettes/dimensionality_data"
fits_dir <- file.path(out_dir, "merge_fits")
dir.create(fits_dir, recursive = TRUE, showWarnings = FALSE)

MIN_ITEMS <- 5
MAX_N     <- 10000  # downsample respondents before correlations, as in dimensionality_compute.R

# ==============================================================================
# 1. Frozen merge groups
#    Generated by dimensionality_merge_scout.R (stage 2 verdict "ok": identical
#    respondent sets across members, no item overlap). Frozen so the published
#    figures don't drift as IRW's bibliography grows.
# ==============================================================================

MERGE_GROUPS <- list(
  list(
    anchor = "act_kay_2025",
    tables = c("act_kay_2025", "bcti21_kay_2025", "spq_kay_2025", "den_kay_2025", "nfc_kay_2025", "cmq_kay_2025", "gcb5_2025", "cf_kay_2025", "agn_kay_2025", "pds_kay_2025", "gmc_kay_2025", "onecm_kay_2025")
  ),
  list(
    anchor = "alsyouf_2024_social_influence",
    tables = c("alsyouf_2024_social_influence", "alsyouf_2024_management_support", "alsyouf_2024_facilitating_conditions", "alsyouf_2024_conscientiousness", "alsyouf_2024_end_user_support", "alsyouf_2024_effort_expectancy", "alsyouf_2024_agreeableness", "alsyouf_2024_neuroticism", "alsyouf_2024_extraversion", "alsyouf_2024_openness", "alsyouf_2024_continuance_intention", "alsyouf_2024_performance_expectancy")
  ),
  list(
    anchor = "jeilani_2024_academic_stress",
    tables = c("jeilani_2024_academic_stress", "jeilani_2024_personal_growth", "jeilani_2024_psychological_wellbeing", "jeilani_2024_proactivity", "jeilani_2024_social_support_family", "jeilani_2024_self_efficacy", "jeilani_2024_social_anxiety", "jeilani_2024_social_outcomes", "jeilani_2024_social_support", "jeilani_2024_emotional", "jeilani_2024_purpose_in_life")
  ),
  list(
    anchor = "okeke2025_decision_confidence_pre",
    tables = c("okeke2025_decision_confidence_pre", "okeke2025_decision_accuracy", "okeke2025_adaptability", "okeke2025_cognitive_agility_post", "okeke2025_risk_mitigation", "okeke2025_ai_usefulness_pre", "okeke2025_ai_usefulness_post", "okeke2025_cognitive_agility_pre", "okeke2025_decision_confidence_post", "okeke2025_response_time")
  ),
  list(
    anchor = "pellerin2020_cpc_selfefficacy",
    tables = c("pellerin2020_cpc_selfefficacy", "pellerin2020_mwbs_gratbeing", "pellerin2020_gq6", "pellerin2020_mwbs_pd", "pellerin2020_serenity_acceptance", "pellerin2020_asti", "pellerin2020_cpc_hope", "pellerin2020_3dws", "pellerin2020_cpc_optimism")
  ),
  list(
    anchor = "singh_2025_identity_gi",
    tables = c("singh_2025_identity_gi", "singh_2025_identity_pba", "singh_2025_identity_irs", "singh_2025_identity_grit", "singh_2025_identity_pia", "singh_2025_identity_pss", "singh_2025_identity_pit", "singh_2025_identity_pds", "singh_2025_identity_cse")
  ),
  list(
    anchor = "suicide_reinbergs_2025_stosa",
    tables = c("suicide_reinbergs_2025_stosa", "suicide_reinbergs_2025_ghsq", "suicide_reinbergs_2025_gad", "suicide_reinbergs_2025_mpfi", "suicide_reinbergs_2025_soss", "suicide_reinbergs_2025_stig", "suicide_reinbergs_2025_sbqr", "suicide_reinbergs_2025_dssm", "suicide_reinbergs_2025_phq")
  ),
  list(
    anchor = "uruguay_2022_technology_devices",
    tables = c("uruguay_2022_technology_devices", "uruguay_2022_technology_govperception", "uruguay_2022_technology_transactions", "uruguay_2022_technology_entertainment", "uruguay_2022_technology_safety", "uruguay_2022_technology_barriers", "uruguay_2022_technology_ownership", "uruguay_2022_technology_information", "uruguay_2022_technology_streaming")
  ),
  list(
    anchor = "chile_2023_social-welfare-survey_a",
    tables = c("chile_2023_social-welfare-survey_a", "chile_2023_social-welfare-survey_u", "chile_2023_social-welfare-survey_ss", "chile_2023_social-welfare-survey_h", "chile_2023_social-welfare-survey_oo", "chile_2023_social-welfare-survey_yy", "chile_2023_social-welfare-survey_ee", "chile_2023_social-welfare-survey_vv")
  ),
  list(
    anchor = "colombia_2023_politics_media",
    tables = c("colombia_2023_politics_media", "colombia_2023_politics_protection", "colombia_2023_politics_prevention", "colombia_2023_politics_spaces", "colombia_2023_politics_risks", "colombia_2023_politics_procedures", "colombia_2023_politics_meaning", "colombia_2023_politics_organizations")
  ),
  list(
    anchor = "heise_2024_mental_falsebel",
    tables = c("heise_2024_mental_falsebel", "heise_2024_mental_vpt", "heise_2024_mental_truebel", "heise_2024_mental_falsesign", "heise_2024_mental_knowexpert", "heise_2024_mental_divdesires", "heise_2024_mental_divbeliefs", "heise_2024_mental_knowaccess")
  ),
  list(
    anchor = "qiang_2025_workplace_friendship",
    tables = c("qiang_2025_workplace_friendship", "qiang_2025_coping", "qiang_2025_red_tape", "qiang_2025_job_dissatisfaction", "qiang_2025_abusive_supervision", "qiang_2025_ne_scale", "qiang_2025_job_performance", "qiang_2025_surface_acting")
  ),
  list(
    anchor = "afaya_2020_medication_knowledge",
    tables = c("afaya_2020_medication_knowledge", "afaya_2020_general_knowledge", "afaya_2020_monitoring_knowledge", "afaya_2020_complications_knowledge", "afaya_2020_diet_knowledge", "afaya_2020_exercise_knowledge", "afaya_2020_footcare_knowledge")
  ),
  list(
    anchor = "chakraborty2026_IWAH_IRW",
    tables = c("chakraborty2026_IWAH_IRW", "chakraborty2026_SELOS_IRW", "chakraborty2026_BIDR_IRW", "chakraborty2026_BES_IRW", "chakraborty2026_BSPWBA_IRW", "chakraborty2026_PTM_IRW", "chakraborty2026_IRI_IRW")
  ),
  list(
    anchor = "feng2026_behavioral_intention",
    tables = c("feng2026_behavioral_intention", "feng2026_perceived_ease_of_use", "feng2026_competence", "feng2026_ec", "feng2026_intrinsic_motivation", "feng2026_autonomy", "feng2026_perceived_usefulness")
  ),
  list(
    anchor = "ghanbari_2016_helma_understand",
    tables = c("ghanbari_2016_helma_understand", "ghanbari_2016_helma_access", "ghanbari_2016_helma_use", "ghanbari_2016_helma_appraise", "ghanbari_2016_helma_comm", "ghanbari_2016_helma_reading", "ghanbari_2016_helma_numeracy")
  ),
  list(
    anchor = "jablonska_2020_upward_comparison",
    tables = c("jablonska_2020_upward_comparison", "jablonska_2020_downward_comparison", "jablonska_2020_rses", "jablonska_2020_hads", "jablonska_2020_profile_grooming", "jablonska_2020_swls", "jablonska_2020_instagram_addiction")
  ),
  list(
    anchor = "liu_2017_mcmq_coping",
    tables = c("liu_2017_mcmq_coping", "liu_2017_communication", "liu_2017_scale_d", "liu_2017_scale_o", "liu_2017_ssrs_support", "liu_2017_qol", "liu_2017_benefit_finding")
  ),
  list(
    anchor = "lorenz_2016_resilience",
    tables = c("lorenz_2016_resilience", "lorenz_2016_optimism2", "lorenz_2016_hope", "lorenz_2016_efficacy1", "lorenz_2016_optimism1", "lorenz_2016_psycap", "lorenz_2016_efficacy2")
  ),
  list(
    anchor = "nam_2024_function",
    tables = c("nam_2024_function", "nam_2024_selfeff", "nam_2024_selfcare", "nam_2024_access", "nam_2024_medint", "nam_2024_khlat", "nam_2024_attitude")
  ),
  list(
    anchor = "zeng_2026_gai_exploitation",
    tables = c("zeng_2026_gai_exploitation", "zeng_2026_gai_ttf", "zeng_2026_gai_inst_support", "zeng_2026_gai_role_adapt", "zeng_2026_gai_self_efficacy", "zeng_2026_gai_learning_effect", "zeng_2026_gai_exploration")
  ),
  list(
    anchor = "dwyer_2025_genomics_os",
    tables = c("dwyer_2025_genomics_os", "dwyer_2025_genomics_pb", "dwyer_2025_genomics_gec", "dwyer_2025_genomics_sjc", "dwyer_2025_genomics_ec", "dwyer_2025_genomics_pc")
  ),
  list(
    anchor = "lunacortes_2019_social_value",
    tables = c("lunacortes_2019_social_value", "lunacortes_2019_interperson_conn", "lunacortes_2019_satisfaction", "lunacortes_2019_isnbi", "lunacortes_2019_isncc", "lunacortes_2019_self_congruity")
  ),
  list(
    anchor = "shan_2020_pd",
    tables = c("shan_2020_pd", "shan_2020_ph", "shan_2020_hs", "shan_2020_f", "shan_2020_cs", "shan_2020_g")
  ),
  list(
    anchor = "shu_2025_translation_mcpis",
    tables = c("shu_2025_translation_mcpis", "shu_2025_translation_pcd", "shu_2025_translation_eib", "shu_2025_translation_add", "shu_2025_translation_pgv", "shu_2025_translation_srt")
  ),
  list(
    anchor = "wang2022_iat",
    tables = c("wang2022_iat", "wang2022_dass_stress", "wang2022_fomo", "wang2022_igas", "wang2022_dass_depression", "wang2022_dass_anxiety")
  ),
  list(
    anchor = "anunciacao_2025_emotional_responsibility",
    tables = c("anunciacao_2025_emotional_responsibility", "anunciacao_2025_emotional_self-awareness", "anunciacao_2025_emotional_social-awareness", "anunciacao_2025_emotional_management", "anunciacao_2025_emotional_relationships")
  ),
  list(
    anchor = "assessment_time_fournier_2025_bscs",
    tables = c("assessment_time_fournier_2025_bscs", "assessment_time_fournier_2025_phq", "assessment_time_fournier_2025_pmpuq", "assessment_time_fournier_2025_gad", "assessment_time_fournier_2025_upps")
  ),
  list(
    anchor = "avilatamayo_2022_skills_dev",
    tables = c("avilatamayo_2022_skills_dev", "avilatamayo_2022_work_life", "avilatamayo_2022_empl_stab", "avilatamayo_2022_work_envir", "avilatamayo_2022_workf_div")
  ),
  list(
    anchor = "BSCS_fadplus_goto2021",
    tables = c("BSCS_fadplus_goto2021", "LOC_fadplus_goto2021", "Rosenberg_fadplus_goto2021", "FAD_fadplus_goto2021", "GBJW_fadplus_goto2021")
  ),
  list(
    anchor = "che_2026_regulatory_self_efficacy",
    tables = c("che_2026_regulatory_self_efficacy", "che_2026_upward_social_comparison", "che_2026_social_support", "che_2026_upward_social_identity", "che_2026_social_wellbeing")
  ),
  list(
    anchor = "gao2025_spiritual_wellbeing",
    tables = c("gao2025_spiritual_wellbeing", "gao2025_family_support", "gao2025_sse", "gao2025_attachment_avoidance", "gao2025_attachment_anxiety")
  ),
  list(
    anchor = "hao_2025_self_efficacy",
    tables = c("hao_2025_self_efficacy", "hao_2025_foreign_language_anxiety", "hao_2025_emotional_regulation", "hao_2025_metacognitive_regulation", "hao_2025_social_regulation")
  ),
  list(
    anchor = "HEARD_Roch_2022_SWLPWI",
    tables = c("HEARD_Roch_2022_SWLPWI", "HEARD_Roch_2022_COPE", "HEARD_Roch_2022_IDSS", "HEARD_Roch_2022_K6", "HEARD_Roch_2022_WHODAS")
  ),
  list(
    anchor = "hoorani_2022_sp",
    tables = c("hoorani_2022_sp", "hoorani_2022_epreas", "hoorani_2022_child_help", "hoorani_2022_ps", "hoorani_2022_nps")
  ),
  list(
    anchor = "kern_2021_happiness",
    tables = c("kern_2021_happiness", "kern_2021_engagement", "kern_2021_learning", "kern_2021_life_satisfaction", "kern_2021_connectedness")
  ),
  list(
    anchor = "liu_2018_panas",
    tables = c("liu_2018_panas", "liu_2018_gse", "liu_2018_swls", "liu_2018_lot_r", "liu_2018_shyness")
  ),
  list(
    anchor = "merlo2025_eng_emotional",
    tables = c("merlo2025_eng_emotional", "merlo2025_eng_agentic", "merlo2025_eng_cognitive", "merlo2025_eng_comprehensive", "merlo2025_eet")
  ),
  list(
    anchor = "much_tte_2025_matrixreasoning",
    tables = c("much_tte_2025_matrixreasoning", "much_tte_2025_concentrationtask", "much_tte_2025_actionorientation", "much_tte_2025_effort", "much_tte_2025_currentmotivation")
  ),
  list(
    anchor = "ngo_2025_green_purchase_behavior",
    tables = c("ngo_2025_green_purchase_behavior", "ngo_2025_green_attitude", "ngo_2025_green_pbc", "ngo_2025_green_subjective_norm", "ngo_2025_green_purchase_intention")
  ),
  list(
    anchor = "ozkurt_2026_sport_motivation",
    tables = c("ozkurt_2026_sport_motivation", "ozkurt_2026_basic_psych_needs", "ozkurt_2026_ego_orientation", "ozkurt_2026_continuance_intention", "ozkurt_2026_paces_enjoyment")
  ),
  list(
    anchor = "rahm_2017_panas",
    tables = c("rahm_2017_panas", "rahm_2017_spane", "rahm_2017_swls", "rahm_2017_hswbs", "rahm_2017_shs")
  ),
  list(
    anchor = "test_taking_much_2025_ct",
    tables = c("test_taking_much_2025_ct", "test_taking_much_2025_ef", "test_taking_much_2025_mr", "test_taking_much_2025_ao", "test_taking_much_2025_cm")
  ),
  list(
    anchor = "thanh_2025_green_knowledge",
    tables = c("thanh_2025_green_knowledge", "thanh_2025_perceived_control", "thanh_2025_green_behavior", "thanh_2025_attitude", "thanh_2025_environ_concern")
  ),
  list(
    anchor = "tuason_2021_wellbeing",
    tables = c("tuason_2021_wellbeing", "tuason_2021_sense_of_agency", "tuason_2021_covid_coping_enjoy", "tuason_2021_loneliness_social", "tuason_2021_loneliness_emotional")
  ),
  list(
    anchor = "uruguay_2022_technology_access",
    tables = c("uruguay_2022_technology_access", "uruguay_2022_technology_places", "uruguay_2022_technology_work", "uruguay_2022_technology_communication", "uruguay_2022_technology_govservices")
  ),
  list(
    anchor = "wang_2026_perceived_usefulness",
    tables = c("wang_2026_perceived_usefulness", "wang_2026_attitude", "wang_2026_technology_anxiety", "wang_2026_behavioral_intention", "wang_2026_teaching_presence")
  ),
  list(
    anchor = "xu2024_noncompliance",
    tables = c("xu2024_noncompliance", "xu2024_turnover_intent", "xu2024_self_efficacy", "xu2024_emotional_exhaust", "xu2024_unethical_behav")
  ),
  list(
    anchor = "zhang_2025_self_efficacy",
    tables = c("zhang_2025_self_efficacy", "zhang_2025_normative_pressure", "zhang_2025_coercive_pressure", "zhang_2025_green_supply_intent", "zhang_2025_environ_awareness")
  ),
  list(
    anchor = "baka2023_uwes",
    tables = c("baka2023_uwes", "baka2023_olbi", "baka2023_bpnsf", "baka2023_jcs")
  ),
  list(
    anchor = "bps_boredom_bieleke2022",
    tables = c("bps_boredom_bieleke2022", "bae_boredom_bieleke2022", "ada_boredom_bieleke2022", "beh_boredom_bieleke2022")
  ),
  list(
    anchor = "chen2025_activity_motivation",
    tables = c("chen2025_activity_motivation", "chen2025_body_image", "chen2025_peer_support", "chen2025_self_esteem")
  ),
  list(
    anchor = "colombia_2023_politics_candidates",
    tables = c("colombia_2023_politics_candidates", "colombia_2023_politics_importance", "colombia_2023_politics_channels", "colombia_2023_politics_rights")
  ),
  list(
    anchor = "cormier_2024_phq4",
    tables = c("cormier_2024_phq4", "cormier_2024_pss4", "cormier_2024_personality", "cormier_2024_cognitive_decline")
  ),
  list(
    anchor = "crspolish_wiesyk_2024_p_stress",
    tables = c("crspolish_wiesyk_2024_p_stress", "crspolish_wiesyk_2024_lie", "crspolish_wiesyk_2024_crs", "crspolish_wiesyk_2024_enrich")
  ),
  list(
    anchor = "dopmeijer_2022_ubos",
    tables = c("dopmeijer_2022_ubos", "dopmeijer_2022_loneliness", "dopmeijer_2022_performance_pressure", "dopmeijer_2022_sense_belonging")
  ),
  list(
    anchor = "dpt_noncog__interpersonal_reactivity",
    tables = c("dpt_noncog__interpersonal_reactivity", "dpt_noncog__intolerance_of_uncertainty", "dpt_noncog__social_intelligence", "dpt_noncog__psychological_flexibility")
  ),
  list(
    anchor = "erf_breuer_2017_frmfr",
    tables = c("erf_breuer_2017_frmfr", "erf_breuer_2017_tai", "erf_breuer_2017_dosp", "erf_breuer_2017_frmmc")
  ),
  list(
    anchor = "FIVPEI_Perrig_2023_AttDiff",
    tables = c("FIVPEI_Perrig_2023_AttDiff", "FIVPEI_Perrig_2023_PENS", "FIVPEI_Perrig_2023_PXI", "FIVPEI_Perrig_2023_IMI")
  ),
  list(
    anchor = "galindo_2023_emotional_intelligence",
    tables = c("galindo_2023_emotional_intelligence", "galindo_2023_beliefs", "galindo_2023_social_support", "galindo_2023_loneliness")
  ),
  list(
    anchor = "huang_2023_b_scale",
    tables = c("huang_2023_b_scale", "huang_2023_c_scale", "huang_2023_d_scale", "huang_2023_e_scale")
  ),
  list(
    anchor = "iwasa_2016_stai_trait",
    tables = c("iwasa_2016_stai_trait", "iwasa_2016_asi", "iwasa_2016_dpssr", "iwasa_2016_padua_inventory")
  ),
  list(
    anchor = "jiang_2025_inclusive_efficacy",
    tables = c("jiang_2025_inclusive_efficacy", "jiang_2025_sacie", "jiang_2025_empathy", "jiang_2025_teaching_motivation")
  ),
  list(
    anchor = "jordan_2020_burnout",
    tables = c("jordan_2020_burnout", "jordan_2020_pss10", "jordan_2020_mindfulness", "jordan_2020_resilience")
  ),
  list(
    anchor = "karajko2025_ai_benefit",
    tables = c("karajko2025_ai_benefit", "karajko2025_ai_governance", "karajko2025_ai_risk", "karajko2025_ai_trust")
  ),
  list(
    anchor = "kim_2025_psqi",
    tables = c("kim_2025_psqi", "kim_2025_isi", "kim_2025_psas", "kim_2025_hads")
  ),
  list(
    anchor = "lec5_xiong_2025",
    tables = c("lec5_xiong_2025", "phq9_xiong_2025", "ders16_xiong_2025", "pcl5_xiong_2025")
  ),
  list(
    anchor = "li_2021_cultural_intelligence",
    tables = c("li_2021_cultural_intelligence", "li_2021_org_cultural_diversity", "li_2021_knowledge_sharing", "li_2021_sustainable_innov_behav")
  ),
  list(
    anchor = "liu_2025_foreign_lang_enjoyment",
    tables = c("liu_2025_foreign_lang_enjoyment", "liu_2025_classroom_interaction", "liu_2025_speaking_selfefficacy", "liu_2025_willingness_communicate")
  ),
  list(
    anchor = "pavic_2022_natural_immunity",
    tables = c("pavic_2022_natural_immunity", "pavic_2022_science_literacy", "pavic_2022_healthcare_trust", "pavic_2022_vaccine_conspiracy")
  ),
  list(
    anchor = "pechorro_impulsivity_2021_rpq",
    tables = c("pechorro_impulsivity_2021_rpq", "pechorro_impulsivity_2021_iid", "pechorro_impulsivity_2021_bes", "pechorro_impulsivity_2021_ypitris")
  ),
  list(
    anchor = "ptacek2023_compact",
    tables = c("ptacek2023_compact", "ptacek2023_swls", "ptacek2023_aaq2", "ptacek2023_dass21")
  ),
  list(
    anchor = "sun_2026_eap_content",
    tables = c("sun_2026_eap_content", "sun_2026_eap_difficulty", "sun_2026_eap_methods", "sun_2026_eap_usage")
  ),
  list(
    anchor = "wang_onlineriskexp_2025_negativeatt",
    tables = c("wang_onlineriskexp_2025_negativeatt", "wang_onlineriskexp_2025", "wang_onlineriskexp_2025_anxiety", "wang_onlineriskexp_2025_interpersonalsecurity")
  ),
  list(
    anchor = "wu_2024_video_addiction",
    tables = c("wu_2024_video_addiction", "wu_2024_resilience", "wu_2024_self_control", "wu_2024_proactive_personality")
  ),
  list(
    anchor = "yang_2023_emotional_eating_uppsp",
    tables = c("yang_2023_emotional_eating_uppsp", "yang_2023_emotional_eating_eesr", "yang_2023_emotional_eating_ders", "yang_2023_emotional_eating_cesd")
  ),
  list(
    anchor = "AOMT_BR_SF_EDPANAB_Geiger_2021_AOT",
    tables = c("AOMT_BR_SF_EDPANAB_Geiger_2021_AOT", "AOMT_BR_SF_EDPANAB_Geiger_2021_RF", "AOMT_BR_SF_EDPANAB_Geiger_2021_BRS")
  ),
  list(
    anchor = "APFCompact_Ptacek_2024_SWLS",
    tables = c("APFCompact_Ptacek_2024_SWLS", "APFCompact_Ptacek_2024_DASS-21", "APFCompact_Ptacek_2024_AAQ_II")
  ),
  list(
    anchor = "chen2022_cls",
    tables = c("chen2022_cls", "chen2022_ses", "chen2022_sasc")
  ),
  list(
    anchor = "chen2022b_socsupport",
    tables = c("chen2022b_socsupport", "chen2022b_psychabuse", "chen2022b_selfesteem")
  ),
  list(
    anchor = "chile_2023_social-welfare-survey_rr",
    tables = c("chile_2023_social-welfare-survey_rr", "chile_2023_social-welfare-survey_f", "chile_2023_social-welfare-survey_g")
  ),
  list(
    anchor = "curiosity_stone_2022_var",
    tables = c("curiosity_stone_2022_var", "curiosity_stone_2022_invol", "curiosity_stone_2022_fns")
  ),
  list(
    anchor = "daiku_2021_lying_frequency",
    tables = c("daiku_2021_lying_frequency", "daiku_2021_dirty_dozen", "daiku_2021_lie_scale")
  ),
  list(
    anchor = "dou2025_ans",
    tables = c("dou2025_ans", "dou2025_area", "dou2025_wcts")
  ),
  list(
    anchor = "fan_2025_mbi_accomplishment",
    tables = c("fan_2025_mbi_accomplishment", "fan_2025_mbi_exhaustion", "fan_2025_mbi_depersonalization")
  ),
  list(
    anchor = "gilbert_meta_103",
    tables = c("gilbert_meta_103", "gilbert_meta_102", "gilbert_meta_104")
  ),
  list(
    anchor = "gilbert_meta_57",
    tables = c("gilbert_meta_57", "gilbert_meta_58", "gilbert_meta_59")
  ),
  list(
    anchor = "gilbert_meta_67",
    tables = c("gilbert_meta_67", "gilbert_meta_65", "gilbert_meta_66")
  ),
  list(
    anchor = "hpwt_bayona_2025_jobsatisfaction",
    tables = c("hpwt_bayona_2025_jobsatisfaction", "hpwt_bayona_2025_workcharacteristics", "hpwt_bayona_2025_jobperformance")
  ),
  list(
    anchor = "kim_2023_gad7",
    tables = c("kim_2023_gad7", "kim_2023_pss10", "kim_2023_phq9")
  ),
  list(
    anchor = "lhsbrasil_couto_2023_ses",
    tables = c("lhsbrasil_couto_2023_ses", "lhsbrasil_couto_2023_lhs", "lhsbrasil_couto_2023_pss")
  ),
  list(
    anchor = "lu_2017_pss10",
    tables = c("lu_2017_pss10", "lu_2017_phq9", "lu_2017_gad7")
  ),
  list(
    anchor = "odachi_2022_fear_covid19",
    tables = c("odachi_2022_fear_covid19", "odachi_2022_hads", "odachi_2022_bfs")
  ),
  list(
    anchor = "PPPASBPNSSedaisw_Pedro_2022_EBSV",
    tables = c("PPPASBPNSSedaisw_Pedro_2022_EBSV", "PPPASBPNSSedaisw_Pedro_2022_PANAS", "PPPASBPNSSedaisw_Pedro_2022_NPBE")
  ),
  list(
    anchor = "psychotools_gratitude_gac",
    tables = c("psychotools_gratitude_gac", "psychotools_gratitude_gq6", "psychotools_gratitude_gart")
  ),
  list(
    anchor = "roelen_2020_k6",
    tables = c("roelen_2020_k6", "roelen_2020_dietary_diversity", "roelen_2020_rses")
  ),
  list(
    anchor = "romadlon_2022_facit",
    tables = c("romadlon_2022_facit", "romadlon_2022_bdi", "romadlon_2022_mfi20")
  ),
  list(
    anchor = "rosetti2023_gad7",
    tables = c("rosetti2023_gad7", "rosetti2023_climate_knowledge", "rosetti2023_climate_anxiety")
  ),
  list(
    anchor = "RvKDCS_Romiacg_Miroshnik_2020_KDOCS",
    tables = c("RvKDCS_Romiacg_Miroshnik_2020_KDOCS", "RvKDCS_Romiacg_Miroshnik_2020_CBI", "RvKDCS_Romiacg_Miroshnik_2020_BFI")
  ),
  list(
    anchor = "song_2023_slwai",
    tables = c("song_2023_slwai", "song_2023_mpats", "song_2023_rses")
  ),
  list(
    anchor = "tran_2023_phq9",
    tables = c("tran_2023_phq9", "tran_2023_gi_symptoms", "tran_2023_gad7")
  ),
  list(
    anchor = "valverdeberrocoso_2021_sqd",
    tables = c("valverdeberrocoso_2021_sqd", "valverdeberrocoso_2021_tictip", "valverdeberrocoso_2021_learning_design")
  ),
  list(
    anchor = "wu2026_liking",
    tables = c("wu2026_liking", "wu2026_typical", "wu2026_novel")
  ),
  list(
    anchor = "ye_2025_q25_scale",
    tables = c("ye_2025_q25_scale", "ye_2025_q32_scale", "ye_2025_q15_scale")
  ),
  list(
    anchor = "yoshimura_2026_es_scale",
    tables = c("yoshimura_2026_es_scale", "yoshimura_2026_isu_scale", "yoshimura_2026_psych_safety")
  ),
  list(
    anchor = "yu_2025_mobile_addiction",
    tables = c("yu_2025_mobile_addiction", "yu_2025_bedtime_procrastination", "yu_2025_physical_activity")
  ),
  list(
    anchor = "zamzuri_2021_rpap_risk_perception",
    tables = c("zamzuri_2021_rpap_risk_perception", "zamzuri_2021_rpap_practice", "zamzuri_2021_rpap_attitude")
  )
)

# ==============================================================================
# 2. Build one merged response matrix
# ==============================================================================

# Item names are prefixed with their source table. The scout requires disjoint
# items, but the prefix keeps that from being load-bearing and gives the
# block-ordered heatmap its provenance.
build_merged <- function(tables) {
  parts <- map(tables, function(tbl) {
    df <- tryCatch(irw_fetch(tbl), error = function(e) {
      message("    fetch failed for ", tbl, ": ", conditionMessage(e))
      NULL
    })
    if (is.null(df)) return(NULL)
    df$item         <- paste0(tbl, "::", df$item)
    df$source_table <- tbl
    df[, c("id", "item", "resp", "source_table")]
  })
  parts <- compact(parts)
  if (length(parts) < 2) return(NULL)

  # Restrict to respondents present in every member table, so the merged matrix
  # is a complete battery rather than a block-diagonal patchwork.
  shared <- reduce(map(parts, function(p) unique(na.omit(p$id))), intersect)
  if (length(shared) < 100) {
    message("    skipped: only ", length(shared), " shared respondents")
    return(NULL)
  }
  if (length(shared) > MAX_N) shared <- sample(shared, MAX_N)

  long <- bind_rows(parts)
  long <- long[long$id %in% shared, ]

  resp <- irw_long2resp(long[, c("id", "item", "resp")])
  resp$id <- NULL
  resp <- resp[, sapply(resp, function(x) length(unique(na.omit(x))) > 1), drop = FALSE]

  # irw_long2resp() prefixes every column with "item_", so the source table has
  # to be recovered from the column names rather than joined against the long
  # data. Column names look like "item_<source table>::<item>".
  item_source <- tibble(
    item         = names(resp),
    source_table = sub("::.*$", "", sub("^item_", "", names(resp)))
  )

  list(
    resp        = resp,
    item_source = item_source,
    n_shared    = length(shared),
    n_tables    = length(parts),
    tables      = map_chr(parts, function(p) p$source_table[1])
  )
}

# ==============================================================================
# 3. Same diagnostics as the single-table pass
# ==============================================================================

fit_merged <- function(group) {
  message("  Processing merge group: ", group$anchor, " (k = ", length(group$tables), ")")

  m <- build_merged(group$tables)
  if (is.null(m) || ncol(m$resp) < MIN_ITEMS) return(NULL)
  resp <- m$resp

  n_categories <- length(unique(na.omit(unlist(resp))))

  if (n_categories == 2) {
    cor_method <- "tetrachoric"
    cormat <- tryCatch(suppressWarnings(suppressMessages(psych::tetrachoric(resp)$rho)),
                       error = function(e) { message("    tetrachoric failed: ", conditionMessage(e)); NULL })
  } else if (n_categories >= 3 && n_categories <= 10) {
    cor_method <- "polychoric"
    # Merged batteries routinely stack instruments with different scale lengths
    # (a 5-point scale beside a 6-point one), which leaves sparse cells in the
    # bivariate tables. psych's default continuity correction (0.5) can then
    # push polycor into an unusable matrix -- psych's own advice in that case
    # is correct = 0, so retry that way before giving up.
    poly <- function(correct) tryCatch(
      suppressWarnings(suppressMessages(
        psych::polychoric(resp, max.cat = 10, correct = correct, progress = FALSE)$rho
      )),
      error = function(e) { message("    polychoric (correct = ", correct, ") failed: ",
                                    conditionMessage(e)); NULL }
    )
    cormat <- poly(0.5)
    if (is.null(cormat) || anyNA(cormat)) {
      message("    retrying polychoric with correct = 0")
      retry <- poly(0)
      if (!is.null(retry) && !anyNA(retry)) {
        cormat     <- retry
        cor_method <- "polychoric (correct = 0)"
      }
    }
  } else {
    cor_method <- "pearson"
    message("    n_categories = ", n_categories, " outside 2-10; falling back to Pearson correlations")
    cormat <- tryCatch(cor(resp, use = "pairwise.complete.obs"),
                       error = function(e) { message("    Pearson failed: ", conditionMessage(e)); NULL })
  }
  if (is.null(cormat) || anyNA(cormat)) {
    message("    skipped: correlation matrix unusable")
    return(NULL)
  }

  ev <- tryCatch(eigen(cormat, symmetric = TRUE, only.values = TRUE)$values, error = function(e) NULL)
  if (is.null(ev) || length(ev) < 2) {
    message("    skipped: eigen decomposition failed")
    return(NULL)
  }

  pa <- tryCatch(psych::fa.parallel(cormat, n.obs = nrow(resp), fa = "fa", plot = FALSE),
                 error = function(e) { message("    fa.parallel failed: ", conditionMessage(e)); NULL })

  list(
    summary = tibble(
      anchor          = group$anchor,
      n_tables        = m$n_tables,
      n_items         = ncol(resp),
      n_participants  = nrow(resp),
      n_categories    = n_categories,
      cor_method      = cor_method,
      ratio_12        = ev[1] / ev[2],
      prop_var_1      = ev[1] / sum(ev),
      nfact_suggested = if (!is.null(pa)) pa$nfact else NA_integer_,
      tables          = paste(m$tables, collapse = "|")
    ),
    eigenvalues = ev,
    # Kept for the block-ordered heatmap: full matrix only where it is small
    # enough to be worth carrying in the cache.
    cormat      = if (ncol(cormat) <= 150) cormat else NULL,
    item_source = m$item_source
  )
}

# ==============================================================================
# 4. Run, writing each group to disk as it completes
# ==============================================================================

fit_to_disk <- function(group) {
  out_file <- file.path(fits_dir, paste0(group$anchor, ".rds"))
  if (file.exists(out_file)) {
    message("  Skipping (already done): ", group$anchor)
    return(invisible(NULL))
  }
  result <- tryCatch(fit_merged(group), error = function(e) {
    message("    unexpected error for ", group$anchor, ": ", conditionMessage(e))
    NULL
  })
  if (!is.null(result)) saveRDS(result, out_file)
}

plan(multisession, workers = min(4, parallel::detectCores() %/% 2))
message("\nAnalyzing ", length(MERGE_GROUPS), " merge groups...")
future_map(MERGE_GROUPS, fit_to_disk, .options = furrr_options(seed = TRUE))
plan(sequential)

# ==============================================================================
# 5. Combine and save
# ==============================================================================

all_raw <- map(MERGE_GROUPS, function(g) {
  f <- file.path(fits_dir, paste0(g$anchor, ".rds"))
  if (file.exists(f)) readRDS(f) else NULL
}) |> compact()

merge_summary <- map(all_raw, "summary") |> compact() |> bind_rows()
anchors       <- map_chr(all_raw, function(r) r$summary$anchor)

message("\nDone. ", nrow(merge_summary), " merged batteries with usable results out of ",
        length(MERGE_GROUPS), " groups.")

saveRDS(
  list(
    summary      = merge_summary,
    eigenvalues  = set_names(map(all_raw, "eigenvalues"), anchors),
    cormats      = set_names(map(all_raw, "cormat"), anchors),
    item_sources = set_names(map(all_raw, "item_source"), anchors),
    merge_groups = MERGE_GROUPS,
    date_run     = Sys.Date(),
    session      = sessionInfo()
  ),
  file = file.path(out_dir, "dimensionality_merge_results.rds")
)

message("Saved to ", out_dir, "/dimensionality_merge_results.rds")
