<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-22">
<meta name="description" content="Hedge, Powell &amp; Sumner (2018) showed that classic conflict tasks (Flanker, Stroop, stop-signal) produce large, dependable group effects but poor individual-differences reliability, because the within-subject difference score that measures the effect cancels out most of the between-person variance. We test whether the same attenuation appears in IRW cognitive-control data: the Hearts &amp; Flowers task, an alcohol Stroop, a stop-signal task, and three tasks (Stroop, Simon, ANT flanker) from the Enkavi et al.&nbsp;(2019) Self-Regulation Ontology battery.">

<title>The Reliability Paradox in Cognitive-Control Tasks – Item Response Warehouse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-66c1b573e2fb14f92c700fd912a2cbe7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-NM0Y0TP4RY"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-NM0Y0TP4RY', { 'anonymize_ip': true});
</script>
<link href="../site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.12.0/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.25.2/plotly-latest.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Item Response Warehouse</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data">    
        <li>
    <a class="dropdown-item" href="../overview.html">
 <span class="dropdown-text">Overview of IRW Data Standards</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data.html">
 <span class="dropdown-text">Browse the IRW Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../metadata.html">
 <span class="dropdown-text">Metadata for IRW tables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../docs.html">
 <span class="dropdown-text">Data Documentation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../itemtext.html">
 <span class="dropdown-text">Item Text Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../itemtext_desc.html">
 <span class="dropdown-text">Item Text Descriptives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../itemtext_issues.html">
 <span class="dropdown-text">Known Issues</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../itemtext_merge.html">
 <span class="dropdown-text">Merging with IRW data</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../standard.html">
 <span class="dropdown-text">The Core IRW Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../comps_standard.html">
 <span class="dropdown-text">The Competition Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../nominal_standard.html">
 <span class="dropdown-text">The Nominal Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../simsyn.html">
 <span class="dropdown-text">Simulated and Synthetic Data</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../contribute.html">
 <span class="dropdown-text">Contributing Data to the IRW</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-get-started" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Get Started</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-get-started">    
        <li>
    <a class="dropdown-item" href="../getstarted.html">
 <span class="dropdown-text">Getting Started</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../training.html">
 <span class="dropdown-text">Training Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../problems.html">
 <span class="dropdown-text">Problem Set Examples</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/index.html"> 
<span class="menu-text">Vignettes</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../about.html">
 <span class="dropdown-text">About the IRW</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../research.html">
 <span class="dropdown-text">Research!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../othersites.html">
 <span class="dropdown-text">Related data resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../contact.html">
 <span class="dropdown-text">Contact Us</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/itemresponsewarehouse/misc/tree/main/data">
 <span class="dropdown-text">Data processing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://itemresponsewarehouse.github.io/Rpkg/">
 <span class="dropdown-text">irw: R package for managing IRW data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link active" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#data-and-methods" id="toc-data-and-methods" class="nav-link" data-scroll-target="#data-and-methods">Data and methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Reliability Paradox in Cognitive-Control Tasks</h1>
</div>

<div>
  <div class="description">
    <p>Hedge, Powell &amp; Sumner (2018) showed that classic conflict tasks (Flanker, Stroop, stop-signal) produce large, dependable group effects but poor individual-differences reliability, because the within-subject difference score that measures the effect cancels out most of the between-person variance. We test whether the same attenuation appears in IRW cognitive-control data: the Hearts &amp; Flowers task, an alcohol Stroop, a stop-signal task, and three tasks (Stroop, Simon, ANT flanker) from the Enkavi et al.&nbsp;(2019) Self-Regulation Ontology battery.</p>
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This vignette — including the dataset search, the compute script, the analysis design, and the writing below — was produced largely by Claude (Anthropic), working from a task specification and with human review. Treat the methodological choices and interpretations accordingly, and check the compute script (<code>hf_reliability_compute.R</code>) directly if you’re relying on the numbers here.</p>
</div>
</div>
<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">Motivation</h2>
<p>Some cognitive tasks produce huge, dependable group-level effects yet turn out to be nearly useless for studying individual differences. The clearest examples are <strong>conflict tasks</strong>: paradigms where each trial pairs a target feature that must be responded to with a second, task-irrelevant feature that either matches (congruent) or clashes (incongruent) with the correct response. Flanker (arrows flanked by same- or opposite-pointing distractors), Stroop (color words printed in matching or mismatching ink), and Simon-type spatial-compatibility tasks are the classic examples. In all of them, incongruent trials require suppressing the irrelevant feature’s pull toward the wrong response, which costs time and accuracy relative to congruent trials — the <em>conflict effect</em> (or congruency effect), usually indexed as incongruent-minus-congruent RT or accuracy. Every study finds that people are slower and less accurate on incongruent trials than congruent ones — the effect is close to universal. But <span class="citation" data-cites="hedge2018reliability">Hedge et al. (<a href="#ref-hedge2018reliability" role="doc-biblioref">2018</a>)</span> showed that when you use these same tasks to <em>rank</em> people (rather than just detect the group effect), reliability collapses: individual conditions like congruent RT or incongruent RT are often reliable enough on their own (test-retest ICCs around .6-.8), but the <em>difference score</em> used to index the effect of interest — incongruent RT minus congruent RT — is barely reliable at all.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What “reliability collapses” means, precisely.</strong> Imagine testing the same people twice (or splitting one session’s trials into two halves) and correlating each person’s score across the two measurements. For congruent RT alone, or incongruent RT alone, that correlation is reasonably strong (ICC ~.6-.8) — a person who’s fast in one measurement tends to still be fast in the other. For the <em>difference score</em>, that same across-measurement correlation is much weaker — in some datasets below, close to zero. This doesn’t mean the conflict effect itself is fake or unstable at the group level; it means that <em>individual differences</em> in the size of the effect are mostly swamped by trial-level noise, so a person’s difference score in one measurement predicts almost nothing about their difference score in another. How close to zero depends on how strongly congruent and incongruent RT covary across people — see <a href="#where-does-the-variance-go">Where does the variance go?</a> for why.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-examples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hf_reliability_paradox_files/figure-html/fig-task-examples-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Schematic examples of the conflict manipulation in Stroop and Hearts &amp; Flowers. Stroop: name the ink colour, ignore the printed word; ink and word agree on congruent trials, disagree on incongruent trials. Hearts &amp; Flowers: press the button on the same side as the stimulus for hearts (congruent), the opposite side for flowers (incongruent). These are illustrative reconstructions, not verbatim task stimuli.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The mechanism is a direct consequence of how difference scores propagate variance. For two conditions <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> measured on the same people,</p>
<p><span id="eq-vardiff"><span class="math display">\[\mathrm{Var}(B - A) = \mathrm{Var}(A) + \mathrm{Var}(B) - 2\,\mathrm{Cov}(A, B) \tag{1}\]</span></span></p>
<p>Conflict tasks are robust precisely <em>because</em> almost everyone shows a similar conflict cost — high scorers on congruent trials tend to also be high scorers on incongruent trials (fast people are fast in both conditions, slow people are slow in both). That shared individual differences signal is exactly what <span class="math inline">\(\mathrm{Cov}(A, B)\)</span> captures, and subtracting it away leaves a difference score with little between-person variance left, while the trial-level measurement noise in each condition is <em>not</em> similarly reduced. The result: low signal-to-noise for the individual-differences measure, even though the group-level contrast (<span class="math inline">\(\bar{B} - \bar{A}\)</span>) is large and rock solid.</p>
<p>This is a <em>structural</em> property of difference-score designs, not a defect specific to Flanker or Stroop. Any task that measures an effect as a within-subject contrast between two positively-correlated conditions is vulnerable to it. The Hearts &amp; Flowers (H&amp;F) task <span class="citation" data-cites="imps2025_hf">(<a href="#ref-imps2025_hf" role="doc-biblioref">DeJoseph et al. 2025</a>)</span> — part of the imps2025 datathon data in IRW — has exactly this structure: children respond to a heart or flower stimulus, pressing the button on the <em>same</em> side as the stimulus for hearts (congruent, low conflict) and the <em>opposite</em> side for flowers (incongruent, high conflict). This is a spatial stimulus-response compatibility manipulation in the same family as Simon and Flanker effects, which makes it a natural candidate for replicating the reliability paradox in IRW data. We also check independent tasks with the same congruent/incongruent structure: an alcohol-related attentional-bias Stroop <span class="citation" data-cites="alcoholstroop_jones2024">(<a href="#ref-alcoholstroop_jones2024" role="doc-biblioref">Jones et al. 2024</a>)</span>, a stop-signal (go/no-go family) task <span class="citation" data-cites="matzke-etal-2019">(<a href="#ref-matzke-etal-2019" role="doc-biblioref">He et al. 2021</a>)</span>, and three tasks (a classic color-word Stroop, a Simon task, and the flanker component of the Attention Network Test) from <span class="citation" data-cites="enkavi2019">Enkavi et al. (<a href="#ref-enkavi2019" role="doc-biblioref">2019</a>)</span>’s large-scale Self-Regulation Ontology test-retest battery. Enkavi et al.’s own analysis is directly relevant here: across 372 behavioral-task dependent variables, they found contrast (difference-score) DVs had a median reliability roughly 0.29 points lower than the raw, noncontrast DVs they were built from (median ICC 0.17 vs.&nbsp;0.50) — the same qualitative pattern as <span class="citation" data-cites="hedge2018reliability">Hedge et al. (<a href="#ref-hedge2018reliability" role="doc-biblioref">2018</a>)</span>, in a much broader battery, and the Stroop effect is one of the examples they use to illustrate it.</p>
</section>
<section id="data-and-methods" class="level2">
<h2 class="anchored" data-anchor-id="data-and-methods">Data and methods</h2>
<section id="candidate-dataset-search" class="level3">
<h3 class="anchored" data-anchor-id="candidate-dataset-search">Candidate dataset search</h3>
<p>We screened IRW’s table metadata for trial-level (not fixed-item-bank) tasks with a response-time column and a plausible two-condition contrast, using a keyword search over table names, dataset descriptions, and variable lists (<code>heart</code>, <code>flower</code>, <code>flanker</code>, <code>stroop</code>, <code>simon</code>, <code>congruent</code>, <code>stop-signal</code>, etc.), followed by direct inspection of each survivor’s columns.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>step0 <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">decision =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>      table <span class="sc">==</span> <span class="st">"imps2025_hf"</span> <span class="sc">~</span> <span class="st">"Kept (Hearts &amp; Flowers, 2475 respondents, has wave variable)"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>      table <span class="sc">==</span> <span class="st">"alcoholstroop_jones2024"</span> <span class="sc">~</span> <span class="st">"Kept (156 respondents, single session)"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"^enkavi_2019_"</span>, table) <span class="sc">~</span> <span class="st">"Kept (Enkavi et al. 2019 battery, 523 respondents, has wave variable)"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"safety_conflicts"</span>, table) <span class="sc">~</span> <span class="st">"Excluded: keyword false positive on </span><span class="sc">\"</span><span class="st">conflicts</span><span class="sc">\"</span><span class="st"> (public-safety survey, no rt/condition structure)"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Excluded"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(table, n_responses, n_participants, has_rt, decision) <span class="sc">%&gt;%</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Table"</span>, <span class="st">"Responses"</span>, <span class="st">"Participants"</span>, <span class="st">"Has RT"</span>, <span class="st">"Decision"</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-step0" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-step0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Candidate tables surviving the keyword screen, and why each was kept or excluded.
</figcaption>
<div aria-describedby="tbl-step0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table</th>
<th style="text-align: right;">Responses</th>
<th style="text-align: right;">Participants</th>
<th style="text-align: left;">Has RT</th>
<th style="text-align: left;">Decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">alcoholstroop_jones2024</td>
<td style="text-align: right;">26,208</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Kept (156 respondents, single session)</td>
</tr>
<tr class="even">
<td style="text-align: left;">imps2025_hf</td>
<td style="text-align: right;">114,823</td>
<td style="text-align: right;">2,475</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Kept (Hearts &amp; Flowers, 2475 respondents, has wave variable)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mexico_2024_q1safety_conflicts</td>
<td style="text-align: right;">313,709</td>
<td style="text-align: right;">23,999</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="even">
<td style="text-align: left;">mexico_2025_q3safety_conflicts</td>
<td style="text-align: right;">323,921</td>
<td style="text-align: right;">23,634</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mexico_2024_q4safety_conflicts</td>
<td style="text-align: right;">334,406</td>
<td style="text-align: right;">23,441</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="even">
<td style="text-align: left;">mexico_2024_q2safety_conflicts</td>
<td style="text-align: right;">345,050</td>
<td style="text-align: right;">24,106</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mexico_2024_q3safety_conflicts</td>
<td style="text-align: right;">345,884</td>
<td style="text-align: right;">24,086</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="even">
<td style="text-align: left;">mexico_2025_q1safety_conflicts</td>
<td style="text-align: right;">339,523</td>
<td style="text-align: right;">23,576</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mexico_2025_q4safety_conflicts</td>
<td style="text-align: right;">351,786</td>
<td style="text-align: right;">23,913</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="even">
<td style="text-align: left;">mexico_2025_q2safety_conflicts</td>
<td style="text-align: right;">341,218</td>
<td style="text-align: right;">23,712</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Excluded: keyword false positive on “conflicts” (public-safety survey, no rt/condition structure)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">enkavi_2019_stroop</td>
<td style="text-align: right;">64,608</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Kept (Enkavi et al.&nbsp;2019 battery, 523 respondents, has wave variable)</td>
</tr>
<tr class="even">
<td style="text-align: left;">enkavi_2019_simon</td>
<td style="text-align: right;">67,300</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Kept (Enkavi et al.&nbsp;2019 battery, 523 respondents, has wave variable)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">enkavi_2019_ant_flanker</td>
<td style="text-align: right;">96,912</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Kept (Enkavi et al.&nbsp;2019 battery, 523 respondents, has wave variable)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Two further candidates were located by widening the search to any table with an <code>rt</code> column and inspecting item-name/column structure directly (not capturable by a keyword match on task names): <code>wang2022_iat</code> (a fixed 20-item dichotomous bank despite its name — no trial-level RT, excluded) and five <code>matzke-*</code> stop-signal tables (a <code>go_</code>/<code>stop_</code> item-prefix condition, <code>cov_ssd</code> = stop-signal delay). Of those, <code>matzke-etal-2019</code> has 53 respondents and was kept; <code>matzke-experiment1-2022</code>, <code>matzke-experiment3-standard</code>, and <code>matzke-experiment3-gamified-2022</code> have 7, 9, and 9 respondents respectively and were dropped for falling below our 50-respondent floor.</p>
<p>A third round located <code>enkavi_2019_stroop</code>, <code>enkavi_2019_simon</code>, and <code>enkavi_2019_ant_flanker</code> — three tasks from <span class="citation" data-cites="enkavi2019">Enkavi et al. (<a href="#ref-enkavi2019" role="doc-biblioref">2019</a>)</span>’s Self-Regulation Ontology battery — by direct inspection of IRW’s table list rather than the keyword screen above: at the time of writing these tables aren’t yet indexed in IRW’s metadata catalog, so the keyword screen (which scans that catalog) can’t see them, even though they’re fetchable like any other IRW table and their table names alone would have matched the <code>stroop</code>/<code>simon</code>/<code>flanker</code> keywords. Five further tasks in the same battery (<code>enkavi_2019_navon</code>, <code>enkavi_2019_stopsignal</code>, <code>enkavi_2019_gonogo</code>, <code>enkavi_2019_taskswitch</code>, <code>enkavi_2019_dpx_axcpt</code>) were located at the same time but excluded from this round: they’re related but not binary congruent/incongruent contrasts (go/no-go, switch cost, AX-CPT probe types) or need a bespoke 3-condition contrast (Navon), and are left for a future extension of this analysis.</p>
<p>The final set has <strong>seven dataset variants</strong> across six IRW tables:</p>
<ul>
<li><strong>Hearts &amp; Flowers, blocked</strong> (<code>imps2025_hf</code>): the <code>hearts test</code> block (congruent) vs.&nbsp;the <code>flowers test</code> block (incongruent) — a separate-block design.</li>
<li><strong>Hearts &amp; Flowers, mixed-trial</strong> (<code>imps2025_hf</code>): within the <code>mixed test</code> block, trials are classified congruent/incongruent by stimulus shape (heart/flower) rather than by block — a trial-intermixed design, which is structurally closer to how Hedge et al.’s tasks are actually administered (their conditions are intermixed within blocks, not run in separate blocks; see their Fig. 1).</li>
<li><strong>Alcohol Stroop</strong> (<code>alcoholstroop_jones2024</code>): neutral word (congruent analogue) vs.&nbsp;alcohol-related word (incongruent analogue) — an attentional-bias variant of Stroop rather than a color-word conflict task, but with an identical per-trial rt/accuracy structure.</li>
<li><strong>Stop-signal / OSARI</strong> (<code>matzke-etal-2019</code>): go trials (congruent analogue) vs.&nbsp;stop-signal trials (incongruent analogue).</li>
<li><strong>Stroop</strong> (<code>enkavi_2019_stroop</code>): classic color-word Stroop, congruent vs.&nbsp;incongruent, from <span class="citation" data-cites="enkavi2019">Enkavi et al. (<a href="#ref-enkavi2019" role="doc-biblioref">2019</a>)</span>’s Self-Regulation Ontology battery. N=523, an online (Amazon Mechanical Turk) adult sample (52% female, age 21-60, mean 34.1).</li>
<li><strong>Simon</strong> (<code>enkavi_2019_simon</code>): spatial stimulus-response compatibility task, congruent vs.&nbsp;incongruent, same battery and sample as above.</li>
<li><strong>ANT Flanker</strong> (<code>enkavi_2019_ant_flanker</code>): the flanker component of the Attention Network Test, congruent vs.&nbsp;incongruent (a third “neutral” condition, no flankers, is excluded to keep the same two-condition contrast used throughout this vignette), same battery and sample as above.</li>
</ul>
</section>
<section id="preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="preprocessing">Preprocessing</h3>
<p>For each variant we dropped respondents with fewer than 5 trials in either condition (sensitivity checked at a floor of 10; see <a href="#trial-count-sensitivity">Trial-count sensitivity</a>). Per person and condition we computed mean RT on correct trials and mean accuracy, then the contrast</p>
<p><span class="math display">\[D_{rt} = \overline{RT}_{\text{incongruent}} - \overline{RT}_{\text{congruent}}, \qquad
  D_{acc} = \overline{acc}_{\text{congruent}} - \overline{acc}_{\text{incongruent}}\]</span></p>
<p>so that positive values of both indices reflect the “expected” direction of a conflict cost.</p>
<p><strong>Stop-signal deviation.</strong> By construction, a successfully inhibited stop-signal trial has no response and hence no RT — there is no such thing as “the RT of a correct stop trial.” Hedge et al.&nbsp;instead estimate Stop-Signal Reaction Time (SSRT) via a race-model calculation. We do not implement the race model here; instead <span class="math inline">\(D_{rt}\)</span> for the stop-signal dataset uses the RT of <em>failed</em> stop trials (a response did occur) as a naive structural analogue, and <span class="math inline">\(D_{acc}\)</span> compares go-trial direction accuracy to the stop-trial inhibition rate — two different kinds of accuracy. Treat the stop-signal numbers below as a structural check only, not a validated inhibition measure.</p>
<p><strong>Split-half reliability.</strong> For each dataset/measure/condition we ran 500 random split-halves: within each person and condition, trials were randomly assigned to two halves, person means were computed for each half, and the correlation between halves across people was Spearman-Brown corrected (<span class="math inline">\(r_{sb} = 2r/(1+r)\)</span>). The difference score was split-half by using the same halves within each condition, so <span class="math inline">\(D_{\text{half 1}} = \overline{incong}_{\text{half 1}} - \overline{cong}_{\text{half 1}}\)</span>, and correlating the two halves’ difference scores. We report the mean and SD of the Spearman-Brown-corrected reliability across splits, and (for split-half only) restrict to each person’s earliest available session, so that pooling multiple sessions doesn’t artificially inflate reliability for respondents with repeat data.</p>
<p><strong>Test-retest.</strong> Two dataset groups have a genuine wave variable and therefore support real test-retest correlations across sessions (no splitting; raw condition means and <span class="math inline">\(D\)</span> from each full session, correlated across sessions), rather than just split-half:</p>
<ul>
<li><strong>Hearts &amp; Flowers</strong>: two wave pairs were available, <code>PLUS Fall</code> → <code>PLUS Spring</code> and <code>2021-2022 Fall</code> → <code>2021-2022 Spring</code> (different cohorts). <strong>This is an important deviation from Hedge et al.</strong>: their test-retest interval is ~3 weeks in stable young adults, ours is roughly a school semester (~6 months) in developing children aged ~5-11 — real developmental change over that interval, not just measurement noise, will suppress our test-retest correlations relative to theirs.</li>
<li><strong>The three Enkavi et al.&nbsp;(2019) tasks</strong> (Stroop, Simon, ANT Flanker): <code>wave</code> is coded 1/2 for the two sessions. <span class="citation" data-cites="enkavi2019">Enkavi et al. (<a href="#ref-enkavi2019" role="doc-biblioref">2019</a>)</span> report a mean interval of 111 days between waves (median 115, range 60-228) in their Amazon Mechanical Turk adult sample — shorter than Hearts &amp; Flowers’ ~6-month gap and in stable adults rather than developing children, but still much longer than Hedge et al.’s ~3 weeks, and with substantial participant-to-participant variability in the exact interval (unlike the fixed-cohort H&amp;F waves). Of the 523 respondents used for split-half, only respondents retained by Enkavi et al.’s own retest invitation and who cleared our trial floor at both sessions contribute to test-retest estimates (~150 respondents; see <a href="#fig-retest" class="quarto-xref">Figure&nbsp;4</a>).</li>
</ul>
<p>The alcohol Stroop and stop-signal datasets have no wave variable and support split-half only.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="split-half-reliability-conditions-vs.-difference-scores" class="level3">
<h3 class="anchored" data-anchor-id="split-half-reliability-conditions-vs.-difference-scores">Split-half reliability: conditions vs.&nbsp;difference scores</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sh_plot_df <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trial_floor <span class="sc">==</span> <span class="dv">5</span>, <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"test-retest"</span>, reliability_type),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>         dataset <span class="sc">!=</span> <span class="st">"matzke_stopsignal_2019"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">dataset_lab =</span> <span class="fu">factor</span>(dataset_labels[dataset], <span class="at">levels =</span> <span class="fu">rev</span>(dataset_labels)),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">reliability_type =</span> <span class="fu">factor</span>(reliability_type,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                               <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"incongruent"</span>, <span class="st">"difference"</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                               <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Congruent"</span>, <span class="st">"Incongruent"</span>, <span class="st">"Difference score"</span>)),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">measure_lab =</span> measure_labels[measure],</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">tooltip =</span> <span class="fu">paste0</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Dataset: "</span>, dataset_lab,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;Condition: "</span>, reliability_type,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;Measure: "</span>, measure_lab,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;Reliability: "</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, reliability_est), <span class="st">" ± "</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, reliability_sd),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;N: "</span>, n_respondents</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>p_sh <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sh_plot_df, <span class="fu">aes</span>(<span class="at">x =</span> reliability_est, <span class="at">y =</span> dataset_lab, <span class="at">colour =</span> reliability_type, <span class="at">text =</span> tooltip)) <span class="sc">+</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> irw_grey) <span class="sc">+</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> reliability_est <span class="sc">-</span> reliability_sd, <span class="at">xmax =</span> reliability_est <span class="sc">+</span> reliability_sd),</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>                  <span class="at">height =</span> <span class="dv">0</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.6</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>measure_lab) <span class="sc">+</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Congruent"</span> <span class="ot">=</span> irw_grey, <span class="st">"Incongruent"</span> <span class="ot">=</span> <span class="st">"black"</span>,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Difference score"</span> <span class="ot">=</span> irw_red), <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Split-half reliability (Spearman-Brown corrected)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(p_sh, <span class="at">tooltip =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-splithalf" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-splithalf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="plotly html-widget html-fill-item" id="htmlwidget-ef238e6816f22d642334" style="width:100%;height:650px;"></div>
<script type="application/json" data-for="htmlwidget-ef238e6816f22d642334">{"x":{"data":[{"x":[0,0],"y":[0.40000000000000002,6.5999999999999996],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0,0],"y":[0.40000000000000002,6.5999999999999996],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0.7692393911223997,0.50213078734109173,0.63516523503027078,0.80008291225030836,0.8804217197460632,0.84494370691609011],"y":[5.833333333333333,4.833333333333333,3.8333333333333335,2.8333333333333335,1.8333333333333333,0.83333333333333326],"text":["Dataset: Hearts & Flowers (blocked)<br>Condition: Congruent<br>Measure: Accuracy<br>Reliability: 0.77 ± 0.01<br>N: 2259","Dataset: Hearts & Flowers (mixed-trial)<br>Condition: Congruent<br>Measure: Accuracy<br>Reliability: 0.50 ± 0.03<br>N: 632","Dataset: Alcohol Stroop<br>Condition: Congruent<br>Measure: Accuracy<br>Reliability: 0.64 ± 0.05<br>N: 156","Dataset: Stroop (Enkavi et al. 2019)<br>Condition: Congruent<br>Measure: Accuracy<br>Reliability: 0.80 ± 0.02<br>N: 523","Dataset: Simon (Enkavi et al. 2019)<br>Condition: Congruent<br>Measure: Accuracy<br>Reliability: 0.88 ± 0.01<br>N: 523","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Condition: Congruent<br>Measure: Accuracy<br>Reliability: 0.84 ± 0.02<br>N: 523"],"type":"scatter","mode":"lines+markers","opacity":1,"line":{"color":"transparent"},"error_x":{"array":[0.014014423092330919,0.030050129531915215,0.047858675551150531,0.016703107374710591,0.011031324735095382,0.017172572987106061],"arrayminus":[0.014014423092330919,0.030050129531915215,0.047858675551150531,0.016703107374710591,0.011031324735095382,0.017172572987106061],"type":"data","width":0,"symmetric":false,"color":"rgba(127,127,127,1)"},"name":"Congruent","legendgroup":"Congruent","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","opacity":1,"size":9.8267716535433092,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)"}},"hoveron":"points","frame":null},{"x":[0.88389388381441469,0.78357812139918137,0.95013958178605284,0.94924762559977516,0.94764092573916503,0.92968644366136766],"y":[5.833333333333333,4.833333333333333,3.8333333333333335,2.8333333333333335,1.8333333333333333,0.83333333333333326],"text":["Dataset: Hearts & Flowers (blocked)<br>Condition: Congruent<br>Measure: Reaction time<br>Reliability: 0.88 ± 0.01<br>N: 2259","Dataset: Hearts & Flowers (mixed-trial)<br>Condition: Congruent<br>Measure: Reaction time<br>Reliability: 0.78 ± 0.02<br>N: 632","Dataset: Alcohol Stroop<br>Condition: Congruent<br>Measure: Reaction time<br>Reliability: 0.95 ± 0.01<br>N: 156","Dataset: Stroop (Enkavi et al. 2019)<br>Condition: Congruent<br>Measure: Reaction time<br>Reliability: 0.95 ± 0.00<br>N: 523","Dataset: Simon (Enkavi et al. 2019)<br>Condition: Congruent<br>Measure: Reaction time<br>Reliability: 0.95 ± 0.01<br>N: 523","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Condition: Congruent<br>Measure: Reaction time<br>Reliability: 0.93 ± 0.01<br>N: 523"],"type":"scatter","mode":"lines+markers","opacity":1,"line":{"color":"transparent"},"error_x":{"array":[0.0059645673686632428,0.018659366585066728,0.0064852781857479558,0.0037158891876266642,0.011506882652215111,0.0052981141398243947],"arrayminus":[0.0059645673686632428,0.018659366585066728,0.0064852781857479558,0.0037158891876266642,0.011506882652215111,0.0052981141398243947],"type":"data","width":0,"symmetric":false,"color":"rgba(127,127,127,1)"},"name":"Congruent","legendgroup":"Congruent","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","opacity":1,"size":9.8267716535433092,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)"}},"hoveron":"points","frame":null},{"x":[0.91021141527584937,0.58160960016098373,0.61676984610285712,0.78471837188018378,0.84441298202295589,0.93380763304476366],"y":[6,5,4,3,2,1],"text":["Dataset: Hearts & Flowers (blocked)<br>Condition: Incongruent<br>Measure: Accuracy<br>Reliability: 0.91 ± 0.00<br>N: 2259","Dataset: Hearts & Flowers (mixed-trial)<br>Condition: Incongruent<br>Measure: Accuracy<br>Reliability: 0.58 ± 0.02<br>N: 632","Dataset: Alcohol Stroop<br>Condition: Incongruent<br>Measure: Accuracy<br>Reliability: 0.62 ± 0.05<br>N: 156","Dataset: Stroop (Enkavi et al. 2019)<br>Condition: Incongruent<br>Measure: Accuracy<br>Reliability: 0.78 ± 0.02<br>N: 523","Dataset: Simon (Enkavi et al. 2019)<br>Condition: Incongruent<br>Measure: Accuracy<br>Reliability: 0.84 ± 0.01<br>N: 523","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Condition: Incongruent<br>Measure: Accuracy<br>Reliability: 0.93 ± 0.01<br>N: 523"],"type":"scatter","mode":"lines+markers","opacity":1,"line":{"color":"transparent"},"error_x":{"array":[0.0041716701383623933,0.024231927382897478,0.04830961826876512,0.016370084861802914,0.012669765487135054,0.0050436175378006931],"arrayminus":[0.0041716701383623933,0.024231927382897478,0.04830961826876512,0.016370084861802914,0.012669765487135054,0.0050436175378006931],"type":"data","width":0,"symmetric":false,"color":"rgba(0,0,0,1)"},"name":"Incongruent","legendgroup":"Incongruent","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(0,0,0,1)","opacity":1,"size":9.8267716535433092,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)"}},"hoveron":"points","frame":null},{"x":[0.89059123482537661,0.7839975308642041,0.94717276640045089,0.94956796522854081,0.9622049905958433,0.9459396891980012],"y":[6,5,4,3,2,1],"text":["Dataset: Hearts & Flowers (blocked)<br>Condition: Incongruent<br>Measure: Reaction time<br>Reliability: 0.89 ± 0.01<br>N: 2259","Dataset: Hearts & Flowers (mixed-trial)<br>Condition: Incongruent<br>Measure: Reaction time<br>Reliability: 0.78 ± 0.02<br>N: 632","Dataset: Alcohol Stroop<br>Condition: Incongruent<br>Measure: Reaction time<br>Reliability: 0.95 ± 0.01<br>N: 156","Dataset: Stroop (Enkavi et al. 2019)<br>Condition: Incongruent<br>Measure: Reaction time<br>Reliability: 0.95 ± 0.00<br>N: 523","Dataset: Simon (Enkavi et al. 2019)<br>Condition: Incongruent<br>Measure: Reaction time<br>Reliability: 0.96 ± 0.00<br>N: 523","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Condition: Incongruent<br>Measure: Reaction time<br>Reliability: 0.95 ± 0.00<br>N: 523"],"type":"scatter","mode":"lines+markers","opacity":1,"line":{"color":"transparent"},"error_x":{"array":[0.0058151858939481382,0.019541100710305015,0.0070760186791730684,0.0034139251492019129,0.0031592895653369535,0.004461004535869284],"arrayminus":[0.0058151858939481382,0.019541100710305015,0.0070760186791730684,0.0034139251492019129,0.0031592895653369535,0.004461004535869284],"type":"data","width":0,"symmetric":false,"color":"rgba(0,0,0,1)"},"name":"Incongruent","legendgroup":"Incongruent","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(0,0,0,1)","opacity":1,"size":9.8267716535433092,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)"}},"hoveron":"points","frame":null},{"x":[0.85580074988958155,0.28119081927400325,-0.18099817374940588,0.53479821255855409,0.56664951371622341,0.89856149593648016],"y":[6.166666666666667,5.166666666666667,4.166666666666667,3.1666666666666665,2.1666666666666665,1.1666666666666667],"text":["Dataset: Hearts & Flowers (blocked)<br>Condition: Difference score<br>Measure: Accuracy<br>Reliability: 0.86 ± 0.01<br>N: 2259","Dataset: Hearts & Flowers (mixed-trial)<br>Condition: Difference score<br>Measure: Accuracy<br>Reliability: 0.28 ± 0.05<br>N: 632","Dataset: Alcohol Stroop<br>Condition: Difference score<br>Measure: Accuracy<br>Reliability: -0.18 ± 0.16<br>N: 156","Dataset: Stroop (Enkavi et al. 2019)<br>Condition: Difference score<br>Measure: Accuracy<br>Reliability: 0.53 ± 0.03<br>N: 523","Dataset: Simon (Enkavi et al. 2019)<br>Condition: Difference score<br>Measure: Accuracy<br>Reliability: 0.57 ± 0.04<br>N: 523","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Condition: Difference score<br>Measure: Accuracy<br>Reliability: 0.90 ± 0.01<br>N: 523"],"type":"scatter","mode":"lines+markers","opacity":1,"line":{"color":"transparent"},"error_x":{"array":[0.0066829080482553316,0.047885018543971869,0.1599584206315478,0.034874717329357208,0.036512487278276051,0.0079372414178201511],"arrayminus":[0.0066829080482553316,0.047885018543971869,0.15995842063154783,0.034874717329357208,0.036512487278276051,0.0079372414178201511],"type":"data","width":0,"symmetric":false,"color":"rgba(215,48,39,1)"},"name":"Difference score","legendgroup":"Difference score","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(215,48,39,1)","opacity":1,"size":9.8267716535433092,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(215,48,39,1)"}},"hoveron":"points","frame":null},{"x":[0.51074103632246637,0.035642435948276895,0.050965691144791749,0.65028502044118153,0.23111659742309776,0.69139161441531616],"y":[6.166666666666667,5.166666666666667,4.166666666666667,3.1666666666666665,2.1666666666666665,1.1666666666666667],"text":["Dataset: Hearts & Flowers (blocked)<br>Condition: Difference score<br>Measure: Reaction time<br>Reliability: 0.51 ± 0.03<br>N: 2259","Dataset: Hearts & Flowers (mixed-trial)<br>Condition: Difference score<br>Measure: Reaction time<br>Reliability: 0.04 ± 0.10<br>N: 632","Dataset: Alcohol Stroop<br>Condition: Difference score<br>Measure: Reaction time<br>Reliability: 0.05 ± 0.13<br>N: 156","Dataset: Stroop (Enkavi et al. 2019)<br>Condition: Difference score<br>Measure: Reaction time<br>Reliability: 0.65 ± 0.02<br>N: 523","Dataset: Simon (Enkavi et al. 2019)<br>Condition: Difference score<br>Measure: Reaction time<br>Reliability: 0.23 ± 0.07<br>N: 523","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Condition: Difference score<br>Measure: Reaction time<br>Reliability: 0.69 ± 0.02<br>N: 523"],"type":"scatter","mode":"lines+markers","opacity":1,"line":{"color":"transparent"},"error_x":{"array":[0.027666243330181195,0.10092826856218282,0.12573275580693397,0.023854820719545033,0.068124931476559403,0.024853564868294931],"arrayminus":[0.027666243330181139,0.10092826856218282,0.12573275580693397,0.023854820719545033,0.068124931476559375,0.024853564868294931],"type":"data","width":0,"symmetric":false,"color":"rgba(215,48,39,1)"},"name":"Difference score","legendgroup":"Difference score","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","marker":{"autocolorscale":false,"color":"rgba(215,48,39,1)","opacity":1,"size":9.8267716535433092,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(215,48,39,1)"}},"hoveron":"points","frame":null}],"layout":{"margin":{"t":38.449149024491497,"r":8.6342880863428828,"b":44.034869240348698,"l":233.9892071398921},"paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":17.268576172685766},"xaxis":{"domain":[0,0.49518175888038901],"automargin":true,"type":"linear","autorange":false,"range":[-0.40627263810806041,1.0306803238882869],"tickmode":"array","ticktext":["0.0","0.5","1.0"],"tickvals":[0,0.49999999999999983,1],"categoryorder":"array","categoryarray":["0.0","0.5","1.0"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148611},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"y","title":"","hoverformat":".2f"},"annotations":[{"text":"Split-half reliability (Spearman-Brown corrected)","x":0.5,"y":0,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":17.268576172685766},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"top","annotationType":"axis","yshift":-25.902864259028647},{"text":"Accuracy","x":0.24759087944019451,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Reaction time","x":0.75240912055980547,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"}],"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,6.5999999999999996],"tickmode":"array","ticktext":["ANT Flanker (Enkavi et al. 2019)","Simon (Enkavi et al. 2019)","Stroop (Enkavi et al. 2019)","Alcohol Stroop","Hearts & Flowers (mixed-trial)","Hearts & Flowers (blocked)"],"tickvals":[1,2,3,3.9999999999999996,5,6],"categoryorder":"array","categoryarray":["ANT Flanker (Enkavi et al. 2019)","Simon (Enkavi et al. 2019)","Stroop (Enkavi et al. 2019)","Alcohol Stroop","Hearts & Flowers (mixed-trial)","Hearts & Flowers (blocked)"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148611},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"x","title":"","hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0,"x1":0.49518175888038901,"y0":0,"y1":27.629721876297221,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0.50481824111961093,"x1":1,"y0":0,"y1":27.629721876297221,"yanchor":1,"ysizemode":"pixel"}],"xaxis2":{"type":"linear","autorange":false,"range":[-0.40627263810806041,1.0306803238882869],"tickmode":"array","ticktext":["0.0","0.5","1.0"],"tickvals":[0,0.49999999999999983,1],"categoryorder":"array","categoryarray":["0.0","0.5","1.0"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148611},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.50481824111961093,1],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"y","title":"","hoverformat":".2f"},"showlegend":true,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":13.814860938148611},"orientation":"h","x":0.5,"y":-0.14999999999999999,"xanchor":"center","yanchor":"top","title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":17.268576172685766}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"2321105e56cc":{"xintercept":{},"type":"scatter"},"232175573193":{"x":{},"y":{},"colour":{},"text":{},"xmin":{},"xmax":{}},"23216c2683c":{"x":{},"y":{},"colour":{},"text":{}}},"cur_data":"2321105e56cc","visdat":{"2321105e56cc":["function (y) ","x"],"232175573193":["function (y) ","x"],"23216c2683c":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-splithalf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Split-half reliability (Spearman-Brown corrected; mean ± SD across splits) for each condition and the difference score, trial floor = 5, for the six congruency-style dataset variants. Difference-score reliability drops relative to the conditions it’s built from in every one of them, though the size of the drop varies widely. The stop-signal dataset is excluded here and shown separately in <a href="#stop-signal-a-structural-comparison">Stop-signal: a structural comparison</a>, since failed-stop RT isn’t a congruency contrast in the same sense.
</figcaption>
</figure>
</div>
</div>
<details>
<summary>
Show full split-half reliability table (all datasets, measures, and conditions)
</summary>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trial_floor <span class="sc">==</span> <span class="dv">5</span>, <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"test-retest"</span>, reliability_type)) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Dataset =</span> dataset_labels[dataset],</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Measure =</span> measure_labels[measure],</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Condition =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(reliability_type),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">N respondents</span><span class="st">`</span> <span class="ot">=</span> n_respondents,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Reliability (mean ± SD)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.2f ± %.2f"</span>, reliability_est, reliability_sd)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Dataset, Measure) <span class="sc">%&gt;%</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-splithalf" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-splithalf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Split-half reliability by dataset, measure, and condition (trial floor = 5).
</figcaption>
<div aria-describedby="tbl-splithalf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 34%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset</th>
<th style="text-align: left;">Measure</th>
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">N respondents</th>
<th style="text-align: left;">Reliability (mean ± SD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.84 ± 0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.93 ± 0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.90 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.93 ± 0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.95 ± 0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.69 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.64 ± 0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.62 ± 0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">-0.18 ± 0.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.95 ± 0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.95 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.05 ± 0.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.77 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.91 ± 0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.86 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.88 ± 0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.89 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.51 ± 0.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.50 ± 0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.58 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.28 ± 0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.78 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.78 ± 0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.04 ± 0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.88 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.84 ± 0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.57 ± 0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.95 ± 0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.96 ± 0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.23 ± 0.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.95 ± 0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.70 ± 0.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.82 ± 0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">1.00 ± 0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.99 ± 0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.92 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.80 ± 0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.78 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Accuracy</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.53 ± 0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.95 ± 0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.95 ± 0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">Reaction time</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.65 ± 0.02</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</details>
<p>The pattern in <a href="#fig-splithalf" class="quarto-xref">Figure&nbsp;2</a> reproduces the core finding of <span class="citation" data-cites="hedge2018reliability">Hedge et al. (<a href="#ref-hedge2018reliability" role="doc-biblioref">2018</a>)</span> directly: congruent and incongruent RT reliabilities sit at .78-.99 across all six congruency-style dataset variants, but the RT difference-score reliability drops in every one of them. The size of that drop, however, varies considerably. At one extreme, it collapses to near zero for the mixed-trial Hearts &amp; Flowers (0.04) and the alcohol Stroop (0.05). The blocked Hearts &amp; Flowers design (0.51) and the Enkavi et al.&nbsp;(2019) Simon task (0.23) retain a moderate amount. And the Enkavi Stroop (0.65) and ANT Flanker (0.69) retain a sizeable fraction of their component reliability, despite still being well below their congruent/incongruent components (~.93-.96). This is a useful complication of the “collapses to near zero” framing from the Motivation section: the direction of the effect (component &gt;&gt; difference) is essentially universal across these six variants, but its magnitude is not — it depends on exactly how strongly the two conditions covary across people in a given task, sample, and design, which is itself variable. The Enkavi tasks — a much larger (N=523), adult, single-country online sample than the other datasets here — retaining more difference-score reliability than mixed-trial H&amp;F or the alcohol Stroop is consistent with sample composition (a wider age/ability range inflates between-person variance relative to trial-level noise) contributing to that variability, though we can’t isolate that from task differences with only one dataset per task.</p>
<p>The blocked-vs-mixed-trial contrast within the same H&amp;F task is informative: Hedge et al.’s tasks intermix conditions within a block, and it’s exactly that design — the mixed-trial H&amp;F variant — that shows the most severe collapse. Separating congruent and incongruent trials into their own blocks (as the blocked H&amp;F variant does) leaves noticeably more difference-score reliability intact, consistent with the variance-shrinkage mechanism: block separation gives some room for per-block state (vigilance, strategy, warm-up) to vary independently across conditions, which lowers <span class="math inline">\(\mathrm{Cov}(A,B)\)</span> relative to <span class="math inline">\(\mathrm{Var}(A)\)</span> and <span class="math inline">\(\mathrm{Var}(B)\)</span> less than a fully intermixed design does.</p>
<p><strong>This contrast deserves a caution, though.</strong> Mean trials per condition are similar between the two variants (~9.5-11.1 for blocked, ~9.7-9.9 for mixed; see <a href="#trial-count-sensitivity">Trial-count sensitivity</a>), but the <em>retained samples</em> are not: the blocked split-half sample is 2259 respondents (of the 2,475 in <code>imps2025_hf</code>), while the mixed-trial sample is only 632 — about a quarter as many. Since per-condition trial counts are comparable for those who clear the floor in each variant, this gap isn’t the trial floor thinning out the mixed sample; it looks more like most respondents never received a “mixed test” block at all, so blocked and mixed aren’t a within-person manipulation on a shared sample but two considerably different-sized (and potentially differently-composed, e.g.&nbsp;by cohort or wave) subgroups of the full <code>imps2025_hf</code> respondent pool. We can’t rule out that this compositional difference, rather than the block/intermixed design itself, contributes to the reliability gap between them.</p>
</section>
<section id="stop-signal-a-structural-comparison" class="level3">
<h3 class="anchored" data-anchor-id="stop-signal-a-structural-comparison">Stop-signal: a structural comparison</h3>
<p>The stop-signal dataset was excluded from <a href="#fig-splithalf" class="quarto-xref">Figure&nbsp;2</a> above because it doesn’t share the congruent/incongruent structure of the other six variants, and its result is the opposite of the general pattern: its difference-score reliability stays high (0.92), barely below its congruent (go, 1.00) and incongruent (stop, 0.99) components. As detailed in Methods, this isn’t really a like-for-like difference score: <span class="math inline">\(D_{rt}\)</span> here is failed-stop RT minus go RT, not Hedge et al.’s race-model SSRT, so this figure is a structural comparison, not a validated inhibition measure. Failed-stop RT and go RT are driven by different aspects of the race model (a fast guess vs.&nbsp;the whole go-process distribution) and so are less tightly coupled across people than two congruency conditions of the same trial type — the variance-shrinkage mechanism has less to work with. That makes it a useful negative case (the paradox is not automatic whenever you subtract two RTs — it depends on how correlated the two quantities are across people), but not a direct replication attempt, and it should not be read alongside the congruency tasks above as if it were measuring the same kind of contrast. A proper replication would need the race-model SSRT integration method Hedge et al.&nbsp;use, which we do not implement here.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ss_irw <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trial_floor <span class="sc">==</span> <span class="dv">5</span>, measure <span class="sc">==</span> <span class="st">"rt"</span>, <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"test-retest"</span>, reliability_type),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>         dataset <span class="sc">==</span> <span class="st">"matzke_stopsignal_2019"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Condition =</span> <span class="fu">recode</span>(reliability_type,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">congruent =</span> <span class="st">"Go"</span>, <span class="at">incongruent =</span> <span class="st">"Stop"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">difference =</span> <span class="st">"Difference (failed-stop − go)"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">Source =</span> <span class="st">"IRW, split-half"</span>, Condition,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">Reliability =</span> <span class="fu">round</span>(reliability_est, <span class="dv">2</span>))</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>ss_hedge <span class="ot">&lt;-</span> hedge_ref <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(measure <span class="sc">==</span> <span class="st">"rt"</span>, task <span class="sc">==</span> <span class="st">"Stop-signal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">Source =</span> <span class="st">"Hedge et al. (2018), test-retest"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">Condition =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(condition),</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">Reliability =</span> <span class="fu">round</span>(icc_mean, <span class="dv">2</span>))</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(ss_irw, ss_hedge) <span class="sc">%&gt;%</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-stopsignal" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stopsignal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Stop-signal split-half reliability alongside Hedge et al.&nbsp;(2018) Table 1 (mean of their Studies 1 &amp; 2). The IRW ‘Difference’ row is failed-stop RT minus go RT, a structural stand-in for SSRT, not SSRT itself — the two are not the same quantity and shouldn’t be read as a validation of one against the other.
</figcaption>
<div aria-describedby="tbl-stopsignal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 44%">
<col style="width: 40%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Go</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Stop</td>
<td style="text-align: right;">0.99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Difference (failed-stop − go)</td>
<td style="text-align: right;">0.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Go</td>
<td style="text-align: right;">0.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Ssrt</td>
<td style="text-align: right;">0.42</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="where-does-the-variance-go" class="level3">
<h3 class="anchored" data-anchor-id="where-does-the-variance-go">Where does the variance go?</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trial_floor <span class="sc">==</span> <span class="dv">5</span>, measure <span class="sc">==</span> <span class="st">"rt"</span>, reliability_type <span class="sc">==</span> <span class="st">"difference"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Dataset =</span> dataset_labels[dataset],</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Var(congruent)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(var_congruent, <span class="dv">4</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Var(incongruent)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(var_incongruent, <span class="dv">4</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Cov(cong, incong)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(cov_cong_incong, <span class="dv">4</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Var(difference)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(var_difference, <span class="dv">4</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-variance" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Between-person variance components underlying the RT difference score (trial floor = 5). Var(D) = Var(incong) + Var(cong) − 2·Cov(cong, incong); a high covariance relative to the individual variances is what shrinks Var(D).
</figcaption>
<div aria-describedby="tbl-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset</th>
<th style="text-align: right;">Var(congruent)</th>
<th style="text-align: right;">Var(incongruent)</th>
<th style="text-align: right;">Cov(cong, incong)</th>
<th style="text-align: right;">Var(difference)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: right;">0.1710</td>
<td style="text-align: right;">0.2395</td>
<td style="text-align: right;">0.1482</td>
<td style="text-align: right;">0.1113</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: right;">0.0134</td>
<td style="text-align: right;">0.0138</td>
<td style="text-align: right;">0.0106</td>
<td style="text-align: right;">0.0061</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: right;">6.4405</td>
<td style="text-align: right;">6.4232</td>
<td style="text-align: right;">6.0804</td>
<td style="text-align: right;">0.7030</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: right;">0.0954</td>
<td style="text-align: right;">0.0622</td>
<td style="text-align: right;">0.0741</td>
<td style="text-align: right;">0.0095</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">0.0103</td>
<td style="text-align: right;">0.0151</td>
<td style="text-align: right;">0.0109</td>
<td style="text-align: right;">0.0037</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">0.0104</td>
<td style="text-align: right;">0.0105</td>
<td style="text-align: right;">0.0099</td>
<td style="text-align: right;">0.0011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">0.0051</td>
<td style="text-align: right;">0.0086</td>
<td style="text-align: right;">0.0055</td>
<td style="text-align: right;">0.0027</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This table makes <a href="#eq-vardiff" class="quarto-xref">Equation&nbsp;1</a> concrete: in every dataset, <span class="math inline">\(\mathrm{Cov}(\text{cong}, \text{incong})\)</span> is a large fraction of both individual variances, so subtracting <span class="math inline">\(2\,\mathrm{Cov}\)</span> (the last term in <a href="#eq-vardiff" class="quarto-xref">Equation&nbsp;1</a>) removes most of the variance that Var(congruent) and Var(incongruent) contribute, leaving Var(difference) small relative to either component alone.</p>
<p><a href="#fig-variance-decomp" class="quarto-xref">Figure&nbsp;3</a> shows <a href="#eq-vardiff" class="quarto-xref">Equation&nbsp;1</a> concretely for a single task, the alcohol Stroop. Var(congruent) and Var(incongruent) are both large and similar in size, but so is <span class="math inline">\(2\,\mathrm{Cov}(\text{cong}, \text{incong})\)</span> — almost as large as the two variances combined — so nearly all of that variance is removed in the subtraction, leaving Var(difference) close to zero. This is the arithmetic behind the “reliability collapses” claim above: two individually well-behaved, reliable measurements can combine into an almost-zero-variance difference score whenever they’re highly correlated across people.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>vdf_row <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trial_floor <span class="sc">==</span> <span class="dv">5</span>, measure <span class="sc">==</span> <span class="st">"rt"</span>, reliability_type <span class="sc">==</span> <span class="st">"difference"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>         dataset <span class="sc">==</span> <span class="st">"alcoholstroop_jones2024"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>vdf <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">component =</span> <span class="fu">factor</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"Var(congruent)"</span>, <span class="st">"Var(incongruent)"</span>, <span class="st">"2·Cov(cong, incong)"</span>, <span class="st">"Var(difference)"</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Var(congruent)"</span>, <span class="st">"Var(incongruent)"</span>, <span class="st">"2·Cov(cong, incong)"</span>, <span class="st">"Var(difference)"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(vdf_row<span class="sc">$</span>var_congruent, vdf_row<span class="sc">$</span>var_incongruent,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>            <span class="dv">2</span> <span class="sc">*</span> vdf_row<span class="sc">$</span>cov_cong_incong, vdf_row<span class="sc">$</span>var_difference),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">role  =</span> <span class="fu">c</span>(<span class="st">"congruent"</span>, <span class="st">"incongruent"</span>, <span class="st">"subtracted"</span>, <span class="st">"result"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vdf, <span class="fu">aes</span>(<span class="at">x =</span> component, <span class="at">y =</span> value, <span class="at">fill =</span> role)) <span class="sc">+</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, value)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.4</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">congruent =</span> irw_grey, <span class="at">incongruent =</span> <span class="st">"black"</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>                               <span class="at">subtracted =</span> irw_blue, <span class="at">result =</span> irw_red),</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>                     <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Variance (RT, seconds²)"</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">paste</span>(dataset_labels[<span class="st">"alcoholstroop_jones2024"</span>], <span class="st">"RT: where the variance goes"</span>)) <span class="sc">+</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="fu">max</span>(vdf<span class="sc">$</span>value) <span class="sc">*</span> <span class="fl">1.15</span>) <span class="sc">+</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-variance-decomp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-variance-decomp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hf_reliability_paradox_files/figure-html/fig-variance-decomp-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-variance-decomp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Variance decomposition for the alcohol Stroop RT difference score (trial floor = 5). Var(difference) = Var(congruent) + Var(incongruent) − 2·Cov(congruent, incongruent); the covariance bar is almost as large as the sum of the two variance bars, leaving very little variance in the difference score.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="true-test-retest-reliability" class="level3">
<h3 class="anchored" data-anchor-id="true-test-retest-reliability">True test-retest reliability</h3>
<p>Five of the seven dataset variants have a genuine wave variable and therefore support true test-retest correlations, not just split-half: the two Hearts &amp; Flowers variants (a ~6-month, within-school-year gap in developing children) and the three Enkavi et al.&nbsp;(2019) tasks (a mean 111-day gap in adults; see Preprocessing).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>retest_df <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dataset <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"imps2025_hf_blocked"</span>, <span class="st">"imps2025_hf_mixed"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"enkavi_stroop"</span>, <span class="st">"enkavi_simon"</span>, <span class="st">"enkavi_ant_flanker"</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>         measure <span class="sc">==</span> <span class="st">"rt"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">design =</span> <span class="fu">case_when</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"PLUS Fall -&gt; PLUS Spring"</span>, reliability_type) <span class="sc">~</span> <span class="st">"Test-retest (H&amp;F, PLUS cohort)"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"2021-2022 Fall -&gt; 2021-2022 Spring"</span>, reliability_type) <span class="sc">~</span> <span class="st">"Test-retest (H&amp;F, K cohort)"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"test-retest: 1 -&gt; 2"</span>, reliability_type) <span class="sc">~</span> <span class="st">"Test-retest (Enkavi et al. 2019, mean 111d)"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>      trial_floor <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Split-half (single session)"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">condition =</span> <span class="fu">case_when</span>(</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"^congruent"</span>, reliability_type) <span class="sc">~</span> <span class="st">"Congruent"</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"^incongruent"</span>, reliability_type) <span class="sc">~</span> <span class="st">"Incongruent"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"^difference"</span>, reliability_type) <span class="sc">~</span> <span class="st">"Difference score"</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">dataset_lab =</span> dataset_labels[dataset],</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">tooltip =</span> <span class="fu">paste0</span>(</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Dataset: "</span>, dataset_labels[dataset],</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;Design: "</span>, design,</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;Condition: "</span>, condition,</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>      <span class="st">"&lt;br&gt;Reliability: "</span>, <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, reliability_est)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(design))</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>p_retest <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(retest_df, <span class="fu">aes</span>(<span class="at">x =</span> reliability_est, <span class="at">y =</span> condition, <span class="at">colour =</span> design, <span class="at">text =</span> tooltip)) <span class="sc">+</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> irw_grey) <span class="sc">+</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.8</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>dataset_lab, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Split-half (single session)"</span> <span class="ot">=</span> irw_blue,</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Test-retest (H&amp;F, PLUS cohort)"</span> <span class="ot">=</span> irw_red,</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Test-retest (H&amp;F, K cohort)"</span> <span class="ot">=</span> <span class="st">"#f4a582"</span>,</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"Test-retest (Enkavi et al. 2019, mean 111d)"</span> <span class="ot">=</span> <span class="st">"#1a9850"</span>),</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name =</span> <span class="cn">NULL</span>, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">nrow =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reliability"</span>, <span class="at">y =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(p_retest, <span class="at">tooltip =</span> <span class="st">"text"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layout</span>(</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend =</span> <span class="fu">list</span>(<span class="at">orientation =</span> <span class="st">"h"</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.15</span>),</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">annotations =</span> <span class="fu">list</span>(<span class="fu">list</span>(</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">text      =</span> <span class="st">"H&amp;F PLUS cohort: Fall -&gt; Spring, one school year. H&amp;F K cohort: 2021-22 Fall -&gt; Spring. Enkavi et al. (2019): mean 111-day gap, range 60-228 days, Amazon Mechanical Turk adults."</span>,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>      <span class="at">showarrow =</span> <span class="cn">FALSE</span>, <span class="at">xref =</span> <span class="st">"paper"</span>, <span class="at">yref =</span> <span class="st">"paper"</span>,</span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.25</span>, <span class="at">xanchor =</span> <span class="st">"left"</span>, <span class="at">yanchor =</span> <span class="st">"top"</span>,</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>      <span class="at">font =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"grey50"</span>)</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-retest" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-retest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="plotly html-widget html-fill-item" id="htmlwidget-71a87d63714ffa444bd5" style="width:100%;height:478px;"></div>
<script type="application/json" data-for="htmlwidget-71a87d63714ffa444bd5">{"x":{"data":[{"x":[0,0],"y":[0.40000000000000002,3.6000000000000001],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0,0],"y":[0.40000000000000002,3.6000000000000001],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0,0],"y":[0.40000000000000002,3.6000000000000001],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"x":[0,0],"y":[0.40000000000000002,3.6000000000000001],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"x":[0,0],"y":[0.40000000000000002,3.6000000000000001],"text":"","type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(127,127,127,1)","dash":"dash"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"x":[0.92968644366136766,0.9459396891980012,0.69139161441531616],"y":[0.875,2.875,1.875],"text":["Dataset: ANT Flanker (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Congruent<br>Reliability: 0.93","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Incongruent<br>Reliability: 0.95","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Difference score<br>Reliability: 0.69"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(33,102,172,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(33,102,172,1)"}},"hoveron":"points","name":"Split-half (single session)","legendgroup":"Split-half (single session)","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0.88389388381441469,0.89059123482537661,0.51074103632246637],"y":[0.83333333333333326,2.8333333333333335,1.8333333333333333],"text":["Dataset: Hearts & Flowers (blocked)<br>Design: Split-half (single session)<br>Condition: Congruent<br>Reliability: 0.88","Dataset: Hearts & Flowers (blocked)<br>Design: Split-half (single session)<br>Condition: Incongruent<br>Reliability: 0.89","Dataset: Hearts & Flowers (blocked)<br>Design: Split-half (single session)<br>Condition: Difference score<br>Reliability: 0.51"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(33,102,172,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(33,102,172,1)"}},"hoveron":"points","name":"Split-half (single session)","legendgroup":"Split-half (single session)","showlegend":false,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0.78357812139918137,0.7839975308642041,0.035642435948276895],"y":[0.875,2.875,1.875],"text":["Dataset: Hearts & Flowers (mixed-trial)<br>Design: Split-half (single session)<br>Condition: Congruent<br>Reliability: 0.78","Dataset: Hearts & Flowers (mixed-trial)<br>Design: Split-half (single session)<br>Condition: Incongruent<br>Reliability: 0.78","Dataset: Hearts & Flowers (mixed-trial)<br>Design: Split-half (single session)<br>Condition: Difference score<br>Reliability: 0.04"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(33,102,172,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(33,102,172,1)"}},"hoveron":"points","name":"Split-half (single session)","legendgroup":"Split-half (single session)","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null},{"x":[0.94764092573916503,0.9622049905958433,0.23111659742309776],"y":[0.875,2.875,1.875],"text":["Dataset: Simon (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Congruent<br>Reliability: 0.95","Dataset: Simon (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Incongruent<br>Reliability: 0.96","Dataset: Simon (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Difference score<br>Reliability: 0.23"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(33,102,172,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(33,102,172,1)"}},"hoveron":"points","name":"Split-half (single session)","legendgroup":"Split-half (single session)","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"x":[0.94924762559977516,0.94956796522854081,0.65028502044118153],"y":[0.875,2.875,1.875],"text":["Dataset: Stroop (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Congruent<br>Reliability: 0.95","Dataset: Stroop (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Incongruent<br>Reliability: 0.95","Dataset: Stroop (Enkavi et al. 2019)<br>Design: Split-half (single session)<br>Condition: Difference score<br>Reliability: 0.65"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(33,102,172,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(33,102,172,1)"}},"hoveron":"points","name":"Split-half (single session)","legendgroup":"Split-half (single session)","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"x":[0.58943237724288378,0.60829040070600071,0.33658552120813579],"y":[1.125,3.125,2.125],"text":["Dataset: ANT Flanker (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Congruent<br>Reliability: 0.59","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Incongruent<br>Reliability: 0.61","Dataset: ANT Flanker (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Difference score<br>Reliability: 0.34"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(26,152,80,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(26,152,80,1)"}},"hoveron":"points","name":"Test-retest (Enkavi et al. 2019, mean 111d)","legendgroup":"Test-retest (Enkavi et al. 2019, mean 111d)","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0.62949530397335518,0.60853840100639744,0.24458247260763691],"y":[1.125,3.125,2.125],"text":["Dataset: Simon (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Congruent<br>Reliability: 0.63","Dataset: Simon (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Incongruent<br>Reliability: 0.61","Dataset: Simon (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Difference score<br>Reliability: 0.24"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(26,152,80,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(26,152,80,1)"}},"hoveron":"points","name":"Test-retest (Enkavi et al. 2019, mean 111d)","legendgroup":"Test-retest (Enkavi et al. 2019, mean 111d)","showlegend":false,"xaxis":"x2","yaxis":"y2","hoverinfo":"text","frame":null},{"x":[0.54114260163336825,0.6401771486140857,0.43636296154746118],"y":[1.125,3.125,2.125],"text":["Dataset: Stroop (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Congruent<br>Reliability: 0.54","Dataset: Stroop (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Incongruent<br>Reliability: 0.64","Dataset: Stroop (Enkavi et al. 2019)<br>Design: Test-retest (Enkavi et al. 2019, mean 111d)<br>Condition: Difference score<br>Reliability: 0.44"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(26,152,80,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(26,152,80,1)"}},"hoveron":"points","name":"Test-retest (Enkavi et al. 2019, mean 111d)","legendgroup":"Test-retest (Enkavi et al. 2019, mean 111d)","showlegend":false,"xaxis":"x","yaxis":"y3","hoverinfo":"text","frame":null},{"x":[0.46548075829553653,0.21420506303904252,0.16959457530079672],"y":[1,3,2],"text":["Dataset: Hearts & Flowers (blocked)<br>Design: Test-retest (H&F, K cohort)<br>Condition: Congruent<br>Reliability: 0.47","Dataset: Hearts & Flowers (blocked)<br>Design: Test-retest (H&F, K cohort)<br>Condition: Incongruent<br>Reliability: 0.21","Dataset: Hearts & Flowers (blocked)<br>Design: Test-retest (H&F, K cohort)<br>Condition: Difference score<br>Reliability: 0.17"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(244,165,130,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(244,165,130,1)"}},"hoveron":"points","name":"Test-retest (H&F, K cohort)","legendgroup":"Test-retest (H&F, K cohort)","showlegend":true,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0.38941532006587365,0.33809166937297525,0.049233778081026212],"y":[1.1666666666666667,3.1666666666666665,2.1666666666666665],"text":["Dataset: Hearts & Flowers (blocked)<br>Design: Test-retest (H&F, PLUS cohort)<br>Condition: Congruent<br>Reliability: 0.39","Dataset: Hearts & Flowers (blocked)<br>Design: Test-retest (H&F, PLUS cohort)<br>Condition: Incongruent<br>Reliability: 0.34","Dataset: Hearts & Flowers (blocked)<br>Design: Test-retest (H&F, PLUS cohort)<br>Condition: Difference score<br>Reliability: 0.05"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(215,48,39,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(215,48,39,1)"}},"hoveron":"points","name":"Test-retest (H&F, PLUS cohort)","legendgroup":"Test-retest (H&F, PLUS cohort)","showlegend":true,"xaxis":"x2","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0.004396664212454702,0.0058981850652473052,0.072124575601508728],"y":[1.125,3.125,2.125],"text":["Dataset: Hearts & Flowers (mixed-trial)<br>Design: Test-retest (H&F, PLUS cohort)<br>Condition: Congruent<br>Reliability: 0.00","Dataset: Hearts & Flowers (mixed-trial)<br>Design: Test-retest (H&F, PLUS cohort)<br>Condition: Incongruent<br>Reliability: 0.01","Dataset: Hearts & Flowers (mixed-trial)<br>Design: Test-retest (H&F, PLUS cohort)<br>Condition: Difference score<br>Reliability: 0.07"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(215,48,39,1)","opacity":1,"size":10.58267716535433,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(215,48,39,1)"}},"hoveron":"points","name":"Test-retest (H&F, PLUS cohort)","legendgroup":"Test-retest (H&F, PLUS cohort)","showlegend":false,"xaxis":"x","yaxis":"y2","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":38.449149024491497,"r":8.6342880863428828,"b":44.034869240348698,"l":123.47031963470323},"paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":17.268576172685766},"xaxis":{"domain":[0,0.49644971706976032],"automargin":true,"type":"linear","autorange":false,"range":[-0.048110249529792169,1.0103152401256354],"tickmode":"array","ticktext":["0.00","0.25","0.50","0.75","1.00"],"tickvals":[0,0.24999999999999992,0.5,0.75,1],"categoryorder":"array","categoryarray":["0.00","0.25","0.50","0.75","1.00"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148611},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"y3","title":"","hoverformat":".2f"},"annotations":[{"text":"Reliability","x":0.5,"y":0,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":17.268576172685766},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"top","annotationType":"axis","yshift":-25.902864259028647},{"text":"ANT Flanker (Enkavi et al. 2019)","x":0.24822485853488016,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Hearts & Flowers (blocked)","x":0.75177514146511981,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Hearts & Flowers (mixed-trial)","x":0.24822485853488016,"y":0.65413923975567823,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Simon (Enkavi et al. 2019)","x":0.75177514146511981,"y":0.65413923975567823,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"Stroop (Enkavi et al. 2019)","x":0.24822485853488016,"y":0.3208059064223448,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(26,26,26,1)","family":"","size":13.814860938148611},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"center","yanchor":"bottom"},{"text":"H&F PLUS cohort: Fall -> Spring, one school year. H&F K cohort: 2021-22 Fall -> Spring. Enkavi et al. (2019): mean 111-day gap, range 60-228 days, Amazon Mechanical Turk adults.","showarrow":false,"xref":"paper","yref":"paper","x":0,"y":-0.25,"xanchor":"left","yanchor":"top","font":{"size":10,"color":"grey50"}}],"yaxis":{"domain":[0.67919409357765526,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["Congruent","Difference score","Incongruent"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["Congruent","Difference score","Incongruent"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148612},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"x","title":"","hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0,"x1":0.49644971706976032,"y0":0,"y1":27.629721876297221,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0.50355028293023962,"x1":1,"y0":0,"y1":27.629721876297221,"yanchor":1,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0,"x1":0.49644971706976032,"y0":0,"y1":27.629721876297221,"yanchor":0.65413923975567823,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0.50355028293023962,"x1":1,"y0":0,"y1":27.629721876297221,"yanchor":0.65413923975567823,"ysizemode":"pixel"},{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","layer":"below","x0":0,"x1":0.49644971706976032,"y0":0,"y1":27.629721876297221,"yanchor":0.3208059064223448,"ysizemode":"pixel"}],"xaxis2":{"type":"linear","autorange":false,"range":[-0.048110249529792169,1.0103152401256354],"tickmode":"array","ticktext":["0.00","0.25","0.50","0.75","1.00"],"tickvals":[0,0.24999999999999992,0.5,0.75,1],"categoryorder":"array","categoryarray":["0.00","0.25","0.50","0.75","1.00"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148611},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.50355028293023962,1],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"y2","title":"","hoverformat":".2f"},"yaxis2":{"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["Congruent","Difference score","Incongruent"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["Congruent","Difference score","Incongruent"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148612},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0.34586076024432194,0.65413923975567823],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"x","title":"","hoverformat":".2f"},"yaxis3":{"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["Congruent","Difference score","Incongruent"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["Congruent","Difference score","Incongruent"],"nticks":null,"ticks":"","tickcolor":null,"ticklen":4.3171440431714414,"tickwidth":0,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":13.814860938148612},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"domain":[0,0.3208059064223448],"gridcolor":"rgba(235,235,235,1)","gridwidth":0.78493528057662576,"zeroline":false,"anchor":"x","title":"","hoverformat":".2f"},"showlegend":true,"legend":{"bgcolor":null,"bordercolor":null,"borderwidth":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":13.814860938148611},"orientation":"h","x":0.5,"y":-0.14999999999999999,"xanchor":"center","yanchor":"top","title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":17.268576172685766}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"232169acaef0":{"xintercept":{},"type":"scatter"},"2321b5b85d2":{"x":{},"y":{},"colour":{},"text":{}}},"cur_data":"232169acaef0","visdat":{"232169acaef0":["function (y) ","x"],"2321b5b85d2":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-retest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Split-half (single session) vs.&nbsp;true test-retest reliability for RT, across all five dataset variants with a wave variable. Hearts &amp; Flowers test-retest spans roughly a school semester in developing children; the Enkavi tasks span a mean 111-day gap in adults. Neither matches Hedge et al.’s ~3-week adult interval, so lower absolute values are expected in both.
</figcaption>
</figure>
</div>
</div>
<p>Test-retest reliabilities are lower than split-half across the board, as expected from the much longer retest interval in both the H&amp;F and Enkavi designs relative to Hedge et al.’s ~3 weeks. But the <em>relative</em> pattern survives everywhere: the difference score’s test-retest reliability is consistently the lowest of the three conditions, in all five dataset variants, indicating the paradox isn’t an artifact of the within-session split-half method — it also shows up when the same people are tested again weeks or months later, in both a developmental (H&amp;F) and a stable-adult (Enkavi) sample. As with the split-half results, the <em>size</em> of the test-retest collapse varies: the Enkavi Stroop difference score (0.44) retains noticeably more reliability across a true ~111-day retest than the Enkavi Simon (0.24) or ANT Flanker (0.34) difference scores do, mirroring the split-half ordering for the same three tasks.</p>
</section>
<section id="comparison-to-hedge-powell-sumner-2018" class="level3">
<h3 class="anchored" data-anchor-id="comparison-to-hedge-powell-sumner-2018">Comparison to Hedge, Powell &amp; Sumner (2018)</h3>
<p>The table below places our estimates next to the point estimates reported in Hedge et al.’s Table 1 (average of their Studies 1 and 2; two-way random-effects ICC, absolute agreement, ~3-week test-retest in adults), for the six congruency-style tasks. (The stop-signal dataset is compared separately in <a href="#stop-signal-a-structural-comparison">Stop-signal: a structural comparison</a>, since it isn’t a congruency contrast.) IRW rows are shown per comparable task: the split-half (single-session) estimate, which is the most directly comparable design for the alcohol Stroop since it has no wave variable, plus a test-retest estimate for every dataset that has one (Hearts &amp; Flowers and the three Enkavi et al.&nbsp;2019 tasks) — of the two, the Enkavi test-retest rows are the closer match to Hedge et al.’s own true-test-retest, stable-adult design.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>irw_split <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(trial_floor <span class="sc">==</span> <span class="dv">5</span>, measure <span class="sc">==</span> <span class="st">"rt"</span>, <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"test-retest"</span>, reliability_type),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>         dataset <span class="sc">!=</span> <span class="st">"matzke_stopsignal_2019"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">pair_task =</span> dataset_labels[dataset], <span class="at">source =</span> <span class="st">"IRW, split-half"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">condition =</span> reliability_type, <span class="at">reliability =</span> reliability_est)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>irw_retest_hf <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(measure <span class="sc">==</span> <span class="st">"rt"</span>, <span class="fu">grepl</span>(<span class="st">"test-retest: PLUS Fall"</span>, reliability_type)) <span class="sc">%&gt;%</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">condition =</span> <span class="fu">sub</span>(<span class="st">" </span><span class="sc">\\</span><span class="st">(test-retest.*</span><span class="sc">\\</span><span class="st">)"</span>, <span class="st">""</span>, reliability_type)) <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">pair_task =</span> dataset_labels[dataset], <span class="at">source =</span> <span class="st">"IRW, test-retest (H&amp;F, Fall-&gt;Spring)"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>            condition, <span class="at">reliability =</span> reliability_est)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>irw_retest_enkavi <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(measure <span class="sc">==</span> <span class="st">"rt"</span>, <span class="fu">grepl</span>(<span class="st">"test-retest: 1 -&gt; 2"</span>, reliability_type)) <span class="sc">%&gt;%</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">condition =</span> <span class="fu">sub</span>(<span class="st">" </span><span class="sc">\\</span><span class="st">(test-retest.*</span><span class="sc">\\</span><span class="st">)"</span>, <span class="st">""</span>, reliability_type)) <span class="sc">%&gt;%</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">pair_task =</span> dataset_labels[dataset], <span class="at">source =</span> <span class="st">"IRW, test-retest (Enkavi, mean 111d)"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>            condition, <span class="at">reliability =</span> reliability_est)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>hedge_tbl <span class="ot">&lt;-</span> hedge_ref <span class="sc">%&gt;%</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(measure <span class="sc">==</span> <span class="st">"rt"</span>, task <span class="sc">!=</span> <span class="st">"Stop-signal"</span>, task <span class="sc">!=</span> <span class="st">"Go/No-go"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">pair_task =</span> task, <span class="at">source =</span> <span class="st">"Hedge et al. (2018), test-retest"</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">condition =</span> condition, <span class="at">reliability =</span> icc_mean)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>pairing <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>pair_task_irw,                     <span class="sc">~</span>pair_task_hedge,</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hearts &amp; Flowers (mixed-trial)"</span>,   <span class="st">"Flanker"</span>,</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hearts &amp; Flowers (blocked)"</span>,       <span class="st">"Flanker"</span>,</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Alcohol Stroop"</span>,                   <span class="st">"Stroop"</span>,</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Stroop (Enkavi et al. 2019)"</span>,      <span class="st">"Stroop"</span>,</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ANT Flanker (Enkavi et al. 2019)"</span>, <span class="st">"Flanker"</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>comparison <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(irw_split, irw_retest_hf, irw_retest_enkavi) <span class="sc">%&gt;%</span></span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(pairing, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"pair_task"</span> <span class="ot">=</span> <span class="st">"pair_task_irw"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="st">`</span><span class="at">Lab task analogue</span><span class="st">`</span> <span class="ot">=</span> pair_task_hedge, <span class="st">`</span><span class="at">IRW dataset</span><span class="st">`</span> <span class="ot">=</span> pair_task,</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>            <span class="at">Source =</span> source, <span class="at">Condition =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(condition),</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>            <span class="at">Reliability =</span> <span class="fu">round</span>(reliability, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>    hedge_tbl <span class="sc">%&gt;%</span></span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>      <span class="fu">transmute</span>(<span class="st">`</span><span class="at">Lab task analogue</span><span class="st">`</span> <span class="ot">=</span> pair_task, <span class="st">`</span><span class="at">IRW dataset</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"—"</span>,</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>                <span class="at">Source =</span> source, <span class="at">Condition =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(condition),</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>                <span class="at">Reliability =</span> <span class="fu">round</span>(reliability, <span class="dv">2</span>))</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="st">`</span><span class="at">Lab task analogue</span><span class="st">`</span>, Source, <span class="fu">factor</span>(Condition, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Congruent"</span>, <span class="st">"Incongruent"</span>, <span class="st">"Difference"</span>, <span class="st">"Go"</span>, <span class="st">"Ssrt"</span>)))</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(comparison)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-hedge-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hedge-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: IRW reliability estimates alongside Hedge et al.&nbsp;(2018) Table 1 point estimates (mean of their Studies 1 &amp; 2), for the six congruency-style tasks. NA where a comparable estimate wasn’t computed (e.g.&nbsp;no test-retest wave for a dataset). Stop-signal is shown separately below.
</figcaption>
<div aria-describedby="tbl-hedge-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 29%">
<col style="width: 33%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lab task analogue</th>
<th style="text-align: left;">IRW dataset</th>
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Condition</th>
<th style="text-align: right;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.51</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, test-retest (Enkavi, mean 111d)</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, test-retest (Enkavi, mean 111d)</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, test-retest (Enkavi, mean 111d)</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">IRW, test-retest (H&amp;F, Fall-&gt;Spring)</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">IRW, test-retest (H&amp;F, Fall-&gt;Spring)</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">IRW, test-retest (H&amp;F, Fall-&gt;Spring)</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">IRW, test-retest (H&amp;F, Fall-&gt;Spring)</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: left;">IRW, test-retest (H&amp;F, Fall-&gt;Spring)</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flanker</td>
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: left;">IRW, test-retest (H&amp;F, Fall-&gt;Spring)</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">Hedge et al.&nbsp;(2018), test-retest</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, split-half</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, test-retest (Enkavi, mean 111d)</td>
<td style="text-align: left;">Congruent</td>
<td style="text-align: right;">0.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, test-retest (Enkavi, mean 111d)</td>
<td style="text-align: left;">Incongruent</td>
<td style="text-align: right;">0.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop</td>
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: left;">IRW, test-retest (Enkavi, mean 111d)</td>
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">0.44</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A few things stand out. First, the <em>direction</em> of the effect (condition reliability &gt;&gt; difference-score reliability) matches Hedge et al.&nbsp;in every task pair shown here (the stop-signal analogue, excluded from this table, runs the opposite way — see <a href="#stop-signal-a-structural-comparison">Stop-signal: a structural comparison</a>). Second, our absolute IRW split-half numbers for individual conditions run higher than Hedge et al.’s test-retest ICCs — expected, since split-half reliability has no opportunity for between-session instability to erode it, while ICC test-retest does. Third, the Enkavi test-retest rows are the closest design match to Hedge et al.’s own true-test-retest methodology among our datasets, but don’t line up on magnitude in a consistent direction: the Enkavi Flanker test-retest difference-score reliability (.34) is closer to Hedge et al.’s Flanker ICC (.49) than Enkavi’s own split-half estimate (.69) is, while for Stroop it’s the reverse — Enkavi’s split-half estimate (.65) is closer to Hedge et al.’s Stroop ICC (.63) than Enkavi’s own test-retest estimate (.44) is. We read this as a caution against over-interpreting small magnitude differences across these comparisons: different reliability estimators (Pearson split-half here vs. Hedge et al.’s two-way random-effects ICC), samples, and retest intervals all contribute noise to the exact numbers, even when the qualitative pattern (component &gt;&gt; difference) is consistent throughout.</p>
</section>
<section id="trial-count-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="trial-count-sensitivity">Trial-count sensitivity</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(measure <span class="sc">==</span> <span class="st">"rt"</span>, reliability_type <span class="sc">==</span> <span class="st">"difference"</span>, <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"test-retest"</span>, reliability_type)) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">Dataset =</span> dataset_labels[dataset], <span class="st">`</span><span class="at">Trial floor</span><span class="st">`</span> <span class="ot">=</span> trial_floor,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">N respondents</span><span class="st">`</span> <span class="ot">=</span> n_respondents,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Reliability (mean ± SD)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sprintf</span>(<span class="st">"%.2f ± %.2f"</span>, reliability_est, reliability_sd)) <span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Dataset, <span class="st">`</span><span class="at">Trial floor</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-sensitivity" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Split-half difference-score RT reliability at trial floors of 5 vs.&nbsp;10 trials/person/condition.
</figcaption>
<div aria-describedby="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 39%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset</th>
<th style="text-align: right;">Trial floor</th>
<th style="text-align: right;">N respondents</th>
<th style="text-align: left;">Reliability (mean ± SD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.69 ± 0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">ANT Flanker (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.69 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.05 ± 0.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol Stroop</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">156</td>
<td style="text-align: left;">0.05 ± 0.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2259</td>
<td style="text-align: left;">0.51 ± 0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (blocked)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">945</td>
<td style="text-align: left;">0.60 ± 0.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">632</td>
<td style="text-align: left;">0.04 ± 0.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hearts &amp; Flowers (mixed-trial)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">239</td>
<td style="text-align: left;">0.15 ± 0.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.23 ± 0.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simon (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.23 ± 0.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.92 ± 0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stop-signal (OSARI)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">53</td>
<td style="text-align: left;">0.92 ± 0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.65 ± 0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stroop (Enkavi et al.&nbsp;2019)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">523</td>
<td style="text-align: left;">0.65 ± 0.02</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Raising the per-condition trial floor from 5 to 10 trims the sample (most sharply for the mixed-trial H&amp;F variant, which has fewer trials per condition to begin with) but does not change the qualitative picture: the difference score remains far less reliable than either condition alone. The three Enkavi tasks are unaffected by this trim (523 respondents at both floors) — they simply have more trials per condition to begin with than H&amp;F does.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>The reliability paradox replicates in IRW cognitive-control data — as an <strong>attenuation of variable size, not a uniform collapse to zero</strong>. Across six independent tasks (Hearts &amp; Flowers, alcohol Stroop, a stop-signal task, and the Enkavi et al.&nbsp;2019 Stroop, Simon, and ANT Flanker tasks) spanning split-half and true test-retest designs in both a developmental and a stable-adult sample, individual congruent and incongruent conditions are consistently far more reliable than the within-subject difference score built from them, but several of those difference scores — the blocked H&amp;F design, the Enkavi Simon task, and (most strikingly) the Enkavi Stroop and ANT Flanker tasks — retain moderate reliability rather than collapsing outright. The mechanism is exactly the one <span class="citation" data-cites="hedge2018reliability">Hedge et al. (<a href="#ref-hedge2018reliability" role="doc-biblioref">2018</a>)</span> describe: the two conditions are highly correlated across people, so most of their between-person variance cancels in the subtraction (<a href="#eq-vardiff" class="quarto-xref">Equation&nbsp;1</a>), while trial-level noise does not. <span class="citation" data-cites="enkavi2019">Enkavi et al. (<a href="#ref-enkavi2019" role="doc-biblioref">2019</a>)</span>’s own analysis of a much broader task battery reaches the same conclusion by a different route, which is reassuring convergent evidence that this isn’t an artifact of our specific pipeline.</p>
<p><strong>The size of the collapse varies far more than its direction.</strong> Every congruency-style dataset here (i.e., excluding the stop-signal exception) shows the qualitative pattern, but RT difference-score reliability spans roughly .04 to .69 depending on the task, sample, and design — not a fixed “paradox constant.” The Enkavi tasks, run in a larger, adult, Amazon Mechanical Turk sample, generally retained more difference-score reliability than the mixed-trial H&amp;F or alcohol Stroop datasets did, though we can’t cleanly separate sample effects from task effects with only one dataset per task. Researchers relying on a congruency-style contrast score for individual-differences work should treat this as a genuinely task-and-sample-specific empirical question, not something to be predicted from task family alone.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p><strong>This is a property of difference-score designs, not a general statement about IRW data.</strong> Most IRW tables are fixed-item-bank IRT designs, where ability is estimated from many items measuring one construct rather than subtracted between two conditions — the mechanism demonstrated here doesn’t apply to them, and this vignette should not be read as evidence that IRW data are broadly unreliable for individual-differences work. It applies specifically to trial-level tasks that measure an effect as a within-subject contrast between two positively-correlated conditions, which in the current IRW warehouse means Hearts &amp; Flowers, the alcohol Stroop, the matzke-etal-2019 stop-signal task, and the enkavi_2019_stroop, enkavi_2019_simon, and enkavi_2019_ant_flanker tasks (plus, presumably, any future task with the same congruent/incongruent or go/no-go structure — including the five other Enkavi et al.&nbsp;2019 tasks noted in Data and methods as candidates for a future extension).</p>
<p><strong>The blocked-vs-mixed-trial finding is worth follow-up.</strong> That H&amp;F’s blocked design retains more difference-score reliability than its trial-intermixed mixed block is consistent with the variance-shrinkage mechanism, but we only have one task to check it in — none of the Enkavi tasks offer a blocked/mixed contrast of the same kind. If it holds up in other tasks, it would suggest a practical mitigation for researchers who need an individual-differences difference score badly enough to trade away some ecological validity: block, don’t intermix.</p>
<p><strong>The stop-signal analogue needs a real SSRT, not this vignette’s naive substitute.</strong> We used failed-stop RT in place of Hedge et al.’s race-model SSRT purely to keep a go/no-go-family task in the comparison with the tools already used elsewhere in this vignette. A proper <code>matzke-etal-2019</code> replication attempt should use the integration method for SSRT (as Hedge et al.&nbsp;recommend) rather than this shortcut.</p>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">Reproducibility</h2>
<p>Results were computed on July 17, 2026. To regenerate:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Re-run the compute script (from the project root)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"vignettes/hf_reliability_compute.R"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Re-render this page</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>quarto<span class="sc">::</span><span class="fu">quarto_render</span>(<span class="st">"vignettes/hf_reliability_paradox.qmd"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
</section>
<section id="references" class="level2">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-imps2025_hf" class="csl-entry" role="listitem">
DeJoseph, M. L., A. Merculief, M. J. Sulik, and J. Obradović. 2025. <span>“Understanding Learning Variability in Early Childhood: An Equity-Centered Assessment of Cognitive Regulation Among Diverse Preschool Children.”</span> <em>Early Education and Development</em>, 1–25. <a href="https://doi.org/10.1080/10409289.2025.2578816">https://doi.org/10.1080/10409289.2025.2578816</a>.
</div>
<div id="ref-enkavi2019" class="csl-entry" role="listitem">
Enkavi, A. Zeynep, Ian W. Eisenberg, Patrick G. Bissett, et al. 2019. <span>“Large-Scale Analysis of Test–Retest Reliabilities of Self-Regulation Measures.”</span> <em>Proceedings of the National Academy of Sciences</em> 116 (12): 5472–77. <a href="https://doi.org/10.1073/pnas.1818430116">https://doi.org/10.1073/pnas.1818430116</a>.
</div>
<div id="ref-matzke-etal-2019" class="csl-entry" role="listitem">
He, Jason L., Rebecca J. Hirst, Rohan Puri, et al. 2021. <span>“OSARI, an Open-Source Anticipated Response Inhibition Task.”</span> <em>Behavior Research Methods</em> 54 (3): 1530–40. <a href="https://doi.org/10.3758/s13428-021-01680-9">https://doi.org/10.3758/s13428-021-01680-9</a>.
</div>
<div id="ref-hedge2018reliability" class="csl-entry" role="listitem">
Hedge, Craig, Georgina Powell, and Petroc Sumner. 2018. <span>“The Reliability Paradox: <span>W</span>hy Robust Cognitive Tasks Do Not Produce Reliable Individual Differences.”</span> <em>Behavior Research Methods</em> 50 (3): 1166–86. <a href="https://doi.org/10.3758/s13428-017-0935-1">https://doi.org/10.3758/s13428-017-0935-1</a>.
</div>
<div id="ref-alcoholstroop_jones2024" class="csl-entry" role="listitem">
Jones, Andrew, Elena Petrovskaya, and Tom Stafford. 2024. <span>“Exploring the Multiverse of Analysis Options for the Alcohol Stroop.”</span> <em>Behavior Research Methods</em> 56 (4): 3578–88. <a href="https://doi.org/10.3758/s13428-024-02377-5">https://doi.org/10.3758/s13428-024-02377-5</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/itemresponsewarehouse\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>