<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>rca_cca_feasibility – Item Response Warehouse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a4aace43a0bb780eb35e26eaacb6ac4f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-NM0Y0TP4RY"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-NM0Y0TP4RY', { 'anonymize_ip': true});
</script>


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Item Response Warehouse</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Data</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data">    
        <li>
    <a class="dropdown-item" href="../overview.html">
 <span class="dropdown-text">Overview of IRW Data Standards</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data.html">
 <span class="dropdown-text">Browse the IRW Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../collections.html">
 <span class="dropdown-text">Browse IRW Collections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../metadata.html">
 <span class="dropdown-text">Metadata for IRW tables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tags_quality.html">
 <span class="dropdown-text">Tag Quality</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../docs.html">
 <span class="dropdown-text">Data Documentation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../itemtext.html">
 <span class="dropdown-text">Item Text Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../itemtext_desc.html">
 <span class="dropdown-text">Item Text Descriptives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../itemtext_issues.html">
 <span class="dropdown-text">Known Issues</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../itemtext_merge.html">
 <span class="dropdown-text">Merging with IRW data</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../standard.html">
 <span class="dropdown-text">The Core IRW Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../comps_standard.html">
 <span class="dropdown-text">The Competition Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../nominal_standard.html">
 <span class="dropdown-text">The Nominal Data Standard</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../simsyn.html">
 <span class="dropdown-text">Simulated and Synthetic Data</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../contribute.html">
 <span class="dropdown-text">Contributing Data to the IRW</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-get-started" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Get Started</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-get-started">    
        <li>
    <a class="dropdown-item" href="../getstarted.html">
 <span class="dropdown-text">Getting Started</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../agents.html">
 <span class="dropdown-text">Using an AI Assistant</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../training.html">
 <span class="dropdown-text">Training Resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../problems.html">
 <span class="dropdown-text">Problem Set Examples</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/index.html"> 
<span class="menu-text">Vignettes</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../about.html">
 <span class="dropdown-text">About the IRW</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../research.html">
 <span class="dropdown-text">Research!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../othersites.html">
 <span class="dropdown-text">Related data resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../contact.html">
 <span class="dropdown-text">Contact Us</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/itemresponsewarehouse/misc/tree/main/data">
 <span class="dropdown-text">Data processing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://itemresponsewarehouse.github.io/Rpkg/">
 <span class="dropdown-text">irw: R package for managing IRW data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="scouting-report-rcacca-algorithm-selection-vignette-on-irw-data" class="level1">
<h1>Scouting report: RCA/CCA algorithm-selection vignette on IRW data</h1>
<p><strong>Date:</strong> 2026-08-27 <strong>Scope:</strong> feasibility scouting only. No vignette code was written and no models were fitted beyond the Task 4 pilots. <strong>Reference:</strong> Sotoudeh &amp; DiMaggio (2021), “Coping With Plenitude,” <em>Sociological Methods &amp; Research</em> 52(4):1838–1882, doi:10.1177/00491241211031273.</p>
<hr>
<section id="recommendation-no-go-on-the-corpus-scale-vignette" class="level2">
<h2 class="anchored" data-anchor-id="recommendation-no-go-on-the-corpus-scale-vignette">Recommendation: NO-GO on the corpus-scale vignette</h2>
<p>Three of the four thresholds pass. The one that fails is the one that decides whether the vignette has a subject.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Threshold</th>
<th>Verdict</th>
<th>Evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Corpus size — ≥60 single tables <strong>or</strong> ≥25 verified merge groups</td>
<td><strong>MET</strong></td>
<td>584 eligible tables (9.7× the bar); 114 merge groups (4.6× the bar)</td>
</tr>
<tr class="even">
<td>2</td>
<td>Feature spread — ≥5 meta-features whose IRW IQR exceeds the Table 9 range</td>
<td><strong>MISSED</strong></td>
<td><strong>0 of 13</strong> comparable features. The lone nominal pass (<code>PercentOut</code>) is a scale artifact</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Non-degeneracy — &gt;1 substantive class on a majority of tables, not explained by reverse-keying</td>
<td><strong>MET</strong></td>
<td>0 runs with k=1, 0 with a class &gt;75%, 19/19 with ≥2 substantive classes; reverse-key η² median 0.154</td>
</tr>
<tr class="even">
<td>4</td>
<td>Compute — full run tractable</td>
<td><strong>MET</strong></td>
<td>~9.3 h single-core, ~1.2 h on 8 cores</td>
</tr>
</tbody>
</table>
<p><strong>Unresolved:</strong> <code>id</code>-comparability verified on 4 of 114 merge groups; ANES licensing terms; Online Appendix E.</p>
<section id="why-threshold-2-is-decisive" class="level3">
<h3 class="anchored" data-anchor-id="why-threshold-2-is-decisive">Why threshold 2 is decisive</h3>
<p>The vignette’s premise was that Sotoudeh &amp; DiMaggio’s regressions extrapolate because nine GSS/ANES modules occupy a narrow band of the simulated feature space, and that hundreds of real datasets could characterize the empirical manifold directly instead. That premise requires IRW to <em>spread</em> across the feature space where their nine datasets do not.</p>
<p>It does not. Across 29 pilot matrices, <strong>not one comparable meta-feature has an interquartile range exceeding the full range of their nine datasets.</strong> IRW reaches further at the extremes — its full range beats theirs on 11 of 14 features — but its middle is tightly packed. IRW is overwhelmingly Likert self-report (2,003 of 2,435 tagged tables), and it shows: the corpus populates the <em>same</em> narrow region their nine datasets occupy, just more densely, with a thin tail of atypical tables (the 101-category rating scales) doing all the range-stretching.</p>
<p>Characterizing the empirical manifold with 584 IRW tables would therefore mostly re-confirm where the manifold already is. There is no prediction problem to solve, because there is no meaningful variation in the predictors. More datasets in the same place does not fix extrapolation.</p>
<p>The merge path does not rescue this. Merging <em>raises</em> mean person-correlation (0.18 → 0.36) and <em>lowers</em> proportional intrinsic dimensionality — it manufactures block structure rather than the heterogeneous covariance RCA is designed to find.</p>
</section>
<section id="what-the-scouting-run-does-support" class="level3">
<h3 class="anchored" data-anchor-id="what-the-scouting-run-does-support">What the scouting run does support</h3>
<p>Two smaller, defensible things, offered as observations rather than a redesign:</p>
<ol type="1">
<li><p><strong>A methods-critique note.</strong> The artifact chain is a personal Google Drive folder with no DOI. <code>evaluate.metafeatures()</code> has a hardcoded <code>num_vars = 10</code> that silently corrupts two of fourteen features on any matrix that is not ten items wide; <code>OverallRightKurt</code> takes the kurtosis of a logical vector while the evidently-intended helper sits defined and uncalled; Louvain is hardcoded despite the paper conceding the choice was consequential; and Table 9’s <code>PercentOut</code> column is on a different scale than the function that supposedly produced it. These are checkable claims about a published method, and they are the most solid findings here.</p></li>
<li><p><strong>GSS ingestion, independent of the vignette.</strong> None of the nine modules is in IRW. Eight are blocked by one NORC licensing question, and IRW already carries 106 tables under <code>Permission via Email</code> — so the path exists and has been walked before. One email covers all eight.</p></li>
</ol>
<p>Per the brief, I am not proposing a reshaped vignette. Threshold 2 failed on the merits and the corpus-scale version should be reported as not viable.</p>
<hr>
</section>
</section>
<section id="task-1-repo-reconnaissance" class="level2">
<h2 class="anchored" data-anchor-id="task-1-repo-reconnaissance">Task 1 — Repo reconnaissance</h2>
<section id="the-github-repo-is-a-stub" class="level3">
<h3 class="anchored" data-anchor-id="the-github-repo-is-a-stub">The GitHub repo is a stub</h3>
<p><code>https://github.com/raminasotoudeh/coping_with_plenitude</code> contains <strong>one file</strong>: a 1.2 KB <code>README.md</code>. Single branch (<code>main</code>, <code>a617939</code>). No code, no data.</p>
<p>The README redirects to a public Google Drive folder (<code>1TxvPMWHjX-ZK1Ih0IRX-FvRNFNmxMmcc</code>), stating the files were moved there because of GitHub file-size limits. That folder is <strong>not listed by the Drive API</strong> for an unauthenticated caller and the <code>claude.ai</code> Drive connector returns nothing for it, but the folder’s HTML listing embeds the file IDs, and each file downloads over <code>drive.usercontent.google.com</code>.</p>
<p>The folder holds <strong>six</strong> files, not the four the README describes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Size</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>metafeature_RCA.R</code></td>
<td>15.6 KB</td>
<td>retrieved — the main file</td>
</tr>
<tr class="even">
<td><code>f_outer.cpp</code></td>
<td>1.0 KB</td>
<td>retrieved — Rcpp helpers</td>
</tr>
<tr class="odd">
<td><code>recursive_relationality.R</code></td>
<td>2.0 KB</td>
<td>retrieved — standalone duplicate of the recursive path</td>
</tr>
<tr class="even">
<td><code>squared_RCA.R</code></td>
<td>2.6 KB</td>
<td>retrieved</td>
</tr>
<tr class="odd">
<td><code>metafeature_models_cleaned.RDS</code></td>
<td>~40 KB unpacked</td>
<td>retrieved (fitted meta-feature regressions)</td>
</tr>
<tr class="even">
<td><code>models_w_noise.RDS</code></td>
<td>large</td>
<td><strong>NOT retrieved</strong> — download timed out; see Open items</td>
</tr>
</tbody>
</table>
<p><strong>Implication for reproducibility:</strong> the paper’s artifact chain runs through a personal Google Drive folder with no DOI, no versioning, and no guarantee of persistence. Anything built on it should vendor its own copy of these files.</p>
</section>
<section id="the-ten-distance-measures" class="level3">
<h3 class="anchored" data-anchor-id="the-ten-distance-measures">The ten distance measures</h3>
<p>All measures are implemented in <strong><code>metafeature_RCA.R</code></strong>, in <strong>plain R</strong>, dispatched from a single function <code>metaRCA(data, measure = ...)</code>. They are <strong>not entangled with the simulation harness</strong> — <code>metaRCA()</code> takes a bare data matrix and returns a membership vector. Portability is good.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Measure in brief</th>
<th>Implemented as</th>
<th>Backing code</th>
<th>Portable?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>eJaccard</code></td>
<td><code>proxy::simil(method="eJaccard")</code></td>
<td>CRAN <code>proxy</code></td>
<td>yes</td>
</tr>
<tr class="even">
<td><code>Podani</code></td>
<td><code>proxy::simil(method="Podani")</code></td>
<td>CRAN <code>proxy</code></td>
<td>yes</td>
</tr>
<tr class="odd">
<td><code>eDice</code></td>
<td><code>proxy::simil(method="eDice")</code></td>
<td>CRAN <code>proxy</code></td>
<td>yes</td>
</tr>
<tr class="even">
<td><code>cosine</code></td>
<td><code>proxy::simil(method="Cosine")</code></td>
<td>CRAN <code>proxy</code></td>
<td>yes</td>
</tr>
<tr class="odd">
<td><code>Euclidean</code></td>
<td><code>proxy::simil(method="Euclidean")</code></td>
<td>CRAN <code>proxy</code></td>
<td>yes</td>
</tr>
<tr class="even">
<td><code>correlation</code></td>
<td><code>corr.dist()</code> + <code>filter.insignif()</code></td>
<td>local, self-contained</td>
<td>yes</td>
</tr>
<tr class="odd">
<td><code>ACE</code></td>
<td><code>ace.dist()</code> → <code>acepack::ace()$rsq</code></td>
<td>CRAN <code>acepack</code></td>
<td>yes</td>
</tr>
<tr class="even">
<td><code>original relationality</code></td>
<td><code>rca.dist()</code> → <code>relationality()</code></td>
<td>local, pure R, O(n²) double loop</td>
<td>yes, but slow</td>
</tr>
<tr class="odd">
<td><code>new relationality</code> (a.k.a. Recursive Relationality — the paper’s headline measure)</td>
<td><code>recursive.rca.dist()</code> → <code>relationalityC()</code></td>
<td><strong>Rcpp</strong>, <code>f_outer.cpp</code></td>
<td>yes</td>
</tr>
<tr class="even">
<td>pairwise-voting ensemble</td>
<td><code>dyadic_vote_ensemble()</code></td>
<td>local, self-contained</td>
<td>yes</td>
</tr>
</tbody>
</table>
<p>Notes that matter for porting:</p>
<ul>
<li><code>f_outer.cpp</code> defines <strong>both</strong> <code>f_outer</code> (pairwise differences) <strong>and</strong> <code>relationalityC</code>. The recursive path is complete — no missing symbol. It compiles under Rcpp 1.1.2 without modification.</li>
<li>Each measure has <strong>bespoke post-processing</strong> inside <code>metaRCA()</code> that is easy to miss and not documented in the paper: the <code>proxy</code>-family measures get median-centred (except Cosine); <code>eJaccard</code>/<code>Cosine</code>/<code>eDice</code> get an extra “oca rescale” (<code>x - median(min(x):max(x))</code>) applied first; Cosine is hard-thresholded at its 75th percentile; Original Relationality is thresholded at 0.05; Recursive Relationality is <strong>squared</strong> rather than absolute-valued. Reimplementing “just the distance measure” without this block will not reproduce their results.</li>
<li><code>filter.insignif()</code> is applied only to Correlation (p&lt;0.05) and ACE (p&lt;0.10). Two different cutoffs, unexplained.</li>
</ul>
</section>
<section id="community-detection-a-real-and-undocumented-degree-of-freedom" class="level3">
<h3 class="anchored" data-anchor-id="community-detection-a-real-and-undocumented-degree-of-freedom">Community detection — a real and undocumented degree of freedom</h3>
<p><code>metaRCA()</code> <strong>hardcodes <code>igraph::cluster_louvain()</code></strong>. There is no argument to change it. This matches the paper’s own admission that swapping leading-eigenvector for Louvain accounted for a meaningful share of RCA’s measured improvement — but the shipped code does not expose the choice, so a user of <code>metaRCA()</code> silently gets Louvain regardless of what the rest of the RCA literature (and the CRAN <code>RCA</code> package) does.</p>
<p>Note also that <code>metaRCA()</code> has <strong>no bootstrap edge-pruning at all</strong>. The CRAN <code>RCA</code> package prunes edges by bootstrap (<code>RCA(matrix, num=1000, alpha=0.05)</code>); the paper’s pipeline substitutes an analytic t-test (<code>filter.insignif</code>) for two measures and no pruning for the rest. These are not the same algorithm, and timings from one do not transfer to the other.</p>
</section>
<section id="meta-feature-code-present-reusable-and-none-require-simulation-parameters" class="level3">
<h3 class="anchored" data-anchor-id="meta-feature-code-present-reusable-and-none-require-simulation-parameters">Meta-feature code: present, reusable, and none require simulation parameters</h3>
<p><code>evaluate.metafeatures(df, num_vars = 10)</code> is a <strong>pure function of the data matrix</strong>. It returns exactly <strong>14</strong> features, and they line up one-to-one with the 14 columns of Table 9. <strong>None of them require the simulation’s generative parameters</strong> — all are computable on real data. This is the single most reusable piece of the artifact.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Returned name</th>
<th>Table 9 column</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>OverallSD</code></td>
<td>Overall SD</td>
</tr>
<tr class="even">
<td><code>OverallKurt</code></td>
<td>Overall Kurtosis</td>
</tr>
<tr class="odd">
<td><code>OverallRightKurt</code></td>
<td>Overall Kurtosis of Right-tail</td>
</tr>
<tr class="even">
<td><code>VarColPC1</code></td>
<td>Variance of PC 1</td>
</tr>
<tr class="odd">
<td><code>SkewColPC1</code></td>
<td>Skewness of PC 1</td>
</tr>
<tr class="even">
<td><code>SkewColPC2</code></td>
<td>Skewness of PC 2</td>
</tr>
<tr class="odd">
<td><code>Skewness</code></td>
<td>Overall Skewness</td>
</tr>
<tr class="even">
<td><code>Mean_Row_Corr</code></td>
<td>Mean correlation of responses</td>
</tr>
<tr class="odd">
<td><code>Row_Corr_Kurtosis</code></td>
<td>Kurtosis of RCs</td>
</tr>
<tr class="even">
<td><code>CorrRightKurt</code></td>
<td>Kurtosis of right-tail of RCs</td>
</tr>
<tr class="odd">
<td><code>Mean_Col_Kurtosis</code></td>
<td>Average kurtosis of variables</td>
</tr>
<tr class="even">
<td><code>Mean_SD_Ratio</code></td>
<td>Mean SD Ratio</td>
</tr>
<tr class="odd">
<td><code>intrinsicDemnsionalityProp</code></td>
<td>Intrinsic Dimensionality</td>
</tr>
<tr class="even">
<td><code>PercentOut</code></td>
<td>Percent of Variables with Outlier Observations</td>
</tr>
</tbody>
</table>
<p>Three defects in this function that anyone reusing it must handle:</p>
<ol type="1">
<li><strong><code>num_vars</code> defaults to 10 and is never inferred from the data.</strong> It is the denominator of both <code>PercentOut</code> and <code>intrinsicDemnsionalityProp</code>. Calling <code>evaluate.metafeatures(x)</code> on a 30-item matrix silently produces two wrong features. We set <code>num_vars = ncol(df)</code>.</li>
<li><strong>An unseeded random column is injected</strong>: <code>df_new$class &lt;- sample(1:4, nrow(df_new), replace=TRUE)</code>, purely to satisfy <code>mfe::statistical()</code>’s formula interface. With <code>by.class=FALSE</code> the <code>nrOutliers</code> result should not depend on it, but the function is non-deterministic by construction. We set a seed.</li>
<li><strong><code>overall_right_kurt</code> computes the kurtosis of a logical vector</strong>: <code>Kurt(df &gt; mean(df))</code>. This is almost certainly a bug — the analogous <code>right_half_kurt</code> helper defined immediately above it (<code>Kurt(x[x &gt; mean(x)])</code>) is the evidently intended form, and it is <strong>defined but never called</strong>. We reproduced their line verbatim rather than silently repairing it, but Table 9’s <code>OverallRightKurt</code> column is therefore measuring the kurtosis of a Bernoulli indicator, not of the right tail of the response distribution. That column’s very low reported simulation overlap (3%) is consistent with it being a near-degenerate quantity.</li>
</ol>
<p><strong>Terminology correction for the brief:</strong> the brief lists “mean inter-item correlation” as a meta-feature. <code>Mean_Row_Corr</code> is <code>mean(cor(t(df)))</code> — the mean <strong>person-by-person</strong> correlation, which is the CCA similarity matrix itself, and Table 9 labels it “Mean correlation of responses.” There is no inter-<em>item</em> correlation feature in their set. We computed inter-item Pearson and polychoric analogues separately as supplementary columns; they are not substitutes for <code>Mean_Row_Corr</code>.</p>
</section>
<section id="the-nine-empirical-matrices-are-not-distributed" class="level3">
<h3 class="anchored" data-anchor-id="the-nine-empirical-matrices-are-not-distributed">The nine empirical matrices are NOT distributed</h3>
<p>Neither the GitHub repo nor the Drive folder contains the constructed GSS/ANES modules — only code and fitted models. <code>metafeature_RCA.R</code> loads <code>readstata13</code>, implying the authors worked from local <code>.dta</code> files that were never shipped. <strong>Reproducing their Table 9 exactly requires rebuilding the nine matrices from source data</strong>, which requires Online Appendix E (see Task 5).</p>
<hr>
</section>
</section>
<section id="task-2-corpus-eligibility" class="level2">
<h2 class="anchored" data-anchor-id="task-2-corpus-eligibility">Task 2 — Corpus eligibility</h2>
<p>Source: <code>irw_metadata()</code> (2,949 tables) joined to the <code>irw_meta</code> Redivis <code>tags</code> (2,435 rows) and <code>biblio</code> (3,688 rows) tables.</p>
<section id="marginal-counts" class="level3">
<h3 class="anchored" data-anchor-id="marginal-counts">Marginal counts</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Criterion</th>
<th>Tables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>density == 1</code></td>
<td>1,476</td>
</tr>
<tr class="even">
<td><code>n_categories &gt;= 3</code></td>
<td>2,385</td>
</tr>
<tr class="odd">
<td><code>n_categories &gt;= 4</code></td>
<td>2,263</td>
</tr>
<tr class="even">
<td><code>n_categories &gt;= 5</code></td>
<td>1,894</td>
</tr>
<tr class="odd">
<td><code>n_items</code> in 6–40</td>
<td>1,923</td>
</tr>
<tr class="even">
<td><code>n_participants &gt;= 300</code></td>
<td>2,093</td>
</tr>
</tbody>
</table>
</section>
<section id="sequential-attrition" class="level3">
<h3 class="anchored" data-anchor-id="sequential-attrition">Sequential attrition</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Remaining</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all IRW tables</td>
<td>2,949</td>
</tr>
<tr class="even">
<td><code>density == 1</code></td>
<td>1,476</td>
</tr>
<tr class="odd">
<td>+ <code>n_items</code> 6–40</td>
<td>1,017</td>
</tr>
<tr class="even">
<td>+ <code>n_participants &gt;= 300</code></td>
<td>694</td>
</tr>
<tr class="odd">
<td>+ <code>n_categories &gt;= 3</code></td>
<td>607</td>
</tr>
<tr class="even">
<td>+ <code>n_categories &gt;= 4</code></td>
<td><strong>584</strong></td>
</tr>
<tr class="odd">
<td>+ <code>n_categories &gt;= 5</code></td>
<td>491</td>
</tr>
</tbody>
</table>
<p>The <code>n_categories &gt;= 4</code> cutoff is cheap: it costs 23 tables relative to <code>&gt;= 3</code> and buys the argument against tied similarity matrices. Going to <code>&gt;= 5</code> costs a further 93. <strong>584</strong> is the headline single-table corpus.</p>
</section>
<section id="construct-split-584-eligible-not-filtered-on" class="level3">
<h3 class="anchored" data-anchor-id="construct-split-584-eligible-not-filtered-on">Construct split (584 eligible, not filtered on)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Tables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>affective/opinion (Opinion/attitude, Affective/mental health, Personality)</td>
<td>260</td>
</tr>
<tr class="even">
<td>cognitive (Cognitive/educational)</td>
<td>66</td>
</tr>
<tr class="odd">
<td>other (Behavioral, Physical health, Developmental, …)</td>
<td>39</td>
</tr>
<tr class="even">
<td><strong>untagged</strong> (no row in the tags sheet)</td>
<td><strong>219</strong></td>
</tr>
</tbody>
</table>
<p>219 of 584 eligible tables have no construct tag at all — 37%. Any claim in the vignette that splits results by construct type is really running on 365 tables, not 584.</p>
</section>
<section id="merge-eligible-groups" class="level3">
<h3 class="anchored" data-anchor-id="merge-eligible-groups">Merge-eligible groups</h3>
<p>Name prefixes are unreliable (<code>ffm_ext</code> and <code>bfi_goldberg_1992_extraversion</code> are the same study). <strong>DOI is populated for all 2,949 tables</strong> and is the better key.</p>
<p>Among the 584 eligible tables, 522 carry a usable DOI, spanning 249 distinct DOIs:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group size</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>≥2 eligible tables</td>
<td><strong>114 groups</strong> (387 tables)</td>
</tr>
<tr class="even">
<td>≥3 eligible tables</td>
<td>67 groups</td>
</tr>
<tr class="odd">
<td>≥2 <em>distinct</em> construct types</td>
<td>29 groups</td>
</tr>
</tbody>
</table>
<p>Largest groups run to 12 tables (<code>anunciacao_2025_personality_*</code>) and 10 (<code>bfi_goldberg_1992_*</code>). Substantively many are exactly what RCA wants — e.g.&nbsp;<code>alsuhibani_2022_*</code> spans paranoia, conspiracy beliefs, attachment, and locus of control.</p>
</section>
<section id="id-comparability-verified-merge-path-is-open" class="level3">
<h3 class="anchored" data-anchor-id="id-comparability-verified-merge-path-is-open"><code>id</code> comparability — VERIFIED, merge path is open</h3>
<p>Tested on 4 groups (12 tables fetched):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lorenz_2016</code> (hope / resilience / optimism)</td>
<td>321/321 shared — <strong>100%</strong></td>
</tr>
<tr class="even">
<td><code>jablonska_2020</code> (HADS / RSES / Instagram addiction)</td>
<td>974/974 — <strong>100%</strong></td>
</tr>
<tr class="odd">
<td><code>silva_2018</code> (BSQ / TFEQ / WHOQOL)</td>
<td><strong>100%</strong> (smaller table nests inside larger)</td>
</tr>
<tr class="even">
<td><code>alsuhibani_2022</code> (PADS / GCBS / LOC)</td>
<td>94–100% <em>within</em> sub-sample; <strong>0% across sub-samples</strong></td>
</tr>
</tbody>
</table>
<p><code>id</code> <strong>is</strong> stable across sibling tables from the same study. The <code>alsuhibani</code> case is the failure mode to guard against: that paper ran three separate sub-samples and ids are namespaced by sample (<code>1xxxxx</code> vs <code>2xxxxx</code>), so a naive DOI-keyed merge yields a matrix that is mostly missing. This is cheaply auto-detectable with exactly the pairwise-overlap test used here, so it is a filter to apply, not a blocker.</p>
<p><strong>Caveat on generality:</strong> verified on 4 of 114 groups. Verifying all 114 requires fetching ~387 tables, which was outside this run’s download budget. The check is cheap per group and should be run as a gate inside any real pipeline rather than assumed.</p>
<p><strong>Deliverables:</strong> <code>scouting/scout_eligible_tables.csv</code> (584 rows), <code>scouting/scout_merge_groups.csv</code> (114 rows).</p>
<hr>
</section>
</section>
<section id="task-3-meta-feature-pilot" class="level2">
<h2 class="anchored" data-anchor-id="task-3-meta-feature-pilot">Task 3 — Meta-feature pilot</h2>
<section id="what-was-run" class="level3">
<h3 class="anchored" data-anchor-id="what-was-run">What was run</h3>
<p>29 matrices: <strong>25 single tables</strong> (stratified on <code>n_categories</code> band × affective/cognitive tag — 18 affective/opinion, 7 cognitive) plus <strong>4 merged multi-construct matrices</strong>. Item counts 6–63, respondent counts 295–4,992.</p>
<p><code>evaluate.metafeatures()</code> was ported verbatim (<code>scouting/pilot_metafeatures.R</code>), with the three fixes noted in Task 1 (<code>num_vars = ncol</code>, seeded, <code>OverallRightKurt</code> left as-is).</p>
<p><strong>Design choices made without asking, per the brief:</strong></p>
<ul>
<li><code>num_vars = ncol(df)</code> rather than their hardcoded 10.</li>
<li>Respondents capped at <strong>N = 5,000</strong> per matrix (meta-features are stable well below this; <code>Mean_Row_Corr</code> is O(N²) to compute).</li>
<li>Tables with <strong>&gt; 50,000 respondents excluded</strong> from the sampling frame. This is a <em>download-cost</em> decision, not a statistical one — RCA subsamples to N=500 regardless. It removes 26 of 584 eligible tables (4.5%). The first draw pulled <code>ffm_csn</code> at 1,015,341 respondents, which alone stalled the fetch for 8 minutes.</li>
<li>Complete cases only; zero-variance rows dropped (819 rows across all 29 matrices; <strong>0 columns</strong> dropped).</li>
<li>Outliers: left as <code>mfe</code>’s Tukey-boxplot <code>nrOutliers</code>.</li>
<li>Polychoric via <code>psych::polychoric</code> default (two-step ML, continuity-corrected).</li>
</ul>
</section>
<section id="feature-spread-vs.-the-papers-nine-datasets-threshold-2-fails" class="level3">
<h3 class="anchored" data-anchor-id="feature-spread-vs.-the-papers-nine-datasets-threshold-2-fails">Feature spread vs.&nbsp;the paper’s nine datasets — THRESHOLD 2 FAILS</h3>
<p>The threshold asks for <strong>≥5 meta-features whose IRW IQR exceeds the Table 9 range</strong>. Result: <strong>1 of 14</strong>, and that one is an artifact.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>IRW IQR</th>
<th>IRW range</th>
<th>Table 9 range</th>
<th>IQR &gt; T9 range?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OverallKurt</td>
<td>0.821</td>
<td>8.472</td>
<td>2.300</td>
<td>no</td>
</tr>
<tr class="even">
<td>OverallRightKurt</td>
<td>0.120</td>
<td>0.902</td>
<td>1.061</td>
<td>no</td>
</tr>
<tr class="odd">
<td>OverallSD</td>
<td>0.756</td>
<td>26.51</td>
<td>1.597</td>
<td>no</td>
</tr>
<tr class="even">
<td>Skewness</td>
<td>0.396</td>
<td>3.741</td>
<td>1.312</td>
<td>no</td>
</tr>
<tr class="odd">
<td>VarColPC1</td>
<td>17.35</td>
<td>2141</td>
<td>46.65</td>
<td>no</td>
</tr>
<tr class="even">
<td>SkewColPC1</td>
<td>0.466</td>
<td>2.678</td>
<td>1.629</td>
<td>no</td>
</tr>
<tr class="odd">
<td>SkewColPC2</td>
<td>0.340</td>
<td>1.266</td>
<td>2.063</td>
<td>no</td>
</tr>
<tr class="even">
<td>Mean_Row_Corr</td>
<td>0.168</td>
<td>0.654</td>
<td>0.564</td>
<td>no</td>
</tr>
<tr class="odd">
<td>Row_Corr_Kurtosis</td>
<td>0.551</td>
<td>2.404</td>
<td>3.939</td>
<td>no</td>
</tr>
<tr class="even">
<td>CorrRightKurt</td>
<td>0.704</td>
<td>11.45</td>
<td>2.672</td>
<td>no</td>
</tr>
<tr class="odd">
<td>Mean_Col_Kurtosis</td>
<td>0.850</td>
<td>8.664</td>
<td>3.607</td>
<td>no</td>
</tr>
<tr class="even">
<td>Mean_SD_Ratio</td>
<td>0.071</td>
<td>0.456</td>
<td>0.436</td>
<td>no</td>
</tr>
<tr class="odd">
<td>intrinsicDemnsionalityProp</td>
<td>0.096</td>
<td>0.389</td>
<td>0.371</td>
<td>no</td>
</tr>
<tr class="even">
<td><strong>PercentOut</strong></td>
<td><strong>43.33</strong></td>
<td>100.0</td>
<td>0.048</td>
<td><strong>yes</strong></td>
</tr>
</tbody>
</table>
<p><strong>The single pass is spurious.</strong> IRW <code>PercentOut</code> spans 0–100; Table 9’s spans 0.000–0.048. Their own code computes <code>(nrOut/num_vars)*100</code>, which for a <em>count</em> of outlier-bearing variables can never land at 0.004. Table 9’s column is on a different scale than the function that supposedly produced it. The two numbers are not comparable, so this feature cannot count toward the threshold. <strong>Comparable features passing: 0 of 13.</strong></p>
</section>
<section id="but-the-picture-is-more-interesting-than-a-flat-fail" class="level3">
<h3 class="anchored" data-anchor-id="but-the-picture-is-more-interesting-than-a-flat-fail">But the picture is more interesting than a flat fail</h3>
<p>The threshold compares an <strong>IQR</strong> (middle 50% of 29 matrices) against a <strong>full range</strong> (all 9 of theirs) — an inherently demanding test. On the like-for-like comparison, IRW is clearly wider:</p>
<p><strong>IRW full range exceeds the Table 9 range on 11 of 14 features</strong> (all but <code>OverallRightKurt</code>, <code>SkewColPC2</code>, <code>Row_Corr_Kurtosis</code>).</p>
<p>So: <strong>the IRW slice reaches further than nine GSS modules on most features, but its middle is tightly clustered.</strong> Most IRW tables look like each other — unsurprising, since IRW is overwhelmingly Likert self-report (2,003 of 2,435 tagged tables are “Likert Scale/selected response”). The range is stretched by a handful of atypical tables, notably the wide-category ones: <code>test_taking_much_2025_cm</code> (101 categories, OverallSD 18.9, VarColPC1 2,144) and <code>climatechange_geiger_2025</code> (OverallSD 27.3), which are IRW’s analogues to their Occupational Prestige outlier.</p>
<p>That is a real finding for the vignette’s premise: <strong>IRW does not densely populate a wider manifold; it populates the same narrow region more thickly, with a thin tail of unusual tables.</strong> Characterizing the empirical manifold “directly instead of assuming it” would mostly re-confirm where the manifold already is.</p>
</section>
<section id="degenerate-misbehaving-features" class="level3">
<h3 class="anchored" data-anchor-id="degenerate-misbehaving-features">Degenerate / misbehaving features</h3>
<p>None were undefined or constant — all 14 returned finite, distinct values on all 29 matrices. Specific concerns:</p>
<ul>
<li><strong><code>PercentOut</code></strong> — not degenerate but not comparable to theirs (above). Also lumpy: it is a count over <code>ncol</code>, so on a 9-item matrix it can only take 10 values, and 2 of 29 matrices sat at exactly 0 and 4 at exactly 100.</li>
<li><strong><code>intrinsicDemnsionalityProp</code></strong> — only <strong>21 distinct values across 29 matrices</strong>. It is a small integer over <code>ncol</code>, so it is coarse by construction. Fine as a covariate, poor as a continuous predictor.</li>
<li><strong><code>OverallRightKurt</code></strong> — the narrowest feature (IRW range 0.902, IQR 0.120) and the one whose definition is a probable bug (kurtosis of a logical). Its low variance in both the simulations and IRW is consistent with it carrying little information.</li>
<li><strong><code>Mean_InterItem_Polychoric</code></strong> (supplementary) — <strong>failed on 5 of 29 matrices</strong>, with <code>psych::polychoric</code> warning about unequal category counts and cells adjusted for zero counts. On merged multi-construct matrices, where sub-scales have different response formats, the polychoric analogue is unreliable. Pearson inter-item was computable everywhere (range −0.026 to 0.613). <strong>Recommendation: use Pearson.</strong></li>
</ul>
</section>
<section id="merged-vs.-single" class="level3">
<h3 class="anchored" data-anchor-id="merged-vs.-single">Merged vs.&nbsp;single</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Mean_Row_Corr</th>
<th>intrinsicDimProp</th>
<th>VarColPC1</th>
<th>OverallSD</th>
<th>PercentOut</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>merged (n=4)</td>
<td>0.356</td>
<td>0.24</td>
<td>13.24</td>
<td>1.472</td>
<td>60.8</td>
</tr>
<tr class="even">
<td>single (n=25)</td>
<td>0.178</td>
<td>0.30</td>
<td>10.12</td>
<td>1.392</td>
<td>35.9</td>
</tr>
</tbody>
</table>
<p>Merging <strong>doubles</strong> mean person-correlation (0.18 → 0.36) and <em>lowers</em> proportional intrinsic dimensionality. Both point the same way: stacking sub-scales that share a respondent sample creates strong block structure, which raises overall person-similarity rather than creating the heterogeneous covariance patterns RCA is meant to detect. Merging is mechanically easy and substantively <strong>not obviously</strong> the fix the vignette premise assumes.</p>
<p><strong>Deliverables:</strong> <code>scouting/scout_metafeatures.csv</code> (29 rows × 14 features + supplements), <code>scouting/scout_feature_spread.csv</code>, <code>scouting/table9.csv</code> (their Table 9, transcribed).</p>
<hr>
</section>
</section>
<section id="task-4-non-degeneracy-and-timing" class="level2">
<h2 class="anchored" data-anchor-id="task-4-non-degeneracy-and-timing">Task 4 — Non-degeneracy and timing</h2>
<p>Five pilot tables at N = 500, spanning 12–40 items, each run through three algorithms: <strong>RCA</strong> (CRAN <code>RCA</code>, with the bootstrap edge-pruning step, <code>num=1000, alpha=0.05</code>), <strong>CCA</strong> (<code>corclass::cca</code>, significance-filtered), and <strong>Recursive Relationality</strong> (the paper’s own headline measure, lifted from <code>metafeature_RCA.R</code>).</p>
<section id="non-degeneracy-threshold-3-met" class="level3">
<h3 class="anchored" data-anchor-id="non-degeneracy-threshold-3-met">Non-degeneracy — THRESHOLD 3 MET</h3>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>runs returning results</td>
<td>19</td>
</tr>
<tr class="even">
<td>runs with <strong>k = 1</strong></td>
<td><strong>0</strong></td>
</tr>
<tr class="odd">
<td>runs with largest class <strong>&gt; 90%</strong></td>
<td><strong>0</strong></td>
</tr>
<tr class="even">
<td>runs with largest class &gt; 75%</td>
<td>0</td>
</tr>
<tr class="odd">
<td>runs with ≥2 substantive classes (≥5% of N)</td>
<td><strong>19 of 19</strong></td>
</tr>
</tbody>
</table>
<p>No degeneracy. Largest class across all runs peaked at 66.6%, and every single run recovered at least two substantive classes. RCA and CCA both routinely return many tiny classes on top of a few real ones (RCA median k = 10, median substantive k = 3), which is why the “substantive” count matters more than raw k.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>median secs</th>
<th>median k</th>
<th>median substantive k</th>
<th>median largest</th>
<th>median reverse-key η²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CCA (corclass)</td>
<td>0.1</td>
<td>4</td>
<td>3</td>
<td>0.436</td>
<td>0.154</td>
</tr>
<tr class="even">
<td>RCA (bootstrap num=1000)</td>
<td>81.8</td>
<td>10</td>
<td>3</td>
<td>0.426</td>
<td>0.301</td>
</tr>
<tr class="odd">
<td>Recursive Relationality</td>
<td>90.5</td>
<td>4</td>
<td>4</td>
<td>0.328</td>
<td>0.242</td>
</tr>
</tbody>
</table>
</section>
<section id="reverse-keying-diagnostic-passes-but-not-comfortably" class="level3">
<h3 class="anchored" data-anchor-id="reverse-keying-diagnostic-passes-but-not-comfortably">Reverse-keying diagnostic — passes, but not comfortably</h3>
<p>Median η² = <strong>0.154</strong>: about a sixth of recovered class variance is explained by nothing more than whether a respondent agrees with the sign of the first principal component’s loadings. <strong>3 of 19</strong> runs exceeded 0.5 (<code>short_dark_triad</code> under CCA at 0.624; <code>hexaco_ashton_2014_h</code> under Recursive Relationality at 0.611; <code>MERGED_jablonska_2020</code> under RCA at 0.510).</p>
<p>So the diagnostic does <strong>not</strong> explain <em>most</em> of the structure, and the threshold is met as written. But a quarter is not a rounding error, and the worst cases are bad. Reported plainly: <strong>the classes are not merely careless-responder artifacts, but a meaningful minority of the signal is polarity agreement</strong>, and any real vignette would need this diagnostic as a standing control, not a one-off check.</p>
<p><strong>The merged matrix is worse, not better.</strong> On <code>MERGED_jablonska_2020</code> (46 items, 5 sub-scales sharing a respondent sample), RCA returned η² = <strong>0.510</strong> — the highest RCA value observed, and above the 0.5 line. CCA on the same matrix went the other way (η² = 0.014) but collapsed to just 2 substantive classes with 52% of respondents in the largest. This is the same warning Task 3’s meta-features gave from the other direction: stacking sub-scales creates strong block structure, and the algorithms respond to it by tracking response polarity rather than finding heterogeneous covariance patterns. <strong>The merge path — the thing that would have made the corpus-scale version viable — is the configuration where the substantive premise looks weakest.</strong></p>
</section>
<section id="timing-and-scaling-threshold-4-met" class="level3">
<h3 class="anchored" data-anchor-id="timing-and-scaling-threshold-4-met">Timing and scaling — THRESHOLD 4 MET</h3>
<p>Wall-clock at N = 500, showing the dominant cost:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Table</th>
<th>items</th>
<th>RCA (w/ bootstrap)</th>
<th>CCA</th>
<th>Recursive Relationality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>heard_roch_2022_idss</td>
<td>12</td>
<td>23.1 s</td>
<td>0.11 s</td>
<td>7.0 s</td>
</tr>
<tr class="even">
<td>pppasbpnssedaisw_pedro_2022_panas</td>
<td>20</td>
<td>54.9 s</td>
<td>0.22 s</td>
<td>50.9 s</td>
</tr>
<tr class="odd">
<td>disgust_berger2014</td>
<td>25</td>
<td>81.8 s</td>
<td>0.10 s</td>
<td>130.1 s</td>
</tr>
<tr class="even">
<td>short_dark_triad</td>
<td>27</td>
<td>95.6 s</td>
<td>0.13 s</td>
<td>not attempted</td>
</tr>
<tr class="odd">
<td>hexaco_ashton_2014_h</td>
<td>40</td>
<td>200.8 s</td>
<td>0.19 s</td>
<td><strong>835.0 s</strong></td>
</tr>
</tbody>
</table>
<p><strong>Recursive Relationality is O(N²·p⁴) in item count</strong> — confirmed empirically, with <code>secs / p⁴</code> constant at 3.3e-4, 2.6e-4, 3.3e-4, 3.3e-4 across the four item counts. It builds a doubly-recursive difference vector of length <code>C(C(p,2),2)</code> per respondent, so item count, not sample size, is the binding constraint. RCA’s bootstrap scales roughly as p² (<code>secs/p²</code> ≈ 0.13 throughout). CCA is effectively free.</p>
<p><strong>The N-scaling check is weak and should not be leaned on.</strong> The brief asked for a rerun at N = 1000. <code>heard_roch_2022_idss</code> has only <strong>574</strong> usable respondents after complete-case and zero-variance filtering, so what actually ran was 500 → 574, a 15% increase rather than a doubling. Over that narrow range: RCA 23.1 → 28.4 s, Recursive Relationality 7.0 → 9.5 s. The recursive ratio (1.35× time for 1.15× N) is consistent with O(N²), but the range is far too short to confirm it. Class recovery was stable across the two sizes (k = 5 → 4, largest 0.286 → 0.324, η² 0.058 → 0.066), which is mildly reassuring about sampling stability. <strong>A real N-scaling curve was not established.</strong></p>
<p><strong>Full-run estimate — 100 tables × 10 measures × 3 replicates at N = 500</strong>, costed against the actual item-count distribution of the 584 eligible tables (median 11 items, IQR 8–20) rather than a single representative table:</p>
<ul>
<li>Recursive Relationality: ~1.85 h per replicate</li>
<li>RCA with bootstrap: ~1.04 h per replicate</li>
<li>8 remaining measures at ~1 s each: ~0.6 h total</li>
<li><strong>Total ≈ 9.3 hours single-core, ≈ 1.2 hours on 8 cores.</strong> Tractable.</li>
</ul>
<p>The caveat that matters more than the total: <strong>cost is entirely tail-driven.</strong> A 40-item table costs 42 minutes for its 3 recursive replicates; an 11-item table costs 15 seconds — a 175× spread. Only 8.4% of eligible tables have ≥30 items, but they would dominate the bill. Cap item count or budget the tail explicitly.</p>
<p><strong>Deliverable:</strong> <code>scouting/scout_task4.csv</code>.</p>
<hr>
</section>
</section>
<section id="task-5-source-data-scout-for-irw-ingestion" class="level2">
<h2 class="anchored" data-anchor-id="task-5-source-data-scout-for-irw-ingestion">Task 5 — Source-data scout for IRW ingestion</h2>
<section id="is-any-of-it-already-in-irw" class="level3">
<h3 class="anchored" data-anchor-id="is-any-of-it-already-in-irw">Is any of it already in IRW?</h3>
<p>Searched <code>table</code>, <code>doi</code>, <code>reference</code>, <code>construct_name</code> and <code>measurement_tool</code> across all 2,949 tables.</p>
<ul>
<li><strong>GSS: zero hits.</strong> No match on “General Social Survey”, “GSS”, or “NORC”. None of the eight GSS modules is in IRW.</li>
<li><strong>ANES: one hit,</strong> <code>polca_election</code> — but its description points to the <strong>2000</strong> National Election Studies, not the 2012 ANES the paper uses. Not the same data.</li>
<li>No hits for “Boutyline”, “DiMaggio”, “music taste”, or “occupational prestige”.</li>
</ul>
<p>So <strong>none of the nine modules is currently in IRW</strong>, and all nine are candidates on their own merits.</p>
</section>
<section id="licensing-this-is-the-blocker" class="level3">
<h3 class="anchored" data-anchor-id="licensing-this-is-the-blocker">Licensing — this is the blocker</h3>
<p><strong>GSS (8 of the 9 modules).</strong> NORC’s terms state: <em>“No part of the contents of NORC websites may be reproduced, stored, or transmitted in any form or by any means, electronic or mechanical, in whole or in any part, without the express written consent of NORC.”</em> There is <strong>no</strong> Creative Commons or public-domain designation. Free-to-download is not the same as free-to-redistribute, and IRW ingestion is redistribution. This does not block <em>analysis</em>; it blocks <em>reposting</em> to Redivis without written consent from NORC.</p>
<p><strong>ANES (1 module).</strong> Public-use data are free but gated behind registration. The precise reuse and redistribution terms could <strong>not be confirmed</strong> — <code>electionstudies.org</code> returns HTTP 403 to automated fetches (see Open items). Recorded as unresolved rather than guessed.</p>
</section>
<section id="item-level-availability-and-scoring" class="level3">
<h3 class="anchored" data-anchor-id="item-level-availability-and-scoring">Item-level availability and scoring</h3>
<p>Item-level responses are available for both GSS and ANES public-use files (they are respondent-level microdata, not scale scores), so the IRW structural requirement is met. One wrinkle the brief anticipated: <strong>Occupational Prestige is a 1–100 rating</strong>, which is a continuous/near-continuous response rather than a Likert item. Note that IRW already contains comparable wide-category tables (the pilot drew <code>test_taking_much_2025_cm</code> at <code>n_categories = 101</code>), so this is a precedent that exists rather than a novel problem.</p>
</section>
<section id="online-appendix-e" class="level3">
<h3 class="anchored" data-anchor-id="online-appendix-e">Online Appendix E</h3>
<p>Appendices A–F are cited throughout the paper as available at <code>http://smr.sagepub.com/supplemental/</code>. That is a <strong>stale generic URL</strong> — it does not resolve to this article’s supplement. The supplement is reachable from the article landing page at <code>journals.sagepub.com/doi/10.1177/00491241211031273</code> (SAGE moved supplemental material there), but retrieving it requires institutional access and was not attempted in this run. <strong>Without Appendix E we cannot reproduce their exact module boundaries</strong>, only guess at them from the Table 8 descriptions.</p>
</section>
<section id="recommendation-per-module" class="level3">
<h3 class="anchored" data-anchor-id="recommendation-per-module">Recommendation per module</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Module</th>
<th>Source</th>
<th>Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Music tastes</td>
<td>1993 GSS</td>
<td><strong>Skip</strong> — blocked on NORC redistribution consent</td>
</tr>
<tr class="even">
<td>Science, religion, spiritualism</td>
<td>1988 GSS</td>
<td><strong>Skip</strong> — same</td>
</tr>
<tr class="odd">
<td>Occupational prestige</td>
<td>1989 GSS</td>
<td><strong>Skip</strong> — same, plus 1–100 response handling</td>
</tr>
<tr class="even">
<td>Economic attitudes</td>
<td>1996 GSS</td>
<td><strong>Skip</strong> — same</td>
</tr>
<tr class="odd">
<td>Mental health causes</td>
<td>2006 GSS</td>
<td><strong>Skip</strong> — same</td>
</tr>
<tr class="even">
<td>Job ideals</td>
<td>2016 GSS</td>
<td><strong>Skip</strong> — same</td>
</tr>
<tr class="odd">
<td>Government spending</td>
<td>2016 GSS</td>
<td><strong>Skip</strong> — same</td>
</tr>
<tr class="even">
<td>Trust in institutions</td>
<td>2016 GSS</td>
<td><strong>Skip</strong> — same</td>
</tr>
<tr class="odd">
<td>Political attitudes</td>
<td>2012 ANES</td>
<td><strong>Ingest-with-caveats</strong> — pending confirmation of ANES redistribution terms</td>
</tr>
</tbody>
</table>
<p>The blocking reason for all eight GSS modules is a single licensing question, not eight separate ones. If someone is willing to email <code>GSS@norc.org</code> for written consent, all eight unblock together, and GSS is a genuinely valuable addition to IRW — large, long-running, publicly documented, and heavily cited. That email is the highest-leverage action in this whole section.</p>
<hr>
</section>
</section>
<section id="open-items" class="level2">
<h2 class="anchored" data-anchor-id="open-items">Open items</h2>
<ol type="1">
<li><code>models_w_noise.RDS</code> — download from Google Drive timed out (curl exit 28). Needed only to reproduce their noise-robustness predictions, not for meta-feature computation.</li>
<li>ANES reuse/redistribution terms — <code>electionstudies.org</code> returns HTTP 403 to automated fetch. Needs a human to read the DUA.</li>
<li>Online Appendix E (per-module variable construction) — behind SAGE institutional access; not retrieved.</li>
<li><code>id</code>-comparability verified on 4 of 114 merge groups.</li>
<li><code>mfe</code> is <strong>archived from CRAN</strong> (installed here from the source archive, with <code>clusterCrit</code>, <code>ECoL</code>, <code>infotheo</code>, <code>rrcov</code> as deps). Any pipeline depending on <code>evaluate.metafeatures()</code> inherits an archived dependency for the <code>PercentOut</code> feature alone.</li>
</ol>
</section>
</section>
<section id="amendment-2026-08-27-follow-on" class="level1">
<h1>Amendment (2026-08-27, follow-on)</h1>
<p>Appended, not rewritten. Everything above stands as originally written. This section revisits threshold 2 on a defensible comparison and establishes the code findings rigorously.</p>
<section id="task-a-threshold-2-on-a-fairer-footing" class="level2">
<h2 class="anchored" data-anchor-id="task-a-threshold-2-on-a-fairer-footing">Task A — Threshold 2 on a fairer footing</h2>
<section id="a1.-like-for-like-dispersion-the-threshold-flips" class="level3">
<h3 class="anchored" data-anchor-id="a1.-like-for-like-dispersion-the-threshold-flips">A1. Like-for-like dispersion — THE THRESHOLD FLIPS</h3>
<p>The original test compared an IRW <strong>IQR</strong> (n=29) against a Table 9 <strong>range</strong> (n=9). That is not like-for-like. All three comparisons, on the 13 comparable features (<code>PercentOut</code> excluded as a scale artifact — see Task B1):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>IRW IQR</th>
<th>T9 IQR</th>
<th>IQR vs IQR</th>
<th>IRW range</th>
<th>T9 range</th>
<th>range vs range</th>
<th>IQR vs range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OverallKurt</td>
<td>0.821</td>
<td>0.695</td>
<td><strong>PASS</strong></td>
<td>8.47</td>
<td>2.30</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="even">
<td>OverallRightKurt</td>
<td>0.120</td>
<td>0.301</td>
<td>fail</td>
<td>0.902</td>
<td>1.06</td>
<td>fail</td>
<td>fail</td>
</tr>
<tr class="odd">
<td>OverallSD</td>
<td>0.756</td>
<td>0.529</td>
<td><strong>PASS</strong></td>
<td>26.5</td>
<td>1.60</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="even">
<td>Skewness</td>
<td>0.395</td>
<td>0.547</td>
<td>fail</td>
<td>3.74</td>
<td>1.31</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="odd">
<td>VarColPC1</td>
<td>17.4</td>
<td>5.68</td>
<td><strong>PASS</strong></td>
<td>2140</td>
<td>46.7</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="even">
<td>SkewColPC1</td>
<td>0.466</td>
<td>0.603</td>
<td>fail</td>
<td>2.68</td>
<td>1.63</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="odd">
<td>SkewColPC2</td>
<td>0.340</td>
<td>0.522</td>
<td>fail</td>
<td>1.27</td>
<td>2.06</td>
<td>fail</td>
<td>fail</td>
</tr>
<tr class="even">
<td>Mean_Row_Corr</td>
<td>0.168</td>
<td>0.223</td>
<td>fail</td>
<td>0.654</td>
<td>0.564</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="odd">
<td>Row_Corr_Kurtosis</td>
<td>0.551</td>
<td>0.735</td>
<td>fail</td>
<td>2.40</td>
<td>3.94</td>
<td>fail</td>
<td>fail</td>
</tr>
<tr class="even">
<td>CorrRightKurt</td>
<td>0.704</td>
<td>0.662</td>
<td><strong>PASS</strong></td>
<td>11.5</td>
<td>2.67</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="odd">
<td>Mean_Col_Kurtosis</td>
<td>0.850</td>
<td>0.412</td>
<td><strong>PASS</strong></td>
<td>8.66</td>
<td>3.61</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="even">
<td>Mean_SD_Ratio</td>
<td>0.0706</td>
<td>0.082</td>
<td>fail</td>
<td>0.456</td>
<td>0.436</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="odd">
<td>intrinsicDimProp</td>
<td>0.0965</td>
<td>0.116</td>
<td>fail</td>
<td>0.389</td>
<td>0.371</td>
<td>PASS</td>
<td>fail</td>
</tr>
<tr class="even">
<td><strong>Totals (of 13)</strong></td>
<td></td>
<td></td>
<td><strong>5</strong></td>
<td></td>
<td></td>
<td><strong>10</strong></td>
<td><strong>0</strong></td>
</tr>
</tbody>
</table>
<p><strong>On the like-for-like IQR-vs-IQR test, 5 of 13 features pass — meeting the “at least five” bar exactly.</strong></p>
</section>
<section id="a2.-excluding-the-high-category-tail" class="level3">
<h3 class="anchored" data-anchor-id="a2.-excluding-the-high-category-tail">A2. Excluding the high-category tail</h3>
<p>Two of 29 matrices have <code>n_categories &gt; 20</code> (<code>test_taking_much_2025_cm</code> and <code>climatechange_geiger_2025</code>, both 101-category rating scales). Dropping them (n = 27):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th>all 29</th>
<th>excl. n_cat&gt;20 (n=27)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IQR vs IQR</td>
<td>5</td>
<td><strong>5</strong> (same five features)</td>
</tr>
<tr class="even">
<td>range vs range</td>
<td>10</td>
<td><strong>6</strong></td>
</tr>
<tr class="odd">
<td>IQR vs range</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>Two things follow, and they point in opposite directions:</p>
<ul>
<li><strong>Your prediction about the range comparison was right.</strong> It drops 10 → 6 when the two wide-category tables are removed, confirming the range advantage was substantially tail-driven and that range at n=29 is outlier-sensitive.</li>
<li><strong>My “tightly packed middle” claim was wrong.</strong> The IQR-vs-IQR pass count is <em>unchanged</em> at 5, and it is the <em>same five features</em> (OverallKurt, OverallSD, VarColPC1, CorrRightKurt, Mean_Col_Kurtosis). The middle of the IRW distribution is genuinely wider than the middle of theirs on those five, and that is not an artifact of the tail.</li>
</ul>
</section>
<section id="a3.-the-n-confound" class="level3">
<h3 class="anchored" data-anchor-id="a3.-the-n-confound">A3. The N confound</h3>
<p>Meta-features recomputed with N capped at 2,000 (matching their ~1,500–2,500 datasets) instead of 5,000. Only <strong>5 of 29</strong> matrices were actually affected.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>N cap 5,000</th>
<th>N cap 2,000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IQR-vs-IQR passes (of 13)</td>
<td>5</td>
<td><strong>6</strong></td>
</tr>
<tr class="even">
<td>median absolute change in IRW IQR</td>
<td>—</td>
<td><strong>1.4%</strong></td>
</tr>
<tr class="odd">
<td>features flipping pass/fail</td>
<td>—</td>
<td>1 (<code>intrinsicDimProp</code>)</td>
</tr>
</tbody>
</table>
<p>The cap is not driving the result. Median IQR shift is 1.4%; the only feature to flip does so <em>toward</em> passing. <code>intrinsicDimProp</code> (+43% IQR) and <code>SkewColPC1</code>/<code>CorrRightKurt</code> (+19%) are the N-sensitive ones, consistent with them being the coarsest/most tail-dependent features. <strong>The objection is closed: correcting the N confound does not weaken the comparison, it marginally strengthens it.</strong></p>
</section>
<section id="reverse-keying-as-a-distribution" class="level3">
<h3 class="anchored" data-anchor-id="reverse-keying-as-a-distribution">Reverse-keying as a distribution</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>n</th>
<th>min</th>
<th>Q1</th>
<th>median</th>
<th>Q3</th>
<th>max</th>
<th>n &gt; 0.5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>single</td>
<td>17</td>
<td>0.058</td>
<td>0.115</td>
<td><strong>0.154</strong></td>
<td>0.368</td>
<td>0.624</td>
<td>2</td>
</tr>
<tr class="even">
<td>merged</td>
<td>2</td>
<td>0.014</td>
<td>0.138</td>
<td>0.262</td>
<td>0.386</td>
<td>0.510</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>By method (singles): CCA median 0.149 (max 0.624), RCA 0.306 (max 0.391), Recursive Relationality 0.115 (max 0.611).</p>
<p>The distribution is <strong>right-skewed, not centered</strong> — most runs sit at 0.06–0.15, with a tail reaching 0.62. A median of 0.154 understates the risk in the same way it overstates the typical case: RCA is the most <em>consistently</em> contaminated (median 0.306, but a tight range), while CCA and Recursive Relationality are usually clean with occasional bad failures. Worth watching, not disqualifying.</p>
</section>
<section id="threshold-2-status-changed" class="level3">
<h3 class="anchored" data-anchor-id="threshold-2-status-changed">Threshold 2: status changed</h3>
<p><strong>Threshold 2 passes under the like-for-like test, and the pass is robust.</strong> 5 of 13 on IQR-vs-IQR with all 29 matrices; the same 5 excluding the high-category tail; 6 of 13 at N = 2,000. The original MISSED verdict was an artifact of comparing an IQR against a range.</p>
<p>Per the brief I am stopping here rather than revisiting the vignette design. Reporting the status change and leaving the decision open. Note the pass is <em>marginal</em> (5 against a bar of 5) and rests on five features of which two — <code>OverallSD</code> and <code>VarColPC1</code> — are scale-dependent and therefore sensitive to the response-category mix of whatever corpus slice is used.</p>
<p><strong>Data:</strong> <code>scouting/A1_dispersion_all29.csv</code>, <code>A2_dispersion_cat20.csv</code>, <code>A3_Nsensitivity.csv</code>, <code>scout_metafeatures_N2000.csv</code>.</p>
</section>
</section>
<section id="task-b1-static-code-audit" class="level2">
<h2 class="anchored" data-anchor-id="task-b1-static-code-audit">Task B1 — Static code audit</h2>
<p>The Drive artifacts are not in version control and the GitHub repo (<code>a617939</code>) contains only a README, so there is no upstream commit SHA to pin. <strong>Findings are pinned by SHA-256 of the files as retrieved 2026-08-27:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>SHA-256</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>metafeature_RCA.R</code> (494 lines)</td>
<td><code>167751976405b6870dcd8e0166d4ef1c9afd948b4c3ddb8a665bb238a4c231cf</code></td>
</tr>
<tr class="even">
<td><code>f_outer.cpp</code> (46 lines)</td>
<td><code>a6a854fa96704521e39abb7dba44645d674834832f933a99cd55c4c670618498</code></td>
</tr>
<tr class="odd">
<td><code>metafeature_models_cleaned.RDS</code></td>
<td><code>38d7b0529123adfd4a61d244d60617b09eb12dfa22575554b4828eab9da21033</code></td>
</tr>
</tbody>
</table>
<p>Reproduction script: <code>scouting/b1_audit.R</code>.</p>
<section id="finding-1-num_vars-10-hardcode" class="level3">
<h3 class="anchored" data-anchor-id="finding-1-num_vars-10-hardcode">Finding 1 — <code>num_vars = 10</code> hardcode</h3>
<p><strong>Location:</strong> <code>metafeature_RCA.R:213</code> — <code>evaluate.metafeatures &lt;- function(df, num_vars = 10)</code>. Used at <strong>line 262</strong> (<code>intrinsicDemnsionalityProp &lt;- intrinsicDemnsionality/num_vars</code>) and <strong>line 268</strong> (<code>PercentOut = ((nrOut/num_vars) * 100)</code>).</p>
<p><strong>Mechanism:</strong> <code>num_vars</code> is never inferred from <code>df</code>. It is the denominator for exactly two of the fourteen features. The other twelve are computed directly from the matrix and are unaffected.</p>
<p><strong>Demonstration</strong> (400 respondents, synthetic):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Matrix</th>
<th>Feature</th>
<th>default (<code>num_vars=10</code>)</th>
<th>correct (<code>num_vars=ncol</code>)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10 items</td>
<td>intrinsicDimProp</td>
<td>0.600</td>
<td>0.600</td>
<td>same</td>
</tr>
<tr class="even">
<td>10 items</td>
<td>all others</td>
<td>—</td>
<td>—</td>
<td>same</td>
</tr>
<tr class="odd">
<td><strong>18 items</strong></td>
<td><strong>intrinsicDimProp</strong></td>
<td><strong>1.000</strong></td>
<td><strong>0.556</strong></td>
<td><strong>diverges</strong></td>
</tr>
<tr class="even">
<td><strong>18 items</strong></td>
<td><strong>PercentOut</strong></td>
<td><strong>170.00</strong></td>
<td><strong>94.44</strong></td>
<td><strong>diverges</strong></td>
</tr>
<tr class="odd">
<td>18 items</td>
<td>other 12 features</td>
<td>—</td>
<td>—</td>
<td>identical</td>
</tr>
</tbody>
</table>
<p>At 18 items the released default returns <strong>PercentOut = 170%</strong> — a percentage exceeding 100, which is impossible by construction and is a self-evident signal of the defect. The <code>intrinsicDimProp</code> failure is quieter and worse: it silently saturates at 1.000.</p>
<p><strong>The documented workflow always hits this path.</strong> <code>select.method()</code> at <code>metafeature_RCA.R:282-287</code> calls <code>evaluate.metafeatures(data)</code> with <strong>no</strong> <code>num_vars</code> argument, and the README instructs users to call <code>select.method()</code>. Any user running the released tool on a matrix that is not exactly 10 items wide gets two corrupted features feeding the method-selection regressions.</p>
</section>
<section id="scoping-question-narrow-erratum-not-broader" class="level3">
<h3 class="anchored" data-anchor-id="scoping-question-narrow-erratum-not-broader">Scoping question — narrow erratum, not broader</h3>
<p><strong>Answer: the defect does not touch the simulation results (Tables 4–7). It is confined to the empirical application.</strong></p>
<p>Evidence: <strong>Table 3</strong> (paper p.1852) lists the grid-search parameters — number of schemas, schema variance, maximum error variance, shift, scaling, probability of inversion. <strong>Item count is not among them.</strong> The text at p.1846 confirms items were fixed: <em>“the original—unshifted and unscaled—schema (i.e., a vector of values for each of the 10 items) is drawn from a normal distribution for each item.”</em> All 198,000 simulated datasets have exactly 10 items, so <code>num_vars = 10</code> is <em>correct</em> on the simulation side, and the fitted regressions in <code>metafeature_models_cleaned.RDS</code> are unaffected.</p>
<p><strong>Further — Table 9 itself appears to have been computed with the correct denominator.</strong> Its intrinsic-dimensionality column is 0.429, 0.357, 0.333, 0.500, 0.200, 0.286, 0.313, 0.571, 0.333. Had <code>num_vars</code> been left at 10, every value would be a multiple of 0.1. They are not: they resolve to 3/7, 5/14, 1/3, 1/2, 1/5, 2/7, 5/16, 4/7, 1/3 — denominators consistent with actual module item counts. So the authors passed <code>num_vars</code> explicitly for the empirical table.</p>
<p><strong>Net:</strong> this is a defect in the <em>released tool</em> as handed to other researchers, not (on the available evidence) an error in the paper’s own published numbers. That is the narrower of the two possibilities, and it should be stated that way.</p>
</section>
<section id="finding-2-overallrightkurt-on-a-logical-vector" class="level3">
<h3 class="anchored" data-anchor-id="finding-2-overallrightkurt-on-a-logical-vector">Finding 2 — <code>OverallRightKurt</code> on a logical vector</h3>
<p><strong>Location:</strong> <code>metafeature_RCA.R:233</code> — <code>overall_right_kurt = Kurt(df &gt; mean(df, na.rm = T))</code>. The intended helper <code>right_half_kurt</code> is defined at <strong>line 217</strong> and, by exhaustive grep of the file, <strong>never called</strong> (single occurrence).</p>
<p><strong>Mechanism:</strong> <code>df &gt; mean(df)</code> is a logical matrix. <code>DescTools::Kurt</code> coerces it to 0/1, so the feature is the excess kurtosis of a Bernoulli indicator — a deterministic function of the proportion above the mean, carrying no information about the shape of the right tail.</p>
<p><strong>Demonstration</strong> (400 × 12 synthetic):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>as released, <code>Kurt(df &gt; mean(df))</code></td>
<td><strong>−1.847932</strong></td>
</tr>
<tr class="even">
<td>as intended, <code>right_half_kurt(as.numeric(df))</code></td>
<td><strong>−1.999943</strong></td>
</tr>
<tr class="odd">
<td>Bernoulli closed form <code>(1−6p(1−p))/(p(1−p))</code> at p = 0.4042</td>
<td><strong>−1.847452</strong></td>
</tr>
</tbody>
</table>
<p>The released value matches the Bernoulli closed form to three decimals, confirming it is a pure function of <code>p</code> and nothing else. This explains the feature’s anomalous behaviour elsewhere: it has the narrowest spread of any feature in the IRW pilot (IQR 0.120) and the lowest reported simulation overlap in Table 9 (3%) — both consistent with a near-degenerate quantity.</p>
</section>
<section id="finding-3-louvain-hardcoded" class="level3">
<h3 class="anchored" data-anchor-id="finding-3-louvain-hardcoded">Finding 3 — Louvain hardcoded</h3>
<p><strong>Location:</strong> <code>metafeature_RCA.R:289</code> — <code>metaRCA &lt;- function(data, measure = "Recursive Relationality")</code>. The signature exposes <strong>only</strong> <code>data</code> and <code>measure</code>. Community detection is fixed at <strong>line 345</strong> (<code>cluster_out &lt;- cluster_louvain(net, weights = E(net)$weight)</code>) and again in the ensemble at <strong>line 446</strong>. Grep for <code>leading.eigen|walktrap|fastgreedy|infomap|spinglass</code> over the file returns nothing — no alternative is implemented or reachable.</p>
<p>This matters because the paper itself reports that swapping leading-eigenvector for Louvain accounted for a meaningful share of RCA’s measured improvement over Boutyline’s baseline. A degree of freedom the authors identify as consequential is not exposed to users of the released tool.</p>
</section>
<section id="finding-4-percentout-scale" class="level3">
<h3 class="anchored" data-anchor-id="finding-4-percentout-scale">Finding 4 — <code>PercentOut</code> scale</h3>
<p><strong>Location:</strong> <code>metafeature_RCA.R:268</code>, <code>PercentOut = ((nrOut/num_vars) * 100)</code>, with <code>nrOut</code> from <code>mfe::statistical(..., "nrOutliers")</code> at line 259. <code>mfe</code>’s documentation defines <code>nrOutliers</code> as <em>“Number of attributes with outliers values”</em> — an integer count of columns.</p>
<p><strong>Mechanism:</strong> <code>PercentOut</code> is therefore an integer count divided by an item count, times 100. It can only take values on the lattice {0, 100/p, 200/p, …} and lies in [0, 100].</p>
<p><strong>Demonstration:</strong> the smallest attainable non-zero value across any plausible item count (p = 40) is <strong>2.5</strong>. Table 9’s published <code>PercentOut</code> column is 0.000, 0.002, 0.002, 0.004, 0.006, 0.007, 0.008, 0.022, 0.048 — <strong>every non-zero entry is at least 50× smaller than the smallest value the released formula can produce.</strong></p>
<p><strong>What transformation would produce those magnitudes?</strong> A <em>cell</em> proportion rather than a <em>variable</em> proportion. Computing the fraction of individual cells that are Tukey outliers across 12 IRW tables gives a range of [0.000, 0.065] with median 0.018 — the same order of magnitude as Table 9’s [0.000, 0.048]. That is consistent with Table 9’s column being the proportion of outlying <em>observations</em>, despite the column being headed “Percent of Variables with Outlier Observations.”</p>
<p><strong>Unresolved hypothesis — stated as such.</strong> Table 9’s intrinsic-dimensionality column is consistent with the released code correctly parameterised (Finding 1), while its <code>PercentOut</code> column is <em>inconsistent with the released formula on any parameterisation</em>. Two features in the same table appear to come from different computations. One reading is that the published empirical meta-features were not produced by the released <code>evaluate.metafeatures()</code>. <strong>That claim is not established here and should not be asserted on this evidence alone.</strong> What would settle it: reconstructing the nine matrices from Appendix E’s item selections and running the released function against published Table 9 (Task B2, currently blocked). A cheaper partial test: if the authors confirm which <code>PercentOut</code> definition was used, the discrepancy either resolves to a labelling/scaling slip in the table or does not.</p>
</section>
</section>
<section id="task-b2-blocked-not-attempted" class="level2">
<h2 class="anchored" data-anchor-id="task-b2-blocked-not-attempted">Task B2 — Blocked, not attempted</h2>
<p>Gate not satisfied. Online Appendix E (per-module variable construction) is required and remains unreachable: <code>journals.sagepub.com/doi/suppl/10.1177/00491241211031273</code> returns <strong>HTTP 403</strong>, as does the paper’s own cited <code>smr.sagepub.com/supplemental/</code>. GSS item-level data is separately blocked pending Task C.</p>
<p>Per instruction, <strong>no reconstruction was attempted from guessed module boundaries.</strong> A failed reproduction from the wrong item selections would be worse than none, and would contaminate the Finding 4 hypothesis above rather than testing it.</p>
</section>
<section id="closed-open-items" class="level2">
<h2 class="anchored" data-anchor-id="closed-open-items">Closed open items</h2>
<ul>
<li><p><strong><code>models_w_noise.RDS</code></strong> — <strong>resolved.</strong> The file had in fact downloaded (96.7 MB, valid gzip); the earlier “timeout” killed the shell after <code>curl</code> completed. However it <strong>fails to load</strong> via <code>readRDS</code> (the companion <code>metafeature_models_cleaned.RDS</code> loads fine and contains 9 fitted <code>lm</code> models, one per distance measure, each with an intercept plus the 14 meta-features). Whether the file is corrupt in transit or in a non-RDS format is undetermined; it is needed only for the noise-robustness predictions.</p></li>
<li><p><strong><code>mfe</code> archived from CRAN</strong> — <strong>resolved with a verified drop-in.</strong> <code>mfe</code>’s rule (<code>mfe/R/statistical.R:353-360</code>) uses <code>stats::quantile</code> (type 7), not <code>boxplot.stats</code> hinges. This four-line replacement reproduces it exactly on 15 random cases:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>nrOutliers <span class="ot">&lt;-</span> <span class="cf">function</span>(m) <span class="fu">sum</span>(<span class="fu">apply</span>(m, <span class="dv">2</span>, <span class="cf">function</span>(x) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  qs <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">quantile</span>(x); iqr <span class="ot">&lt;-</span> (qs[<span class="dv">4</span>] <span class="sc">-</span> qs[<span class="dv">2</span>]) <span class="sc">*</span> <span class="fl">1.5</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  (qs[<span class="dv">2</span>] <span class="sc">-</span> iqr) <span class="sc">&gt;</span> qs[<span class="dv">1</span>] <span class="sc">|</span> (qs[<span class="dv">4</span>] <span class="sc">+</span> iqr) <span class="sc">&lt;</span> qs[<span class="dv">5</span>]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>}))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>No archived dependency is required. (A naive <code>boxplot.stats</code> implementation does <strong>not</strong> match — it disagreed on 1 of 8 test cases.)</p></li>
<li><p><strong><code>Permission via Email</code> count</strong> — corrected: <strong>111</strong> tables, not 106. The exact-string count is 106; a further 5 carry it in combination (e.g.&nbsp;<code>Permission via Email, CC BY 4.0</code>).</p></li>
<li><p><strong><code>id</code>-comparability coverage</strong> — extended from 4 to <strong>24 of 114 merge groups (21%)</strong>. A further 20 groups were sampled across group sizes (2–7 member tables, capped at 4 tables tested per group, 68 tables fetched) and <strong>all 20 verified at 100% minimum pairwise id overlap</strong>. Combined tally: 23 VERIFIED, 1 PARTIAL (<code>alsuhibani_2022</code>, whose ids are namespaced by sub-sample). No new failure modes appeared.</p>
<p>This raises confidence that id-stability is the rule and disjoint sub-samples the exception, but note the sample was restricted to groups with <code>min_n_participants &lt;= 20000</code>, so very large multi-wave studies remain untested. The pairwise-overlap gate should still run inside any real pipeline rather than being assumed — <code>silva_2018</code> is the standing warning: 100% overlap at 3 tables, 0% at 5.</p>
<p>Data: <code>scouting/id_verification_extended.csv</code>.</p></li>
</ul>
</section>
<section id="revised-threshold-table" class="level2">
<h2 class="anchored" data-anchor-id="revised-threshold-table">Revised threshold table</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Threshold</th>
<th>Original verdict</th>
<th>Revised verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Corpus size</td>
<td>MET</td>
<td><strong>MET</strong> (24/114 groups now id-verified)</td>
</tr>
<tr class="even">
<td>2</td>
<td>Feature spread</td>
<td>MISSED</td>
<td><strong>MET (marginal)</strong> — 5/13 like-for-like, robust to tail removal and N cap</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Non-degeneracy</td>
<td>MET</td>
<td><strong>MET</strong> (η² right-skewed, median 0.154 singles)</td>
</tr>
<tr class="even">
<td>4</td>
<td>Compute</td>
<td>MET</td>
<td><strong>MET</strong></td>
</tr>
</tbody>
</table>
<p><strong>All four thresholds are now met.</strong> The original NO-GO rested on threshold 2, and threshold 2 failed only under a comparison that was not like-for-like. Stating that plainly, per instruction, and leaving the decision on the vignette open rather than reopening the design.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/itemresponsewarehouse\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>