---
title: "IMPS 2025 Datathon"
aliases:
  - ../training.html
---

This datathon ran at IMPS 2025. The brief is kept here as it was given, so the task can be reused in a class. The Hearts and Flowers data also appear in the problem [What makes an 'item'?](problems.qmd#what-makes-an-item).

Looking for the workshop slides that used to be on this page? They are now on [Workshops & Slides](workshops.qmd).

## The Challenge: Predicting Accuracy of Executing Functioning tasks

Your task is to develop predictive models leveraging information about the stimulus, response time, and demographic features to predict accuracy on a holdout sample. The Hearts and Flowers (H&F) task is a cognitive task that measures inhibitory control and cognitive flexibility, two components of executive functions. For more information on this task from the group that collected these data, see [here](https://sparklab.stanford.edu/ames). A respondent is shown either a heart or flower on the left or right of the screen. If the shape is a heart, the respondent needs to press the button on the same side whereas if it is a flower they press the button on the opposite side. Participants respond to visual stimuli following simple (congruent: hearts or flowers) or conflicting (incongruent: hearts and flowers) rules. Key features of the dataset include:

* Different task conditions (congruent, incongruent, mixed)

* Response time

* Demographic variables (such as age)

The data are structured in an Item Response Warehouse (IRW)-consistent format (more information available [here](https://itemresponsewarehouse.org/standard.html)).

## The data

The H&F data for the competition were collected from a large urban district in the US. In particular, these data were collected in school environments. Students completed the Hearts and Flowers measures on digital devices during the school day.

The data are available here:

* [Training data](https://www.dropbox.com/scl/fi/ofve08sfpkkfcw4fba258/imps2025_train.csv?rlkey=p3to1voy2ughnzoxv1nmbl7q7&e=1&st=skp9kftd&dl=0)
* [Test data](https://www.dropbox.com/scl/fi/2xjpxdjzme9quzvfpsjgw/imps2025_test.csv?rlkey=z5rn1bv1qnoetg9ksmrr12u9l&e=1&st=eyrbel9y&dl=0)

Note that we are posting two datasets. Best practice is to develop a predictive approach in the training dataset and then report accuracy in the test dataset. 

### Variables

In the competition, you need to predict whether the response is accurate. 

* `resp`: Response accuracy (1 = correct, 0 = incorrect).

The following information is available for prediction.

* `id`: Unique identifier for each respondent.
* `cov_grade`: Respondent’s current school grade level.
* `cov_female`: Respondent’s gender (0 = male, 1 = female).
* `cov_age`: Respondent’s age in years (numeric, continuous).
* `trial_num`: The trial number within the respondent’s task session (starts at 1).
* `resp_side`: Side on which the response was made (either "left" or "right"); can be ignored for scoring (see `resp`).
* `rt`: Response time in seconds.
* `block`: Block label indicating task phase (e.g., "practice", or test condition).
* `time_limit`: Time limit in place for that particular data collection.
* `stim_side`: Side on which the stimulus was shown ("left" or "right").
* `time`: Season during which data were collected (e.g., "Fall").
* `stim_shape`: Shape of the stimulus shown on screen (e.g., "heart", "flower").
* `cohort`: Condition or experimental grouping label (e.g., "plus").

## Hints

We make a few observations about this data to help respondents get oriented with the H&F data.

* The H&F data involve relatively weakly defined 'items'. Rather, persons respond to trials where the stimuli are varying in along several dimensions (e.g., side shape is presented on, what shape is presented, whether the trial is in one of the congruent or incongruent blocks, etc).

* Response time is potentially a valuable predictor of response accuracy. In particular, note that there were different time limits in place at various points of data collection. 

## Judging criteria

We note two criteria that will be used in judging this competition. Some attention will be paid to accuracy in the test dataset; in particular, **please report the root mean squared error between predicted and observed responses in your report**. Specifically, please report the root mean squared error between predicted probabilities (i.e., model-estimated probabilities of a correct response) and the actual binary responses (0 = incorrect, 1 = correct) in the test dataset. Note that there will also be a subjective evaluation of the degree to which the predictive approach is novel or forwards new insights about the nature of the response process. 

## Submission Instructions

Entrants should submit three components (using the below link).

1. A written report should be formatted using Times New Roman 12 point with double spacing and one-inch margins, following the structure below:

  * Cover page (one page maximum) including:

    + Designated Team Lead’s name, email, and affiliation with a graduate program;
    + Name of other team members and their affiliation with a graduate program;
    + Name of the presenter (can be different from the team lead but must be one of the team members) and email.

  * Description (five pages maximum) including:

    + Research question
    + Methodology
    + Key findings **including the RMSE between predicted and actual accuracy in the test dataset**
    + Implications
    + References, optional (one page maximum)

2. Analysis code to ensure reproducibility.
3. Visualizations or slides to effectively communicate insights.

Submissions need to be made [here](https://forms.gle/3GRpyBq9jdWUW7cS8).

## Suggested Readings

* Camerota, M., Willoughby, M. T., Magnus, B. E., & Blair, C. B. (2020). Leveraging item accuracy and reaction time to improve measurement of child executive function ability. Psychological Assessment, 32(12), 1118–1132. <https://doi.org/10.1037/pas0000953>

* Domingue, B.W., Braginsky, M., Caffrey-Maffei, L., Gilbert, J.B., Kanopka, K., Kapoor, R., Liu, Y., Nadela, S., Pan, G., Zhang, L., Zhang, S., & Frank, M. (2025). Solving the problem of data in psychometrics: An introduction to the Item Response Warehouse (IRW). PsyArXiv. <https://doi.org/10.31234/osf.io/7bd54>

* Obradović, J., Sulik, M. J., Finch, J. E., & Tirado-Strayer, N. (2018). Assessing students' executive functions in the classroom: Validating a scalable group-based procedure. Journal of Applied Developmental Psychology, 55, 4-13. <https://psycnet.apa.org/record/2018-17703-003>

* Stanford Project on Adaptation and Resilience in Kids. (n.d.). Assessment of Motivation, Effort, and Self-Regulation (AMES). Stanford University. Retrievable from <https://sparklab.stanford.edu/ames>

* Wu, T., Weiland, C., McCormick, M., Hsueh, J., Snow, C., & Sachs, J. (2024). One Score to Rule Them All? Comparing the Predictive and Concurrent Validity of 30 Hearts and Flowers Scoring Approaches. Assessment, 31(8), 1702-1720. <https://journals.sagepub.com/doi/10.1177/10731911241229566>
